### ISSUE TITLE
Android keys are not backed up outside of App's (local) storage.

### ISSUE THREAD

**Issue by moskovich** [bitmark-inc/autonomy-apps#1]
If you want to use Autonomy to directly manage your seeds (full accounts) you will need to back up your accounts on paper manually. 

We don’t have a good solution to secure seeds (private keys) for full accounts across all Android variants. 

Either use linked accounts, or don’t delete your app.

**Comment by NekhDRej** [comment]
The bug is fixed.
Android build (App center): 0.29.8 (60)
Redmi 8A\Android 10 - fixed

https://user-images.githubusercontent.com/101094775/174049322-ebc32168-ff82-4d2d-9f40-035381533fee.mp4
