### ISSUE TITLE
[Gallery] The artwork ordering changes when the main page is loaded

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#10]
NFT ordering isn't consistent. Many pieces are always in the same spot, but others move when the main page is loaded. If a piece moves, it is usually only a couple positions left or right. This shuffling can happen when navigating between different screens, so it's a little disorienting to return to the previous page and have things be in different spots. This seems to only affect ETH NFTs, but it's possible Feral File also does this (I haven't seen it though)

https://discord.com/channels/768706944097058828/883766547888357386/964016729317597245
Address: 0x184AC16710F9a41fddaF2B62f32E1f13415D459a

**Steps to reproduce:** 
 - Open the app
 - scroll to ETH NFTs
 - click on a thumbnail
 - click the "x" to return to the main page, repeat, repeat, repeat, and you'll at times notice the pieces shuffling around. Not always, not even most of the time, but you should see some of the pieces moving around

https://user-images.githubusercontent.com/42630760/163505897-de162ed1-7c87-4ab4-85f7-b5df30198aa5.MP4

Information:
Build: 0.26.8 (35) (App Center) Device:
- Ip13 pro max OS (15.3)
https://user-images.githubusercontent.com/42630760/164143426-c9cb399a-d294-4cdb-b1a5-34c40cec44b7.mp4

**Comment by NekhDRej** [comment]
The bug is fixed

Android build (App center): 0.29.9 (61)
Redmi 8A\Android 10 - fixed
iOS build (App center): 0.2910 (66)
iPhone 12\iOS 15.5 - fixed
