### ISSUE TITLE
The "Unexpected problem" error is shown on the screen after trying to "Forget I exist" clearing data

### ISSUE THREAD

**Issue by NekhDRej** [bitmark-inc/autonomy-apps#103]
Steps to reproduce:
- Open the Autonomy app
- Go to the settings
- Tap on the "Forget I exist"
- Proceed the forgetting
- Check the error message

Expected result: The clearing data should be successful

Environment:
iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - repro
Android build (App center): 0.29.9 (61)
Redmi 8A\Android 10 - repro

https://user-images.githubusercontent.com/101094775/175063760-6ecdc5c9-285f-467b-8e65-67b691775f2b.mp4

**Comment by hoan-bitmark** [comment]
@lemonlatte I found this issue caused by the endpoint @DELETE("/apis/v1/me") returning 500 error. Can you check it for me? cc @anhnguyenbitmark

**Comment by NekhDRej** [comment]
The bug is fixed

Environment:
iOS build (App center): 0.30.0 (67)
iPhone 12\iOS 15.5 - fixed
Android build (App center): 0.30.0 (63)
Redmi 8A\Android 10 - fixed
