### ISSUE TITLE
Nil, by agoston nagy

### ISSUE THREAD

**Issue by JasonLiuBitmark** [bitmark-inc/autonomy-apps#108]
Collection: [Nil](https://www.fxhash.xyz/gentk/832325)
Creator: [agoston nagy](https://www.fxhash.xyz/u/agoston%20nagy)

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/autonomy-rendering-issues/issues/13

**Comment by hoan-bitmark** [comment]
![Image](https://user-images.githubusercontent.com/106646129/175489977-fe2f160a-646f-42eb-b26d-5469a14ea9b8.png)
The NFT can be displayed from iOS
