### ISSUE TITLE
Missing some artworks and white frame displays for some artwork (The Versum item gaps are not tappable)

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#11]
https://discord.com/channels/768706944097058828/883766547888357386/952331586173538304

Linked but missing wallet:
- kingd.eth
0x171446B041C6683e5F138b8a3f263BBFfb8Ee74a
https://opensea.io/DuaneKing
Below are some missing artworks:
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/16080601057401287728466083465888223137311171705608613108233436077998005551105
https://opensea.io/assets/0x12c8630369977ee708c8e727d8e838f74d9420c5/6429
https://opensea.io/assets/0x12c8630369977ee708c8e727d8e838f74d9420c5/3397

Missing items in Versum / a few placeholder thumbs in Objkt:
- duane.tez
tz1bPMztWzs449CuEmVTY3BprhHMtm4NUQPJ

**Information:**
Build: 0.27.2 (40) (App Center) 
Device:
- Ip13 pro max OS (15.3)

https://user-images.githubusercontent.com/42630760/164364523-cb8eaaf7-d6bc-4cac-805e-eff8b025c45f.MP4

**Comment by hienphan1472** [comment]
This bug is fixed on build 0.29.1 (57)
Device: iPhone 12 (15.3)
