### ISSUE TITLE
WIND SHIFT, by Strangepeo

### ISSUE THREAD

**Issue by JasonLiuBitmark** [bitmark-inc/autonomy-apps#116]
Collection: WIND SHIFT
Creator: [Strangepeo](https://objkt.com/profile/tz1ZgCAhiKdZSrCHG9sCHGdvCogkpkH94Q5p)

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/autonomy-rendering-issues/issues/22

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/autonomy-rendering-issues/issues/22

**Comment by hoan-bitmark** [comment]
This issue is caused by the thumbnail link https://ipfs.io/ipfs/QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc. The link is broken.
