### ISSUE TITLE
METAWATCHER, by angoes25

### ISSUE THREAD

**Issue by JasonLiuBitmark** [bitmark-inc/autonomy-apps#120]
Collection: [METAWATCHER](https://objkt.com/asset/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/604062)
Creator: [angoes25](https://objkt.com/profile/tz1WcEHgjivUndAq5H91gwnjLYTnvD4M45Fj)

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/autonomy-rendering-issues/issues/28

**Comment by hoan-bitmark** [comment]
![Image](https://user-images.githubusercontent.com/106646129/175490807-abb02e6f-6c22-4252-93e1-8459b007bb45.png)

The NFT can be displayed from NFT rendering

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/autonomy-rendering-issues/issues/34

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/autonomy-rendering-issues/issues/35

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/au-support-board/issues/250
