### ISSUE TITLE
Cyclical, by maxdrekker.tez

### ISSUE THREAD

**Issue by JasonLiuBitmark** [bitmark-inc/autonomy-apps#124]
Collection: [Cyclical](https://objkt.com/asset/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/481937)
Creator:[maxdrekker.tez](https://objkt.com/profile/tz1R59PNrWCakcK5uSEiGSgFCwh4EiZwBsmR)

**Comment by hoan-bitmark** [comment]
<img width="380" alt="Screen Shot 2022-06-24 at 5 34 15 PM" src="https://user-images.githubusercontent.com/106646129/175517920-940077d2-3495-4604-a60f-eb0f3335cb17.png">
This NFT can be displayed from NFT rendering
