### ISSUE TITLE
[FaceID] App required FaceID/TouchID when being at Webview screen, but users can ignore it and continue using the app 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#13]
https://user-images.githubusercontent.com/42630760/165423969-ce25791a-ee2a-4e42-9306-ee29b6a4d839.MP4

https://discord.com/channels/768706944097058828/883766547888357386/961137602759639151

**Steps to reproduce:** 
- Enable Touch ID for your account, navigate to an NFT, 
- click on the "Source" button to open the NFT's source page,
- leave the app (but leave running in the background)
- re-open the app, 

--> note that the webpage contents are viewable before you authenticate with Touch ID, click "Cancel," continue to browse the Internet with that browser even though you did not provide Touch ID. Additionally, leaving the app a second time and returning to it will no longer prompt for Touch ID after hitting "Cancel" the first time

**Expected result:**
- The content should not be showed while FaceID/TouchID is required
- Users can not use app if they skip FaceID/TouchID

**Information:**
Build: 0.27.4(44) (App Center) 
Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)

**Comment by NekhDRej** [comment]
The bug is fixed.

iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - fixed

https://user-images.githubusercontent.com/101094775/174804026-b969608c-7ebf-4426-9b90-bf1fe2adbb54.mp4
