### ISSUE TITLE
Blank Setting page displays when user leaving the Address field blank then submit to add the debug address

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1336]
Steps:
1. Install app in App center
2. Navigate to "+ Account->Debug address"
3. Don't enter address
4. Click on Link button

Observe result:
Success message displays. The blank setting page displays after linking.

Expected result:
All buttons should be disabled when user has not entered any data value into the textbox
- [x] Add debug address, 
- [x] Add debug tokenID
- [x] Add Alias
- [ ] Add seeds to restore account

- [ ] API should validate not to submit the null data value for important data.

![IMG_2091CBF4F146-1](https://user-images.githubusercontent.com/109057362/186872909-bafd1d2b-3d54-4b04-a26d-f7eb37f0e522.jpeg)

**Comment by hungqd** [comment]
- [x] Add debug address
- [x] Add debug tokenID
- [ ] Add Alias
- [ ] Add seeds to restore account
- [ ] API should validate not to submit the null data value for important data.
