### ISSUE TITLE
Convertion from XTZ to USD is not corect in Transaction detail page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1427]
Steps:
1. Open an account that has some transaction
2. Navigate to transaction history
3. Click on any transaction
4. Observe the Total Amount value

Observed result: The amount displays USD value is not correct

Expected result:
The conversion from XTZ to USD should be update to correct value
![image](https://user-images.githubusercontent.com/109057362/187113807-bbfae6a5-c259-46a6-9fed-2f6e23d13c6f.png)

**Comment by phuocbitmark** [comment]
fixed in Unified transaction history
