### ISSUE TITLE
There are some artworks have the same black thumbnail display in Collections page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1595]
Please kindly add Vanto Tezos address to debug mode.

Please kindly refer to this link to get the record ID details.
https://docs.google.com/spreadsheets/d/1BlLjmUa9mKIdKubz6-08AB1K842JE7pk/edit?usp=sharing&ouid=107602622851859262464&rtpof=true&sd=true

**Comment by lemonlatte** [comment]
the source data point to black.

```json
"displayUri": "",
"artifactUri": "ipfs://QmQ5FUt2aCF3KxDibonJggLcd2KkKAL7UXZ4Avad88Jw9V",
"thumbnailUri": "ipfs://QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc",
```

How do we address this? If we use the real artwork as thumbnail, it would be have some chances that we set the preview in video. @moskovich 
cc @anhnguyenbitmark @longbmk

**Comment by longbmk** [comment]
https://tzkt.io/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/tokens/77477/metadata
Yes, I double check on this, the thumbnailUri returned a black cover. How can we show to user when we got this issue @moskovich @anhnguyenbitmark ? This is issue from ipfs, not from our side. 

In users view, I think they will always think it is issue from our app, not deeply to know detail is from another party. It's not easy to clarify for user. I suggest we will show the message "Cannot load artwork thumbnail from IPFS" in the thumbnail. 
Thanks all,

**Comment by JasonLiuBitmark** [comment]
@moskovich @anhnguyenbitmark , reminder to give feedback.

**Comment by anhnguyenbitmark** [comment]
To me, we should respect what the metadata provided. If the thumbnail is a black image, the app should show that too.

**Comment by moskovich** [comment]
Agreed with Anh.

**Comment by longbmk** [comment]
Ok. Thank you all. So I think this issue can close because it happens from the metadata provider.
