### ISSUE TITLE
There are some artworks cannot load thumbnail because data return 0 in some specific browser agents

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1596]
Please use Vanto Ethereum/Tezos address to check this issue. (E.g. eth-0xCA5d26fda442bbF604f20CC88289Ea1661863C44-7b)
https://docs.google.com/spreadsheets/d/1BlLjmUa9mKIdKubz6-08AB1K842JE7pk/edit?usp=sharing&ouid=107602622851859262464&rtpof=true&sd=true

**Comment by hungqd** [comment]
Solution: fallback to original IPFS url if can not get file information from Au gateway.

**Comment by hungqd** [comment]
@longbmk for this issued, I've updated the app to fallback to original ipfs url (https://ipfs.io) if autonomy gateway (https://gateway.autonomy.io) failed. If both are fail, we will display error icon. Since it is the IPFS issue, we can't fix in the app.
