### ISSUE TITLE
Missing some artworks of Vanto user in iOS device and Android device

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1597]
Please use Tezos account of Vanto to check this issue. Their detailed address is from lines 52 to 60 in below file.

https://docs.google.com/spreadsheets/d/1BlLjmUa9mKIdKubz6-08AB1K842JE7pk/edit#gid=1119909333

**Comment by longbmk** [comment]
On behalf of @lemonlatte, this is the issue from the ipfs. I think we need confirmation from @moskovich or @anhnguyenbitmark to close this ticket.

The discussion in here:
https://bitmark.slack.com/archives/C01EPPD07HU/p1662604654326419

**Comment by anhnguyenbitmark** [comment]
I think what we are doing is correct.
What I expected here is:
1. We try to load the artwork from the Autonomy IPFS gateway.
2. If it's failed, we will try with another IPFS gateway (preferably cloudflare-ipfs.com)
3. If it's still failed, we consider the IPFS link not valid and display a message to say it is broken.

**Comment by longbmk** [comment]
Yes, we implemented the forwarding to IPFS. If having any issues about IPFS, we will display "IPFS!" to show the problem to user. I think we can close this ticket now. If having any issue, I will create new ticket or reopen this one later.
