### ISSUE TITLE
Can’t swipe right or left for some artworks

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#165]
Steps:
- in Collection page, click an artwork to goto Playback screen.
- Swipe left/ right to move between artworks.

**Comment by thuyenBitmark** [comment]
@NekhDRej : 
Could I confirm that you swipe tokens in normal mode (no cast/full screen mode)?

**Comment by NekhDRej** [comment]
@thuyenBitmark 
The swipe tokens worked as expected in normal mode. Can`t swipe exactly in the full screen mode

**Comment by thuyenBitmark** [comment]
@NekhDRej Can't swipe in the full-screen mode is expected.
Because user can interact (swipe) with artwork (software). so when in full-mode, we don't support swipe to switch between artworks.

**Comment by NekhDRej** [comment]
The issue is fixed

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10
