### ISSUE TITLE
Au Application still connect Beacon wallet although user has not finished the onboarding steps

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1690]
Steps:
1. Make sure user has installed Au app but has not finished onboarding steps
2. Use Chrome browser open objkt.com
3. Sync to Au wallet
4. Wait for application loads

Observed result:
Flow to connect still displays although user has not finished the onboarding steps

Expected result:
User need to finish the onboarding steps, then the Wallet connection displays to link account.

https://user-images.githubusercontent.com/109057362/189567647-c8a98e60-aa43-4b0f-b1c2-6949985f6651.mp4
If you can't view the video in Github, please try in Google driver with your bitmarkl email. https://drive.google.com/file/d/1VfmHfz5eitcofOX1WIGTebnfutySui06/view?usp=sharing

**Comment by caseyalt** [comment]
@Anais-bitmark — can you take a look at this, and we'll discuss it?

**Comment by longbmk** [comment]
Hi @caseyalt @Anais-bitmark ,
I updated the video. This issue happens in case user has not finished the onboarding but still want to connect wallet to NFT exchanges. As the discussion with Anh Nguyen, we think user need to finish onboarding first then connecting to wallet.
Thanks all

**Comment by caseyalt** [comment]
@longbmk — it looks ok for me on my Pixel: 

 
![Au Pixel 6 Collection](https://user-images.githubusercontent.com/1546286/189797632-59de3b97-a32f-4aad-abd2-319cd70d99aa.png)

![Au Pixel 6 Settings](https://user-images.githubusercontent.com/1546286/189797653-cd20ae79-3a5e-4cf7-984f-24821b52846a.png)

**Comment by caseyalt** [comment]
@longbmk — it still isn't working on GItHub for me, but it worked on Google Drive. How were you able to get to the connection screen from the launch screen? I agree with you and Anh that the user should need to finish the onboarding first before connecting to a wallet, but isn't that already the flow? How would they be able to connect to a marketplace like you did?

**Comment by longbmk** [comment]
@caseyalt 
Yes, it happens when I use chrome browser in mobile device. Please notice that this device has already installed Au app without onboarding then open the marketplace exchange in Chrome mobile browser and continue.
Thanks Casey

**Comment by Anais-bitmark** [comment]
@longbmk Who is supposed to fix it?

@moskovich Could you have a quick look?

[Figma](https://www.figma.com/file/U5VPJFLteVfvtEooLfQ9Yo/Au-Application-still-connect-Beacon-wallet-although-user-has-not-finished-the-onboarding-steps?node-id=5%3A4615)

<img width="1212" alt="Capture d’écran 2022-09-15 à 16 01 56" src="https://user-images.githubusercontent.com/61187455/190452238-fffa1d8c-96c2-4be5-9ad5-af4115713010.png">

**Comment by longbmk** [comment]
@Anais-bitmark I think @hvthhien will fix it because he implemented Defer Deeplink but this ticket is still new to delay to the next cycle because it is a lower priority. We need to finish Defer Deeplink first

**Comment by moskovich** [comment]
Good idea to use DDLs here.
