### ISSUE TITLE
There is stranger icon displays in confirmation message in Sign connection page when user connect the Tezos wallet

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1698]
Steps:
1. Connect the Wallet to exchange by Tezos beacon wallet connection
2. Back to AU and wait for Connect page
3. Click on Connect button
4. Observe the Confirmation message

Observed result:
There is a stranger icon displayed in the Confirmation message.

Expected result:
There is no the stranger icon in Confirmation message.
![image](https://user-images.githubusercontent.com/109057362/189257453-d949ab90-de07-48b8-a4f7-9aad9db7fdcf.png)

**Comment by phuocbitmark** [comment]
Test acceptant list:
 - No the stranger icon in Confirmation message, only display "Tezos Signed Message:...."

**Comment by phuocbitmark** [comment]
Fixed
![Screenshot_20220912-125614_Autonomy (Dev)](https://user-images.githubusercontent.com/110799144/189583219-d95ca803-cb29-4528-aa6b-b06a36f858a3.jpg)
