### ISSUE TITLE
[Playback] The Image is cropped on Gallery / Token Detail and playback screens

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#17]
Address: 0xd1b9d2f4b77c20e3b612ea3112c477d268268797

Information:
Build: 0.27.4(44) (App Center) 
Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)
https://user-images.githubusercontent.com/42630760/165725505-26f28a80-d016-4231-8b31-9462289071e1.MP4

**Comment by NekhDRej** [comment]
The issue is fixed

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5

https://user-images.githubusercontent.com/101094775/178716608-25e6738f-c16e-4f7c-baec-dec5e0440b5f.mp4
