### ISSUE TITLE
Eula page with error content displays when clicking on Eula link in Start page of Onboarding steps

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1719]
Steps:
1. Navigate to Start page of Onboarding steps
2. Click on EULA link
Observed result:
The error page display

Expected result:
Data Eula load successfull
https://user-images.githubusercontent.com/109057362/190082662-68227196-88a2-411b-a9c0-508936ebf3ee.MP4

**Comment by trunghq17520184** [comment]
hi @moskovich, could you give me the correct link to the EULA page? Currently, we use "https://raw.githubusercontent.com/bitmark-inc/autonomy-apps/main/docs/eula.md" but it responses 404 not found.

**Comment by moskovich** [comment]
We don’t have this anymore. We don’t need a EULA since we’re open source now. 

@Anais-bitmark could you give him the new designs here?

**Comment by Anais-bitmark** [comment]
@moskovich I didn't treat this one yet. I thought we could put it as UI/UX improvement for next cycle. Is it urgent ?

**Comment by moskovich** [comment]
Up to you. You can prioritize this. We're ready for it.

**Comment by trunghq17520184** [comment]
hi @moskovich, @Anais-bitmark, if we put it to next cycle, what would we display in this screen?
Currently, AU is displayed as below
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-15 at 14 14 30](https://user-images.githubusercontent.com/45090989/190339289-a2c79a94-3e4b-41d0-a2d7-ca109e4a54f2.png)

**Comment by Anais-bitmark** [comment]
@trunghq17520184 
I provided the UI for this UI improvement [Update footer text on Launch screen.](https://github.com/bitmark-inc/autonomy/issues/1547#top)
It would solve this problem.
I will ask @phuocbitmark if he can treat this late UI improvement.
