### ISSUE TITLE
There is a specific artwork still play in background when navigating to Artwork infor page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1720]
Please add this artwork debug token to check:
tez-KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi-1151981
https://user-images.githubusercontent.com/109057362/190084910-16211344-40ce-42e9-9a81-364464e2c594.MOV

**Comment by trunghq17520184** [comment]
hi @longbmk, this is special artwork. So we can't fix it. Thank you

**Comment by longbmk** [comment]
Ok @trunghq17520184.  We will take a deep look at this issue in the future when having many issues like this. As the discussion with you and @hvthhien, I will close it. 
Thank you
