### ISSUE TITLE
It take too much time to indexing data for an artwork in Discovery (more than 24h)

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1721]
Please kindly add this debug address and check the discovery at the 1st record
tz1f6UyafTfyoBHStmEqcpfjA855rf26g2Nn

https://user-images.githubusercontent.com/109057362/190095575-0b23444e-f786-49aa-9a63-8960d5a22d50.MP4

**Comment by lemonlatte** [comment]
Will add a token check from the query function to trigger the indexing process for the missing tokens.
@minhkstn

**Comment by minhkstn** [comment]
@longbmk I believe this bug is already fixed and can be moved to Done

**Comment by longbmk** [comment]
Ok. I imported this address and it is fixed. Let me close it. Thank you
