### ISSUE TITLE
Keep receiving notification from new feed in discovery, but Discovery feed is not updated.

### ISSUE THREAD

**Issue by Anais-bitmark** [bitmark-inc/autonomy-apps#1766]
Keep receiving these notifications (too much by the way) but latest feed I can see in Discover it's from 9 days ago.

![IMG_0084](https://user-images.githubusercontent.com/61187455/192525232-086dbac4-7d2e-4e8a-931e-8c0c8bbfee38.PNG)

![IMG_F9D83FB9F259-1](https://user-images.githubusercontent.com/61187455/192525473-3b7ff0c7-e415-4149-94a0-2db3307909ab.jpeg)

**Comment by Anais-bitmark** [comment]
@longbmk Who can investigate?

**Comment by hxw** [comment]
there was a problem with the cadence client config in the event feed service, i changed `cadenceau-frontend` → `cadence-frontend` and redeployed - now waiting to see if index workflows triggers still cause errors

**Comment by hxw** [comment]
One error: 
```
| time="2022-09-28T02:02:46Z" level=error msg="start index workflow failed" contract=0xC36442b4a4522E871399CD717aBDD847Ab11FE88 error="WorkflowExecutionAlrea │
│ dyStartedError{Message: Workflow execution is already running. WorkflowId: index-single-nft-0xC36442b4a4522E871399CD717aBDD847Ab11FE88-325671, RunId: 4bcec │
│ e2a-b818-4bfc-bc2d-867f803b5e63., StartRequestId: 1c27c99a-9c9f-4f25-8190-f7bfd1f7d83b, RunId: 4bcece2a-b818-4bfc-bc2d-867f803b5e63}" recipient=tz1S6qay6bQ │
│ Xz5PzyZMpJ2j5m3zhTqm85i8Y token_id=325671                                                                                                                   
```

This would suggest that indexing is triggering now.

However if the same token has multiple events in a short period of a repeat of the same index operation will give this error because the first is not finished yet, Maybe this should be fixed to suppress these duplicate index requests

**Comment by hxw** [comment]
currently debugging on dev

**Comment by hxw** [comment]
@longbmk I have the modified version running on DEV - Would you test it?

**Comment by lemonlatte** [comment]
[0.5 units] fix the incorrect environment for pushing events on production

**Comment by hxw** [comment]
[1 unit] reorganise the event background queue

the process is now:
- webhook 
    - saves event either livenet or testnet is ok
    - queues the event_id for distribution
- worker processes (currently 3)
    - take an item off the queue
    - if event's network is not in the "networks:" config list (you can add either/both testnet and livenet to config) event is ignored
    - a workflow to index the token is started
    - worker waits for event to be indexed - if this fails abort
    - set the indexed flag in the event record
    - compute followers
    - add to each followers feed
    - if a user is ready send an event and record when sent (config sets interval for next notification rate limit: 60s dev; 10min prod)

in my test over 40 min I received 4 notifications for 34 feed events created, more events were received, but those that failed to index were not present in the feed.

**Comment by hxw** [comment]
@longbmk I think this is ok now.

However since the indexer only returns error status I cannot add artist or artwork to notification, but I think this is now in a new story

**Comment by longbmk** [comment]
Yes @hxw,
The notification no longer send to user, but the discovery it seems still indexing with too much time. This is issue https://github.com/bitmark-inc/autonomy-apps/issues/1721. Can you please help @lemonlatte take a look on it?

Thank you very much
