### ISSUE TITLE
User is unable to sync with objkt.com via Safari

### ISSUE THREAD

**Issue by caseyalt** [bitmark-inc/autonomy-apps#1770]
https://github.com/bitmark-inc/au-support-board/issues/569

**Comment by longbmk** [comment]
https://github.com/bitmark-inc/autonomy-apps/issues/1771
I also logged the ticket but it is later than Casey ticket. So I will close it but please kindly notice the root cause is the application has not opened. I discuss with Hien about it. Thank you

**Comment by hvthhien** [comment]
This should be fixed on the Web

**Comment by longbmk** [comment]
This issue no longer happens
