### ISSUE TITLE
An empty Discovery page displays when clicking on a Discovery push notification

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1773]
An empty Discovery page displays when clicking on a Discovery push notification. It should displays the corresponding artwork from this artist

**Comment by phuocbitmark** [comment]
@longbmk the notification right now doesn't contain any data to determine the artwork, so it just check new feeds and show it. 
-> This isn't a bug right?
if so, should we close the issue

**Comment by longbmk** [comment]
Ok let me close it. We will apply update notification message in the futures
