### ISSUE TITLE
Subscription screen still display in a new phone although user had subscription in Google store

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1777]
Steps:
1. Open the Autonomy app 
2. Add subscription for Autonomy app (user sandbox account)
3. User another phone with the same as Google account
4. Open the Autonomy app
5. Navigate to some next screen

Observed result:
- Subsciption screen still displays. It should be hidden when user has already subscription
- Subscription should be loaded by default for Setting

![Screenshot_20221006-104805_Autonomy](https://user-images.githubusercontent.com/109057362/194216613-d9aca5b4-f7ab-4d2d-8e42-f0d5082d0fc4.jpeg)

https://user-images.githubusercontent.com/109057362/194216622-cf7015fb-b7fc-48c1-9d56-834af8837396.mp4

**Comment by hungqd** [comment]
@longbmk, as current implementation, the app is not restore the purchase since there is no account yet. I think we have to move the subscription screen to after account is created.

@Anais-bitmark, could you help redesign the flow here? Thank you.

**Comment by Anais-bitmark** [comment]
@hungqd @moskovich 

So actually I think we could by default remove 2 screens from the onboarding:
- Notifications/ Analytics : Notifications we can use the same mechanism as for MoMa with the red badge in Settings to give them a hint to enable it. Analytics from what I understood, they are enabled by default so it doesn't really make sense to offer it in the onboarding. They can disable them in settings.
- Subscription: First I doubt people will be willing to subscribe (with or without trial) without having explored the app beforehand. So I believe we can use the same mechanism as for notifications (red badge), and if notifications are enabled, we could send an in-app notification shortly after they start using the app (48h? TBD) saying something like 

> DO YOU WANT MORE AUTONOMY?
> START YOUR 30 TRIAL TODAY

It would lead them to the subscription screen.

What are your thoughts about it?

[Figma](https://www.figma.com/file/zqYaRcgMFV4c3tcjcj9dS8/Untitled?node-id=0%3A1)

<img width="1705" alt="Capture d’écran 2022-10-11 à 11 40 53" src="https://user-images.githubusercontent.com/61187455/195080421-777b3b35-b28c-4356-861a-07a296b52d25.png">

**Comment by moskovich** [comment]
Yes. I'm good with this. Please do remove both of those.

**Comment by hungqd** [comment]
[1 units] Update onboarding flow.

**Comment by hungqd** [comment]
[0.5 units] Update onboarding flow.

**Comment by Anais-bitmark** [comment]
@longbmk 
What is the status of this ticket ?
So I can update UI
