### ISSUE TITLE
Au application always shows Notification popup when killing application then reopen it

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1786]
Steps:
1. Open Au app
2. Finish the onboarding app
3. Accept the Notification
4. Kill Au application
5. Reopen Au application

Observed result:
Notification popup displays

Expected result:
Current setting should retain and no need to ask user to show Notification or not.
https://user-images.githubusercontent.com/109057362/195018963-658e7127-34cc-4ca5-a285-3bf992515a6e.MP4

**Comment by trunghq17520184** [comment]
[0.25 units] fix bug
