### ISSUE TITLE
UI in some specific iphones is deformed in Onboarding screen and Notification screen

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1789]
iPhone SE:
![image](https://user-images.githubusercontent.com/109057362/195249083-891d202f-b52a-415f-a86a-f252e0a392d5.png)

iPhone 7 plus:
![image](https://user-images.githubusercontent.com/109057362/195249106-66caba11-69ee-4583-af32-9ca07e7d2364.png)

**Comment by longbmk** [comment]
Tested in iPhone SE from Hoang Nguyen

**Comment by trunghq17520184** [comment]
[0.5 units] update UI for iPhone SE
