### ISSUE TITLE
Application is stucked at splash screen after update the old version 0.32.2 to new version 0.33.3

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1790]
There are some specific iphone has got this issue: iPhone 7 plus, iPhone SE, iPhone 13 promax.

Steps:
1. Install production build 0.32.2
2. Onboarding app
3. Leave app without using some days
4. Install the new app version in Testflight
5. Open the application

Observed result:
Application is stuck at splash screen

Expected result:
Application should work correctly without any error
![image](https://user-images.githubusercontent.com/109057362/195265153-3a294396-5616-43b5-9774-232861059a7f.png)

**Comment by hvthhien** [comment]
This issue looks like failing during the migration of local databases. Most likely only happens when testing some pre-release versions (when user downloads the AppStore version then downgrades to a lower testflight version then upgrades again). 

This will not happen in production.
