### ISSUE TITLE
The text "iCloud Keychain" of iOS displays in the "Backup recovery phase" page of Android

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1794]
![image](https://user-images.githubusercontent.com/109057362/195487347-d43f578b-7a6a-4ffd-9c73-1b5d1fbacdb2.png)

**Comment by phuocbitmark** [comment]
@longbmk 
IOS device: 
- text: iCloud Keychain; 
- ontap -> https://github.com/bitmark-inc/autonomy.io/blob/main/apps/docs/security-ios.md
Android device:
- text: Android Block Store; 
- ontap -> https://github.com/bitmark-inc/autonomy.io/blob/main/apps/docs/security-android.md

**Comment by Anais-bitmark** [comment]
@phuocbitmark 
[Figma](https://www.figma.com/file/mz2o5Ia4KLGFzmMUCUUKjZ/Au-bug_1794%3A-The-text-%22iCloud-Keychain%22-of-iOS-displays-in-the-%22Backup-recovery-phase%22-...?node-id=0%3A1)

<img width="1500" alt="Capture d’écran 2022-10-13 à 11 44 14" src="https://user-images.githubusercontent.com/61187455/195587620-002b3590-d993-4877-969c-32a4925cb938.png">

**Comment by phuocbitmark** [comment]
[0.25 units] change the keychain text, add link git hub
