### ISSUE TITLE
Sometimes, account is hidden in setting is automatically change to show after minimize/kill app then reopen

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1795]
![image](https://user-images.githubusercontent.com/109057362/195490600-b7237b31-dbf4-4144-87b1-0b1bd39b38b8.png)

**Comment by trunghq17520184** [comment]
[0.5 units] Fix bug backup hidden account

**Comment by longbmk** [comment]
This issue no longer happens
