### ISSUE TITLE
[Bug] User open this artwork but TV app/Mac mini app open another artwork when source casting account imports many accounts that have artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1798]
[Bug] Artworks index is wrong. Open this artwork but it open another artwork. This issue happens when import many address and load to Mac mini app at the first time.

Please contact me, I will give you the list of address to debug.

Thank you

**Comment by trunghq17520184** [comment]
[1 unit] fix bug index artwork

**Comment by longbmk** [comment]
[0.25 unit] check for fixed bug
