### ISSUE TITLE
Artwork sorting in TV app/Mac mini app is not the same as Collections view in source casting device

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1799]
Steps:
1. Import many accounts to mobile device
2. Scan to cast artworks to TV app/Mac mini app
3. Compare artwork sorting in app and mobile app

Observed result:
Artworks in TV app/Mac mini are not sorted as mobile app.

Expected result:
Artworks in TV app/Mac mini are sorted the same as mobile app

**Comment by trunghq17520184** [comment]
[0.5 units] apply NFT collection library

**Comment by longbmk** [comment]
[0.25 unit] Check for fixed bug
