### ISSUE TITLE
[FaceID] Passcode should be required when users enable FaceID 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#18]
**Steps to reproduce:**
1. Launch Autonomy App
2. Enable Face ID

**Observed result:**
Users can enable without entering passcode

**Expected result:**
Passcode should be asked

**Information:**
Build: 0.27.4(44) (App Center) 
Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)

https://user-images.githubusercontent.com/42630760/165736351-0318c524-f26e-422b-8236-882b92230902.MP4

**Comment by NekhDRej** [comment]
The task is done

iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - done

https://user-images.githubusercontent.com/101094775/175340477-814e00dc-0a96-45ab-ad1e-909614bbd733.mp4
