### ISSUE TITLE
iOS-Missing waiting popup displays in Au app when user click on Connect button in WalletConnect/Beacon WalletConnect in mobile browser

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1816]
Steps:
1. Open Chrome/Safari mobile browser
2. Navigate to FeralFile.com
3. Click on Tezos to Signin with Beacon wallet connect
4. Observe the AU app

Observed result:
AU app does not show the waiting popup after automatically open from mobile browser. 

Expected result:
It should have a popup to wait for WalletConnect/Beacon WalletConnect displays when browser open Au app

**Comment by phuocbitmark** [comment]
fixed in [Missing waiting popup when user scan QR code for an airdrop/walletconnect/Beacon walletconnect/add collection from FF #1820](https://github.com/bitmark-inc/autonomy-apps/issues/1820)
