### ISSUE TITLE
Artwork still displays in User collections a little time although user has sent it to another address

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1818]
Currently, the sent artwork still needs a little time to confirm the transaction and wait for the indexer update. So that artwork still keep retained in the collection 
Steps:
1. Add an account that has at least 1 artwork
2. Send this artwork to another account
3. Observe the current collection

Observed result:
The sent artwork still displays in Collections page

Expected result:
Collections page should display after sending artwork success.
The sent artwork should be removed out of Collections after sending success.
The sent artwork should be query and remove out of local hidden artwork list.
![image](https://user-images.githubusercontent.com/109057362/196854785-e705821d-1b09-42b9-848a-20647553675f.png)

**Comment by phuocbitmark** [comment]
Should consider these cases:
- Wallet has multiple accounts and user sends that NFT among these accounts
- Hidden artworks

**Comment by phuocbitmark** [comment]
@longbmk Test acceptant criteria (additional to "Expected result")
- for 1155 token, if sent quantity < token own => not hiding artwork, not navigating to collection view.

**Comment by phuocbitmark** [comment]
[0.75 units] after sending token: hide token for 10 minutes, navigate to home if that user is no longer own that token
