### ISSUE TITLE
Sometimes, user cannot attach debug log/send request

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1819]
Sometimes, user cannot attach debug log/send request. We cut the logs but just send event it when minimizing app. We should update to cut the logs to below 1MB when sending logs.

![image](https://user-images.githubusercontent.com/109057362/196870465-53f72d19-7679-404e-8f14-fbb4bda5abaa.png)

**Comment by phuocbitmark** [comment]
[0.25 units] limit debug log size to 1 MB

**Comment by phuocbitmark** [comment]
![Uploading Screenshot_20221020-160615_Autonomy (Dev).jpg…]()

**Comment by phuocbitmark** [comment]
![Screenshot_20221020-160615_Autonomy (Dev)](https://user-images.githubusercontent.com/110799144/196912038-1204dfbe-8b45-4b64-bd83-3da7b0778166.jpg)
