### ISSUE TITLE
Missing waiting popup when user scan QR code for an airdrop/walletconnect/Beacon walletconnect/add collection from FF

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1820]
We need to add a popup to wait for data in these cases:
- [ ] Use Camera app scan and open Au app
- [ ] Scan a QR code for airdrop
- [ ] Scan a QR code for walletconnect
- [x] Scan a QR code for Beacon walletconnect
- [ ] Scan a QR code for add collection from FF

**Comment by Anais-bitmark** [comment]
@longbmk 
Please find the UI for this bug here.

I did it last week but I didn't have the link of the bug on GitHub.

[1 unit]

[Figma](https://www.figma.com/file/ycQCGmZmkZAsmM0BdrgNX8?node-id=0:1&comments-enabled=1)

**Comment by phuocbitmark** [comment]
@longbmk Use Camera app scan and open Au app: <-- this is for airdrop rights?

**Comment by phuocbitmark** [comment]
[0.5 units] implements pop up for Beacon walletconnect, test waiting time for other cases

**Comment by phuocbitmark** [comment]
There only 2 things need to be implemented this time:
- Pop up for beacon connect
- Notifications.

**Comment by phuocbitmark** [comment]
@ppupha please review UI in branch waiting_popup

**Comment by phuocbitmark** [comment]
[0.25 units] notify when notification enable, add icon
