### ISSUE TITLE
Spinner spin never end and show error message when opening Discovery at the first time

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1829]
1. Import some existing account that has Discovery event.
2. Open Discovery
3. Scroll next to show artwork.

![1666585548351](https://user-images.githubusercontent.com/109057362/197448452-fc1a855d-10c6-41c5-8610-0a0dfbe8a3d0.JPEG)

https://github.com/bitmark-inc/au-support-board-test/issues/1154

This issue happens in dev environment.

**Comment by hxw** [comment]
Do we have any log for this case to show the API call that failed?
Is this an Ethereum account that was imported?
