### ISSUE TITLE
The Discovery artwork still display the artwork that user has bought into user collection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1830]
Steps:
1. Buy an artwork in any NFT exchange
2. Wait for discovery event feed displays
3. Observe some artwork in Discovery

Observed result:
The artwork user has bought displays in Discovery

Expected result:
It should filter to not display Discovery artwork that user has in the collection
![IMG_F2F923D48F7D-1](https://user-images.githubusercontent.com/109057362/197458239-9d48069d-aa35-4496-9b58-12637e6f3d85.jpeg)

**Comment by hungqd** [comment]
[0.25 units] Fix bug
