### ISSUE TITLE
There are some duplicated artwork display in Discovery

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1831]
1. Buy artwork in the account added to Au app
2. Repurchase this artwork for another account added to Au app
3. Wait for Discovery event
4. Observe the artwork in Discovery mode

Observed result:
There is a duplicated artworks display in Discovery mode.

Expected result:
The duplicated artwork should be removed.  
https://user-images.githubusercontent.com/109057362/197458945-5bb14182-4ba1-4afb-aa19-27811f6f9a88.MP4

**Comment by hungqd** [comment]
Hi @hxw, could you please help check the feed api? There are feed events duplication, it only difference in id and timestamp.

<img width="443" alt="Screen Shot 2022-10-24 at 14 17 38" src="https://user-images.githubusercontent.com/12369158/197469242-867429f7-2e77-47d6-a8f3-13c17ffa28a3.png">

**Comment by hungqd** [comment]
[0.25 units] Fix bug

**Comment by longbmk** [comment]
I can't check this issue because the discovery is indexing too much in Staging. Let me check with @hxw and then will back soon. Thank you all

![Image](https://user-images.githubusercontent.com/109057362/198860387-dd3776db-6086-42ae-adb0-9cc7a3ec2e67.PNG)
