### ISSUE TITLE
User is still able to transfer artwork many times although this artwork has sent to another address

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1832]
Steps:
1. Open an artwork detail
2. Send the artwork to another address
3. Retry to send the artwork to another address
Observed result:
Estimate still success. User is still able to submit to send artwork again

Expected result:
The estimate should be failed and user is not able to submit to send artwork again after sent it.
https://user-images.githubusercontent.com/109057362/197462912-e6116ae9-781e-4691-aabe-02d54c3a588c.MP4

https://user-images.githubusercontent.com/109057362/197462925-8f578f39-3fad-4433-9b5d-a6cd27047233.MP4

https://user-images.githubusercontent.com/109057362/197462938-ac3e011c-2f84-46a9-aaae-a4190b8790ec.MP4

**Comment by phuocbitmark** [comment]
This will be fixed in Artwork still displays in User collections a little time although user has sent it to another address [#1818](https://github.com/bitmark-inc/autonomy-apps/issues/1818)
