### ISSUE TITLE
Redundant Max Edition and Artist display in Transfer artwork page when user transfers an airdrop artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1834]
![image](https://user-images.githubusercontent.com/109057362/197508889-0e3f3c24-3448-4ddb-add5-23f09ffd718c.png)

**Comment by hungqd** [comment]
@Anais-bitmark, for this bug
- If artist is empty, we will hide the artist section.
- If maxEdition = -1, we will show only the edition number.

Is it ok?

**Comment by Anais-bitmark** [comment]
@hungqd 

You are right, please double check the design here 

[Figma](https://www.figma.com/file/TOdpHN1lPTC6LEaujhxfvn/Au-bug_1834%3A-Redundant-Max-Edition-and-Artist-display...?node-id=0%3A1)

[0.1 unit]

<img width="1669" alt="Capture d’écran 2022-10-26 à 09 17 51" src="https://user-images.githubusercontent.com/61187455/197987618-6dc42e50-b894-4176-9e30-ec756bc81ad9.png">

**Comment by Anais-bitmark** [comment]
Can you also fix that @hungqd ?

<img width="682" alt="Capture d’écran 2022-10-26 à 09 23 17" src="https://user-images.githubusercontent.com/61187455/197988900-56ce3b78-be86-48dd-b1ce-79864a6b89d8.png">

**Comment by hungqd** [comment]
Thanks @Anais-bitmark, I can fix it.

**Comment by hungqd** [comment]
[0.3 units] Fix bug
