### ISSUE TITLE
Artwork still plays although user navigated to Artwork Infor page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1838]
Artwork still plays although user navigated to Artwork Infor page. This issue happen when loading artwork info before the artwork audio loads.
Please use this ID to check: tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-467603

https://user-images.githubusercontent.com/109057362/197744132-d039c00d-4b7b-4332-a424-5049042a5dbb.mp4

**Comment by hungqd** [comment]
[0.5 units] fix bug
