### ISSUE TITLE
TV app - Sometime, artwork displays "unsupported token" but still play audio correctly

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1839]
Please use this ID to debug in TV app.
tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-505853

**Comment by phuocbitmark** [comment]
Currently, we use "unsupported token" widget for all artwork that fails to load. But, in case of audio, we can have the audio loaded and played, but the thumbnail is failed to load. thus, created this bug.
@Anais-bitmark should we change "unsupported token" to something like "unsupported thumbnail" or "failed to load thumbnail" ?

**Comment by phuocbitmark** [comment]
[0.25 units] research the problem
