### ISSUE TITLE
Money in USD conversion display scientific math type instead of normal user number

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1841]
1. Deposit 1 Ethereum/10000 Tez to Au.
2. Go to Account Balance/History page
3. Observe USD conversion number
![image](https://user-images.githubusercontent.com/109057362/197933158-8451f2fb-945e-479c-a702-b773101bc78e.png)

**Comment by hungqd** [comment]
[0.25 units] Fix bug
