### ISSUE TITLE
Missing a popup to show invalid chain when scanning connection to an invalid blockchain

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1842]
1. Open Au app production
2. Scan QR code to connect for FF testnet
3. Observe Au app

Observed result:
Missing the popup to show invalid chain

Expected result:
There should be a message to show invalid chain when connection invalid.

Please kindly help us design for this case @Anais-bitmark. Thank you

**Comment by Anais-bitmark** [comment]
@phuocbitmark 
You can use this new version of the message until I get feedback from Casey.

[0.25 unit]
[Figma](https://www.figma.com/file/ycQCGmZmkZAsmM0BdrgNX8/Au-bug_1842%3A-Missing-a-popup-to-show-invalid-chain-when-scanning-connection-to-an-invalid-blockchain?node-id=0%3A1)


<img width="505" alt="Capture d’écran 2022-10-26 à 09 37 06" src="https://user-images.githubusercontent.com/61187455/197992070-bf90b11e-5b03-49d7-8b4b-891519662c76.png">

**Comment by longbmk** [comment]
@Anais-bitmark I mean we should have a popup to display an invalid to handle for all cases user use AU app to scan any stranger's QR code. Can you please help us on this.
Thank you

**Comment by Anais-bitmark** [comment]
@longbmk 
UI is ready
Can you push to an engineer to build it?

[Figma](https://www.figma.com/file/U4KQpeonL8JdvuH67GSZ22/Au-bug_1842%3A-Missing-a-popup-to-show-invalid-chain-when-scanning-connection-to-an-invalid-blockchain?node-id=0%3A1&t=7cWYq6dGSxFG4Isa-1)
[0.25 unit]UI

<img width="797" alt="Capture d’écran 2023-01-18 à 15 01 57" src="https://user-images.githubusercontent.com/61187455/213205923-5484f3c6-9dad-415d-a4e3-8272b64822a3.png">

**Comment by longbmk** [comment]
Thanks Anais,

Can you please take a look on it @phuocbitmark ?

**Comment by phuocbitmark** [comment]
@longbmk this is actually fixed by @trunghq17520184 on branch develop, i only fixed clearing error after 4 sec and button padding

**Comment by Anais-bitmark** [comment]
@phuocbitmark @trunghq17520184 @longbmk 
Can we update the status of this bug if it has been resolved?
