### ISSUE TITLE
Au Viewer cannot load some artworks thumbnail for LAW show

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1852]
1. Please use build 0.34.6 and enable Demo mode
2. Scan QR code to show artwork to TV app
3. Observe the list of artworks
https://user-images.githubusercontent.com/109057362/198525156-47706327-50dc-4a29-98b1-515785a6e081.MOV

**Comment by trunghq17520184** [comment]
[0.5 units] Fix bug load artwork
