### ISSUE TITLE
There are some artwork cannot play in TV app Viewer

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1853]
Indexer tokenID: demo-tv-tez-KT1GbUx4MFBWHi3YhofDDvDYyeDeqahpKAGD-102702213695122363478566839164218757538779692010365371141592693954062874595531

![IMG_0607](https://user-images.githubusercontent.com/109057362/198529805-464e0903-82bf-4f66-b0f1-ada61f794cb8.jpg)

**Comment by trunghq17520184** [comment]
[0.5 units] Fix bug load artwork on TV
