### ISSUE TITLE
There are some artworks cannot play in Mobile app Android Redmi Note 11S

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1855]
- [ ] It is the same as the issue in TV app here for artwork Lizard king. Indexer tokenID: demo-tv-tez-KT1GbUx4MFBWHi3YhofDDvDYyeDeqahpKAGD-102702213695122363478566839164218757538779692010365371141592693954062874595531 https://github.com/bitmark-inc/autonomy-apps/issues/1853

- [ ] FACIAL cannot load the artwork, it just load the thumbnail preview in Preview screen. demo-tv-bmk--edc9a397185713bda753dc3e116c237938109f403f8cc5fe03dafec666f6dff5

- [ ] Each and Every Command, It cannot load and it make the Au app in Android is crashed out to Android Home screen when loading too much time. demo-tv-bmk--babf0e793c0e953f2f40ce2d279e6a6701b813f266780295caff4b5dba1d411d

**Comment by ritawu91** [comment]
> * [ ]  It is the same as the issue in TV app here for artwork Lizard king. Indexer tokenID: demo-tv-tez-KT1GbUx4MFBWHi3YhofDDvDYyeDeqahpKAGD-102702213695122363478566839164218757538779692010365371141592693954062874595531 [There are some artwork cannot play in TV app Viewer #1853](https://github.com/bitmark-inc/autonomy-apps/issues/1853)
@longbmk This is software, how do we update the artwork on the Tezos blockchain?

> * [ ]  FACIAL cannot load the artwork, it just load the thumbnail preview in Preview screen. demo-tv-bmk--edc9a397185713bda753dc3e116c237938109f403f8cc5fe03dafec666f6dff5
What is the requirement I need to tell the artists?

> * [ ]  Each and Every Command, It cannot load and it make the Au app in Android is crashed out to Android Home screen when loading too much time. demo-tv-bmk--babf0e793c0e953f2f40ce2d279e6a6701b813f266780295caff4b5dba1d411d
This is also the software
