### ISSUE TITLE
Missing Hide artworks icon for the Account although user set hidden artwork in this account setting

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1856]
Steps:
1. Import an account that has artworks
2. Navigate to Settings->account detail
3. Set on "Hide from collection" for this account
4. Move back to Settings page
5. Observe the Hide/Show icon

Observed result:
The account set hidden artwork collection still not display "hidden" icon

Expected result:
The account set hidden artwork collection display "hidden" icon
https://user-images.githubusercontent.com/109057362/198565971-9be46c8d-e42b-4e5f-8ec1-0e4adee6c813.MP4

**Comment by hungqd** [comment]
[0.25 units] fix bug
