### ISSUE TITLE
Star rating system never disappears after voting

### ISSUE THREAD

**Issue by moskovich** [bitmark-inc/autonomy-apps#1858]

**Comment by phuocbitmark** [comment]
I tested by my self and the bug seems to be gone. 
@hxw you fixed this, right?

**Comment by hxw** [comment]
I think it was due to missing the "star" labels on the production issues board so the GraphQL to set the rating+lable would just error.

**Comment by hxw** [comment]
- I was only able to get the rating to repeat by reopening the issue, then closing again
- there was a glitch in the app in that after the second rating the display would not scroll, and  I had to go back, then enter the issue again to see that there are now two ratings. But that is what I would expect.
- Also I did not see how to close an issue from the App or reopen it. These actions were done on github directly

**Comment by phuocbitmark** [comment]
@hxw you can not close an issue from the App, you can only reopen the issue by "Still experiencing the same problem?"
