### ISSUE TITLE
Sometime, estimate fee return error when confirming to send a token/coin in Au app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1871]
This is the log data: https://github.com/bitmark-inc/au-support-board/issues/677

These are the issues that user reported:
https://github.com/bitmark-inc/au-support-board/issues/674
https://github.com/bitmark-inc/autonomy-client/issues/384

I tried to swapt USDT XTZ and it returned fail.
![image](https://user-images.githubusercontent.com/109057362/199193551-b8c682c9-3154-4be8-b079-c48f7b951604.png)

**Comment by longbmk** [comment]
This issue is fixed.

**Comment by hvthhien** [comment]
[1 unit] investigate + fixing
