### ISSUE TITLE
Sometime, claimed success artwork does not display pending thumbnail in Au app after claiming

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1874]
These are logs files. Please kindly see the video for more detail.
[a907d394db3c12be813d0d9b096474cecadf595abd2479942874d40a9d343dea.txt](https://github.com/bitmark-inc/autonomy-apps/files/9917618/a907d394db3c12be813d0d9b096474cecadf595abd2479942874d40a9d343dea.txt)
[missing pending.txt](https://github.com/bitmark-inc/autonomy-apps/files/9917620/missing.pending.txt)

https://user-images.githubusercontent.com/109057362/199427344-32b2759c-6d66-4349-a58a-9d8f33408faa.MP4

**Comment by hungqd** [comment]
[0.25 units] Fix bug.

**Comment by longbmk** [comment]
This bug no longer happens. We deployed the hotfix for it.
