### ISSUE TITLE
Au app is not support multi-unique editions for artwork in FF so that some artwork will not display in Au app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1875]
![image](https://user-images.githubusercontent.com/109057362/199450931-3e95d6ed-9785-42ec-9e9b-85e7402b2c10.png)

Solution:
We should add param for previewUrl in Au app. List of param is here:
edition_index
blockchain
token_id
contract

**Comment by hungqd** [comment]
[0.25 units] Add parameters to FF's artwork preview url.

**Comment by longbmk** [comment]
[0.25 units] Check this bug in new minted TOTP in FF2 for both iOS and Android
