### ISSUE TITLE
User is not able to link AU to Metamask if Memamask open too long time over the timeout connection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1878]
User is not able to link AU to Metamask if Memamask open too long time over the timeout connection. We should increase the timeout to ensure when backing from Metamask still have link to Metamask wallet.

Steps:
1. Kill Metamask app
2. Open Au app
3. Link to Metamask wallet
4. Observe the Au app after baking to Au app

Observed result:
Missing connection to link account after clicking on Connect button in Metamask

Expected result:
Connection timeout should be increase to have Metamask connection
https://user-images.githubusercontent.com/109057362/199638659-80d406c9-ac2e-43b2-a270-ccfd67f3c93f.MP4

**Comment by longbmk** [comment]
@Anais-bitmark Can you please help to design a popup displays when we link to Metamask app. This popup should notify to user that: "If the external app needs loading time too long and the request connect is timeout, please re-connect again."

Thank you,

**Comment by Anais-bitmark** [comment]
@longbmk somehow I completely missed this one.
Is this still happening?

**Comment by longbmk** [comment]
@Anais-bitmark This issue still happens. It happens because metamask takes a long time to open so our request in AU is timeout. We discussed and have 2 solutions to improve UX here for users to retry. We prefer the 1 because this case sometimes happen, devices with high hardware will not load Metamask too slow.

1. We call Metamask and when back to AU, if the request time is greater than the config time (e.g. 30s) and the request is timeout, we show the popup for user: "Sorry, the request is timeout because it take too long time for connection. Please retry again". (Please provide the better message and UX in here @Anais-bitmark).
2. We show the popup to notify user the request sometime fail if Metamask load too long. After user click ok in the popup, we start to link to Metamask.

Please choose the solution and make a design for it @Anais-bitmark. (We prefer option 1 👯. Can you choose it because it will not affect the automation test)

Thank you @Anais-bitmark

**Comment by Anais-bitmark** [comment]
@longbmk @hvthhien 
UI is ready

I providing the versions with the old UI and new one.

[Figma](https://www.figma.com/file/MrsuaSQPLypKwvO34wqyrA/Au-bug_1878%3A-can't-to-link-AU-to-Metamask-if-Metamask-open-too-long-time-over-the-timeout-connection?node-id=0%3A1&t=0MhK5EnVBxsKG6PY-1)

`UI [0.1]`

<img width="788" alt="Capture d’écran 2023-01-09 à 12 05 16" src="https://user-images.githubusercontent.com/61187455/211304148-c5043fe4-3189-4bda-bdf9-7706266dbc6c.png">

**Comment by longbmk** [comment]
[0.1 unit] This issue no longer happens.

**Comment by hvthhien** [comment]
[0.5 units] Implement timeout popup.
