### ISSUE TITLE
Gray popup instead of confirm screen displays when Claim a domain in ENS domain

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1881]
Please connect to WalletConnect and Claim in this link:
https://app.ens.domains/name/anhbitmark.eth.test/details.

https://user-images.githubusercontent.com/109057362/199679334-4bf56cba-c156-4323-9b91-ce4bc8372939.MP4

**Comment by hvthhien** [comment]
[0.25 units] investigate + fix - prevent `null` amount in request
