### ISSUE TITLE
There is a redundant Pending NFT displays in AU app when having a swap token event

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1882]
1. Connect Au wallet to an exchange https://quipuswap.com/
2. Swap 2 tokens
3. Back to AU app

Observed result:
there is a pending item in Collections page.

Expected result:
The pending token should display just for NFT, should not apply for swap token.
![IMG_0630](https://user-images.githubusercontent.com/109057362/199686841-70ccf977-29ec-49df-9ab1-68581e5b5db1.PNG)

**Comment by hungqd** [comment]
[0.5 units] Fix bug
