### ISSUE TITLE
Missing Sign screen in Au app when user minimize app then clicking to buy an artwork in FF and relaunch Au app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1883]
Steps:
1. Connect Au to FF by WalletConnect
2. Minimize Au app
3. Click on Buy artwork in FF
4. Relaunch Au app
5. Wait for the confirm popup

Observed result:
1. Sign popup display but connection is lost when backing to previous page.

Expected result:
The Confirm/Sign popup should display when reopen Au app and connection should not lost

**Comment by hvthhien** [comment]
[0.5 units] add a mechanism to reconnect to disconnected sessions.
