### ISSUE TITLE
Indexer return edition = 0 instead of correct edition when user adds 2 multi-edition artworks indexID to Appcenter Au app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1886]
Please kindly use these addresses to check in staging.

{
    "ids": [
        "eth-0xdb5f1adcffa1869b9711cbfbe3bf46cc5d5319e5-92419109143972345096969611651362597777388673613154609693448331487805624917915",
        "eth-0xdb5f1adcffa1869b9711cbfbe3bf46cc5d5319e5-92419109143972345096969611651362597777388673613154609693448331487805624917936"
    ]
}
![image](https://user-images.githubusercontent.com/109057362/199910342-f707d563-35fc-478f-aae9-a47c640c7cda.png)

![image](https://user-images.githubusercontent.com/109057362/199909745-79710b8b-0ebe-411b-99d4-1e82fb17e447.png)

**Comment by lemonlatte** [comment]
This is query apparent come from staging. In staging the data is not push by FF so it would not correct.

**Comment by longbmk** [comment]
ok Let me close it. Thank you Jim
