### ISSUE TITLE
[Passcode] Passcode displays as OFF although it is ON

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#19]
**Steps to reproduce:**
1. Launch Autonomy App
2. Turn on Face ID
3. Go to setting on device 
4. Turn OFF FaceID on Autonomy app (Device setting)
5. Open Autonomy app
6. check FaceID/Passcode Setting status

**Observed result:**
- After step 5: Autonomy asks Passcode 
- Status Passcode setting if OFF

**Expected result:**
- Status Passcode setting if ON

**Information:**
Build: 0.27.4(44) (App Center) 
Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)

https://user-images.githubusercontent.com/42630760/165737138-85b95042-4ac9-4def-a789-0cc3f5a2622e.MP4

**Comment by hienphan1472** [comment]
This bug is still happened. Status of passcode is still OFF
![IMG_3719](https://user-images.githubusercontent.com/33851123/171121135-e194fa5b-adf8-4351-bd36-d27181fe9db1.PNG)

**Comment by thuyenBitmark** [comment]
@hienphan1472 Could you please check if you're testing on AppCenter or Testflight version?

**Comment by hienphan1472** [comment]
It's App Center version @thuyenBitmark

**Comment by thuyenBitmark** [comment]
@hienphan1472 Could you please give me the record?
I just tried in AppCenter and it worked.

**Comment by hienphan1472** [comment]
Here you go
https://user-images.githubusercontent.com/33851123/171122581-2ce1059a-d02d-4c88-b13b-6df920922e90.MP4
