### ISSUE TITLE
Application crash out to home screen when transfering edition 56 of the Calatog of Simulation artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1901]
Please kindly use my account to check the catalog art. I will provide you the seed to import
https://user-images.githubusercontent.com/109057362/201259099-0ae5f397-820c-4684-853a-1e805dc23ad2.MP4

The debug log is here.
https://github.com/bitmark-inc/au-support-board/issues/713

**Comment by hungqd** [comment]
[0.5 units] Investigate issue & fix bug

**Comment by longbmk** [comment]
This issue still happens when continuing confirm to transfer artwork.

**Comment by longbmk** [comment]
On behalf of @hungqd, this issue related to the keyboard we added to artwork preview from @trunghq17520184.
