### ISSUE TITLE
Artwork display in duplication when sending an artwork to another account that added to Au

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1903]
1. Import an account that has artwork
2. import a blank account
3. Transfer an artwork from account has artwork to blank account
4. Minimize Au app
5. Wait for some minutes to confirm blockchain
6. Open Au app and observe the Collections

Observed result:
There are 2 transferred artwork in Collections

Expected result:
The transferred artwork should not duplicated display in Collections
![1668140975186](https://user-images.githubusercontent.com/109057362/201263813-b91b01fe-1c76-449b-9cce-8f2dd432a128.JPEG)

**Comment by hvthhien** [comment]
[0.5 units] investigate + updates to remove unowned tokens by every address.
