### ISSUE TITLE
Missing the push notification to notify user has a transaction need to sign when the Au app is in minimize status

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1908]
1. Make sure we have a connection from any exchange to Au app (E.g. FF)
2. Minimize Au app
3. Send a request to transfer/buy an artwork
4. Observe the Au app

Observed result:
Nothing happens in Au app. User don't know any request to sign from Au app

Expected result: 
- [ ] Au app should have a notification to show the user has a new transaction that needs to sign.
- [ ] Au app will not send the push notification if the Au app is in active status.

**Comment by hvthhien** [comment]
It's not easy and will need a feature to do this. This is the expected flow for now so I'm gonna close this issue.
