### ISSUE TITLE
Collection is not refreshed when throwing down the collection in AU app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1925]
We are missing the function to refresh the Collection when throwing down the collection. We should implement it because most users are familiar with this behavior but we are missing it.

**Comment by ppupha** [comment]
[0.5 unit] refresh when pull down

**Comment by longbmk** [comment]
[Bug] It still has problem in case we have 1 artwort and the collection list is too short. So that it does not show the scrollview to pull down to update
