### ISSUE TITLE
Confirm button of Claim flow displays too low at the bottom of screen. It should be consistent with another screen.

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1943]
![image](https://user-images.githubusercontent.com/109057362/204959412-1b5904c0-1766-426e-9a84-34ab8fd0e63a.png)

**Comment by ppupha** [comment]
|Before|After|Another Screen|
|---|---|---|
|![image](https://user-images.githubusercontent.com/47568867/204967723-2cc715f6-07e7-43b8-9b0f-4beee6b0bead.png) {///////////////////////////}|![image](https://user-images.githubusercontent.com/47568867/204967844-8eacc532-1fe2-45eb-b094-2709be8d2d11.png) {///////////////////////////}|![image](https://user-images.githubusercontent.com/47568867/204968363-05240a98-d698-4e77-b608-ca3bfd5757f0.png) {///////////////////////////}|

@Anais-bitmark UI updated

**Comment by longbmk** [comment]
This issue is fixed

**Comment by ppupha** [comment]
[0.25 units] Update claim button position to the same as another buttons
