### ISSUE TITLE
Import screen display "iCloud keychain" instead of "Android Block Store" when navigating to this screen in Android phone

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1944]
It should display "Android Block Store" for Android and "iCloud Keychain" for iOS when navigating to Import screen.

![image](https://user-images.githubusercontent.com/109057362/204960348-52a3e0f4-3b20-4f52-8d92-d6d24613e657.png)

**Comment by phuocbitmark** [comment]
[0.25 units] fix text, add github link
