### ISSUE TITLE
Restore screen still displays after user finished the Wallet/Beacon connect at onboarding

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1947]
https://user-images.githubusercontent.com/109057362/205025464-789991a9-61ff-4e3e-a2f5-65d0143d4715.mp4

**Comment by phuocbitmark** [comment]
[0.5 units] auto restore if handle deeplink, branchlink while onboarding

**Comment by longbmk** [comment]
This bug is fixed
