### ISSUE TITLE
Ethereum artwork does not disappear immediately when user sends it to another address

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1948]
1. Send the Ethereum artwork to another address
2. Observe the collection page

Observed result:
The ethereum artwork still displays in collection. It disappears after 15 minutes when indexer confirmed.

Expected result:
The app should update to hide both Tezos artwork and Ethereum artwork when it is sent to another address.

Note: Please kindly double check again for Tezos artwork.
![IMG_0679](https://user-images.githubusercontent.com/109057362/205039840-ac42326e-4562-43d2-80fc-f9db1d12012a.jpg)

**Comment by phuocbitmark** [comment]
[0.25 units] hide ethereum token after sent it

**Comment by longbmk** [comment]
This issue no longer happens
