### ISSUE TITLE
There is a duplicated Autonomy icon displays in WalletConnect popup when user try to connect Au app to any dapps by WalletConnect

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1956]
![image](https://user-images.githubusercontent.com/109057362/205217639-4a07d655-f1ea-4be9-a8ca-ed4e39746367.png)

**Comment by anhnguyenbitmark** [comment]
Related: https://github.com/WalletConnect/walletconnect-monorepo/issues/1774

**Comment by moskovich** [comment]
@longbmk is this still a bug?

**Comment by longbmk** [comment]
It is fixed when upgrading to WC2.0. Let me close it.
