### ISSUE TITLE
Missing Ethereum artworks in Discovery function

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1965]
1. Add an account that has Ethereum artwork
2. Wait for Discovery sync
3. Open Discovery
4. Observer list of artwork in Discovery

Observed result:
Missing Ethereum artworks.

Expected result:
Ethereum artwork should be applied for Discovery

**Comment by hxw** [comment]
This needs a fix in Au to follow Ethereum addresses. As far as I could tell Au is only sending Bitmark addresses to follows, it must send ETH (and TEZ)  as well.

---
Not sure if related: if a discovery feed contains a "_nft currentlyindexing…_" item the discovery page will freeze, swiping not working, NFT info not working, only **X** works to exit back to the collection page. However just wait 90 seconds discovery will continue and show more items.
I will search the DB to find this failed NFT, the try to force a reindex to see if that helps

**Comment by longbmk** [comment]
@hxw It has already been fixed and deployed the new app. Please kindly try it. Thank you so much

**Comment by hxw** [comment]
[3 units] rewrite of the discovery service indexing process

- no longer storing pending events in the DB
- ignore any event whose address is not followed
- put all incoming "followed" invents to Redis queue
- multiple workers to dequeue events and run index workflow
    - throw away failures
    - store only successes
- fix bug in background Ethereum fetch that would add events as if already indexed, now just send to Redis (this is process to add events for "new users" when they add their first Eth NFT)
- remove all failed events from DB (gradually remove 100k per day about 15% complete as of this issue
