### ISSUE TITLE
iOS only - Beacon wallet connect is not success when user connect wallet at the Restore sreen in Onboarding

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1974]
1. User is on Restore - onboarding screen
2. Use the Camera app/QR code app to scan the Beacon connects in Objkt
3. Select the account an connect

Observed result:
The website does not finish the connection. Missing the Sign step in Au app

Expected result:
The connection should be success contains Sign screen

Note:
In case Start screen, it still work ok in both Android and iOS
In case Restore screen, it still work ok in Android but failed in iOS

**Comment by hvthhien** [comment]
[0.5 units] investigate & fix the issue beacon connect got reset after onboarding.

**Comment by longbmk** [comment]
This issue no longer happens.
