### ISSUE TITLE
Red dot does not disappear when user enable the Notification setting

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1977]
Please kindly update to disappear the red dot when user enables the Notification setting.
![image](https://user-images.githubusercontent.com/109057362/206347947-85447dd9-499b-4411-b449-b32705dcfa09.png)

**Comment by ppupha** [comment]
[0.25 units] hide red note if enable notifications

**Comment by longbmk** [comment]
New UI will not show the red dot. This bug no longer happens
