### ISSUE TITLE
Missing Pending NFT in Collections when purchasing an Ethereum NFT in Feralfile

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1978]
1. Connect Ethereum Wallet to FF
2. Purchase an Ethereum NFT in FF
3. Observe the Collections page

Observed result:
Missing the Pending purchasing NFT

Expected result:
Pending purchasing NFT should display in the Collections

**Comment by anhnguyenbitmark** [comment]
We do not support pending state for purchases on Feral File.
