### ISSUE TITLE
Collection instead of "Discovery Artwork Info" page displays when closing the Discovery Artwork preview 

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1979]
Steps:
1. Import an account that has Discovery event
2. Open an artwork in Discovery
3. Click on artwork title to view Artwork Info
4. Click on the thumbnail to view Artwork preview
5. Click on X icon to close the artwork preview
6. Observer the return page

Observed result:
Collection page displays

Expected result:
Artwork Info page displays.

https://user-images.githubusercontent.com/109057362/206381124-134abe46-eea2-418b-bbe3-b5b2c5c2f1b8.mp4

**Comment by ppupha** [comment]
@longbmk the flow is right, it should be back to Collection Page. When click on artwork thumbnail, it goes back to Discovery, not Artwork Preview.
