### ISSUE TITLE
There are inconsistency between Edition number in Artwork info page and in Transfer Artwork page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1980]
Compare the Edition number in Artwork Info page and Transfer Artwork page.

Expected:
The Edition should load edition name with format #xxx for both Artwork Infor and Transfer Artwork.

![image](https://user-images.githubusercontent.com/109057362/206384933-b6ec7741-61aa-45a8-af71-9152d17dba11.png)

![image](https://user-images.githubusercontent.com/109057362/206384918-e101f1fa-a169-4e32-bb5c-23e696afaf2d.png)

**Comment by phuocbitmark** [comment]
@longbmk do we have /maxEdition after editionName

**Comment by phuocbitmark** [comment]
[0.25 units] fix edition
