### ISSUE TITLE
Splash screen displays in landscape mode at the first opening AU app if the screen is in landscape status

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1985]
1. Make the phone to Lanscape 
2. Open Autonomy app
3. Observe the Splash screen

Observed result:
Logo open in landscape then turn back to portrait

Expected result:
- [ ] Splash screen should always display in Portrait mode and then disable it after loading Splash screen.
- [ ] Artwork preview still support landscape mode

**Comment by hvthhien** [comment]
[0.25 units] lock orientation for splash screen.
