### ISSUE TITLE
Artwork thumbnail still displays SVG instead of converting to PNG in server then using for the application

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1996]
https://opensea.io/assets/ethereum/0xdda32aabbbb6c44efc567bac5f7c35f185338456/18

Please double check by this artwork. 

Thanks @PhucDuongBitmark

**Comment by PhucDuongBitmark** [comment]
[1 units]
- change svg log error

**Comment by longbmk** [comment]
[0.25 unit] Check and discuss to fix it
