### ISSUE TITLE
[Notification] The notification settings shouldn't be prompt after users click on "Not Now" option 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#20]
You can change your notification settings at any time from the Settings app, so even if users click on "Not Now" option, the The notification settings shouldn't be prompt after that

**Steps to reproduces:**
1. Launch app at the 1st time
2. Tap "Not now" btn on Notification Settings
3. Close app
4. Re-launch app
5. Notice that the notification setting displays or not

**Observed result:**
The notification settings still displays

Information:
Build: 0.27.4(44) (App Center) 
Device:
Ip13 pro max OS (15.3)
https://user-images.githubusercontent.com/42630760/165740801-ca3c2385-bf86-463c-8a69-39dd09bc8f08.MP4

**Comment by NekhDRej** [comment]
The task is done

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10
