### ISSUE TITLE
[Enhancement] Missing validation message for invalid recovery phrase when user imports the seeds

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2009]
1. Navigate to Import screen
2. Enter the invalid seed
3. Observe the Recovery seeds textbox

Observed result:
The textbox is highlight but missing the validation message.

Expected result:
The textbox is highlight and show the validation message.

Please kindly help us design for it @Anais-bitmark. Thank you
https://github.com/bitmark-inc/au-support-board/issues/935

**Comment by Anais-bitmark** [comment]
@ppupha 
Please find missing UI here.

[Figma](https://www.figma.com/file/UtB7IuFLpj44vUyYYpbvT4/Au-Enhance_2009%3A--Missing-validation-message-for-invalid-recovery-phrase-when-user-imports-the-seeds?node-id=0%3A1&t=bpnFm5uEXihTxoHp-1)

<img width="1498" alt="Capture d’écran 2022-12-20 à 15 22 13" src="https://user-images.githubusercontent.com/61187455/208702245-a52397ee-2f3b-4a0b-ac80-4f76a8e92ff9.png">
