### ISSUE TITLE
The "Report a Bug" function cannot send the next report messages after reporting a photo then send others message

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#201]
This issue happens in both iOS and Android app in build 0.30.1(64) 
Steps:
1. Open Autonomy app.
2. Open the "Report a Bug" function
3. Send a photo to Report
4. Send log or another message to report bug

Observed result:
Message cannot deliver to report system. The spinner spins never end

Observed result:
The next report message should be send success after user send a photo report
https://user-images.githubusercontent.com/109057362/178455016-cc82fd19-d6ce-413e-b78e-ee113d4dbce9.MOV

https://github.com/bitmark-inc/au-support-board-test/issues/422

**Comment by NekhDRej** [comment]
The bug is fixed. 

Environment:
iOS build (App center): 0.31.1 (75)
iPhone 12\iOS 15.5
Android build (App center): 0.31.1 (70)
Redmi 8A\Android 10

https://user-images.githubusercontent.com/101094775/181216286-5131c049-6c07-43b4-8dcb-b81cc7a7d345.mp4
