### ISSUE TITLE
Problem transferring funds to another wallet

### ISSUE THREAD

**Issue by caseyalt** [bitmark-inc/autonomy-apps#2013]
https://github.com/bitmark-inc/au-support-board/issues/952

**Comment by caseyalt** [comment]
The user said this send to have resolved itself, but we should figure out what caused the original issue.

> The issue resolved itself somehow, but I wasn't able to do any transactions from wallet to wallet within Autonomy. I finally was able to get a transaction through to my AirGap wallet from Autonomy, but all of my funds were frozen the entire day...

**Comment by anhnguyenbitmark** [comment]
It is fixed.
