### ISSUE TITLE
Missing "Collected by" info for Discover function in new UI

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2042]
Please kindly help us to design it @Anais-bitmark. Thank you
![image](https://user-images.githubusercontent.com/109057362/210160442-c879faee-33ba-4043-b5bd-35fe5aa39d8c.png)

**Comment by Anais-bitmark** [comment]
@longbmk  UI is ready

UI: `[0.25 unit]`

[Figma](https://www.figma.com/file/zWpvxZq1hQylmRJ0oB3cqk/Au-bug_2042%3A-Missing-%22Collected-by%22-info-for-Discover-function-in-new-UI?node-id=0%3A1&t=6CbDtizCsFHbmiKk-1)

<img width="984" alt="Capture d’écran 2023-01-06 à 11 47 41" src="https://user-images.githubusercontent.com/61187455/211006596-69007ed1-6e2a-4ff5-a122-672c5a02b920.png">

**Comment by longbmk** [comment]
Thank @Anais-bitmark

**Comment by ppupha** [comment]
[0.25 units] add Collected by

**Comment by ppupha** [comment]
[0.25 units] refactor and fix click on collector name

**Comment by longbmk** [comment]
This issue no longer happens.

**Comment by Anais-bitmark** [comment]
@ppupha 
The font and color are not correct here for the date.
It should be PP Mori in 12px in grey #A0A0A0

Could you fix it?

![Image](https://user-images.githubusercontent.com/61187455/215783020-1745790a-f21b-4a31-9d8b-e389582de38e.jpeg)



![Image](https://user-images.githubusercontent.com/61187455/215783825-c81b05f1-d17b-4347-ad13-b6edaeae6266.png)
