### ISSUE TITLE
Missing Rights section for some artwork if we creat the artwork without the migration

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2043]
- [ ] We need to create the migration or load the correct exhibitionID after migrating.
![image](https://user-images.githubusercontent.com/109057362/210160532-62bf9485-09a3-4ae4-8857-5afccf53d82c.png)

**Comment by phuocbitmark** [comment]
[0.5 units] update models, migrate, get edition id from originTokenInfo

**Comment by longbmk** [comment]
Can you please help to check it in your side @Anais-bitmark? Thank you

**Comment by Anais-bitmark** [comment]
@longbmk 
The rights section is back but it always takes 1 second to load, compared to metadata and provenance that are visible right away.

**Comment by phuocbitmark** [comment]
@Anais-bitmark i understand that problem, but fixing that takes time. I will get back to you about this matter later

**Comment by JasonLiuBitmark** [comment]
https://github.com/bitmark-inc/au-support-board/issues/965

**Comment by phuocbitmark** [comment]
@Anais-bitmark unfortunately, we can not fix that, it takes several step to load the rights section, it can not be as quick as provenance or metadatda

**Comment by JasonLiuBitmark** [comment]
@phuocbitmark , is it ok to close the support ticket now?

**Comment by phuocbitmark** [comment]
@JasonLiuBitmark yes, please.
