### ISSUE TITLE
There are some displayed issues for new UI

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2045]
- [ ] On discovery, there is a weird underline on the NFT RENDERING button.
![image](https://user-images.githubusercontent.com/109057362/210191320-c5f78298-f1c7-4dbf-a74a-9f04b735782c.png)

- [ ] When viewing artwork (after tapping on preview in artwork details) the artwork title in header should be 14px not 12px.
![image](https://user-images.githubusercontent.com/109057362/210191357-61426bb2-167d-42fe-af67-4153947d49e3.png)

- [ ] For fungible tokens that don’t have an edition number, can we bring up the description so we don’t end up with a gap here.
![image](https://user-images.githubusercontent.com/109057362/210191375-b9cf5c08-5746-4411-a2ce-7d73f182205e.png)

- [ ] In Discovery some artworks are displayed with a white background once you open the artwork details while it seems to be displayed correctly in the discovery feed.
![image](https://user-images.githubusercontent.com/109057362/210191401-143d57ee-b268-41eb-a244-84b95be33ce0.png)

- [ ] Legend in editorial should be in grey. See my comment on GitHub story
![image](https://user-images.githubusercontent.com/109057362/210191407-2a41579c-d286-4847-8bc8-a8a4be7fc4a0.png)

- [ ] This header should have a question mark at the end.
![image](https://user-images.githubusercontent.com/109057362/210191628-c9774cc4-c3ff-4277-8322-161f4f41a571.png)

**Comment by ppupha** [comment]
@longbmk this issue was fixed in prep time

**Comment by ppupha** [comment]
[0.25 units] fix UI
