### ISSUE TITLE
There are inconsistency about currency decimal number in Au and FF

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2068]
There are inconsistency about currency decimal number in Au and FF. We need to make them consistency. FF is using ETH in 8 digits, and USDC/ XTZ in 2 digits.

**Comment by Anais-bitmark** [comment]
@ppupha 
on Autonomy when selecting gas fees for example, the difference is so small between low - medium and high that you see the difference only at the third or fourth decimal.
FF maybe doesn't have this need.
But when I look into other wallets thery also display even 6 digits for XTZ and 8 for ETH.

![IMG_2678](https://user-images.githubusercontent.com/61187455/211007423-f6ab9611-d7ab-4a75-bc25-08f9d023b597.jpeg)

**Comment by ppupha** [comment]
@Anais-bitmark  if in FF use 8 digits, i suggest in Au use 8 digits too, for both ETH and XTZ (also in Max)

**Comment by anhnguyenbitmark** [comment]
@longbmk @ppupha @Anais-bitmark I asked Sean about this before. Let's use this rule:
- Fiat: 2 significant figures.
- Cryptocurrency: 4 significant figures.

**Comment by longbmk** [comment]
Ok @anhnguyenbitmark,

We will apply 4 digits after @Anais-bitmark has a design for it.

**Comment by hvthhien** [comment]
@anhnguyenbitmark 
> Cryptocurrency: 4 significant figures.

This I think it would not enough for user, especially for Ethereum. (Other apps I see are using up to 8 digits).

**Comment by hvthhien** [comment]
Additionally, other apps don't limit much the digits when show the fee (because these amounts are small and cannot show the difference when rounding them).

**Comment by Anais-bitmark** [comment]
@anhnguyenbitmark 
For cryptocurrencies
So common practice is in between 6 and 8 digits. 
in Au we are using 6 digits
and now suggestion would be 4 digits.

I still think 4 digits is too short to display gas fee differences


As references 

- Metamask uses 5 digits for ETH
- Zen Go uses 8 digits for ETH
- Rainbow uses 6 digits for ETH

- Temple uses 6 digits for XTZ
- Zen Go uses 6 digits for XTZ

Is there a reason to display only 4 digits?

**Comment by anhnguyenbitmark** [comment]
5 or 6 doesn't affect much to the calculation or storage. I'm open to that. Let's raise again to @moskovich.

**Comment by Anais-bitmark** [comment]
@moskovich 
Are you okay to use 5 or 6 significant figures for cryptocurrencies?
4 is too little to display the difference between gas fees.

**Comment by moskovich** [comment]
Sure. Use what is necessary.

**Comment by Anais-bitmark** [comment]
The rules that we will apply for Autonomy:

> - FIAT:  2 significant figures 
> - Cryptocurrencies:  6 significant figures 

[Figma](https://www.figma.com/file/6txtsnKW2gFh3hbxr9SqDp/Au-bug_2068%3A-There-are-inconsistency-about-currency-decimal-number-in-Au-and-FF?node-id=0%3A1&t=V6bpqtQ3HWJifuwI-1)

@longbmk can we push this info to Feral File to update in consequence? 
@stedemar for the update, we want to make digits consistent between Au and FF when it comes to currency decimal numbers.  The rule above is what would work for Autonomy. 
Could you apply it to FF?

According to Anh, displaying 8 digits for crypto requires too much computing power and more storage, but up to 5 or 6 significant figures, it would be easier to handle.


![Image](https://user-images.githubusercontent.com/61187455/213017998-bf9a4bbe-89bb-44e7-aaa5-2836ca8a55b8.png)

**Comment by stedemar** [comment]
Hei @Anais-bitmark sounds good

**Comment by ppupha** [comment]
[0.25 units] fix currency decimal number

**Comment by ppupha** [comment]
Ready to test @longbmk

**Comment by longbmk** [comment]
We applied 6 digits for Autonomy. Just need FF to update the digits to make the consistent
