### ISSUE TITLE
Sometimes, production app (0.36.3) crashed when viewing an artwork info

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2069]
https://github.com/bitmark-inc/au-support-board/issues/1005
[longbmk_appcrash_when_opening_artworkFF.txt](https://github.com/bitmark-inc/autonomy-apps/files/10334360/longbmk_appcrash_when_opening_artworkFF.txt)

**Comment by hvthhien** [comment]
this is potential caused by the memory issue, which is handled in [#2076](https://github.com/bitmark-inc/autonomy-apps/issues/2076), @longbmk kindly need your help to check it again.

**Comment by longbmk** [comment]
@hvthhien The application is better, but this issue still happens in the latest build. I think we still need to investigate more. Tested in iPhone xsmax.

**Comment by anhnguyenbitmark** [comment]
Will check again after cycle 026.
