### ISSUE TITLE
There are so many artwork thumbnails display in black circle when importing some addresses has many artworks

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2070]
They always return the same thumbnail: https://gateway.test.autonomy.io/ipfs/QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc

Please use these addresses to check.
Addresses: 
0xef63682430CE126B0DB33Bb0F74161B4604580bA 
tz1YzPosgwSCShxBJy6BVuR3QtRXyt5cP2WR
tz1YokFzMR1hX4m4aBqgutxLSUKFDdNoYGEN

![IMG_0708](https://user-images.githubusercontent.com/109057362/210309396-acf30a5a-4363-429a-81e9-c0a1d049bb26.PNG)

**Comment by PhucDuongBitmark** [comment]
indexID: tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-76777

**Comment by PhucDuongBitmark** [comment]
[1 units]
Replace black circle image by Objkt CDN URL
