### ISSUE TITLE
AU is crashed out to OS home page when loading Discovery that has some heavy artworks

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2076]
Please use these addresses to check in Discovery.
Addresses:
0xef63682430CE126B0DB33Bb0F74161B4604580bA
tz1YzPosgwSCShxBJy6BVuR3QtRXyt5cP2WR
tz1YokFzMR1hX4m4aBqgutxLSUKFDdNoYGEN

**Comment by hvthhien** [comment]
Proposal solutions:
- [ ] Update libraries to the latest version and re-test (videoplayer, webview, pdfview).
- [ ] Prevent autoplay for videos have size too large (maybe >200MB).
- [ ] Downloader server limit number of file downloading concurrently.

**Comment by hvthhien** [comment]
[1 unit] analyze, update libraries & update downloader service.

**Comment by longbmk** [comment]
@hvthhien As my comment in #2069 The application is better, but this issue still happens in the latest build. I think we still need to investigate more. Tested in iPhone xsmax.

https://drive.google.com/file/d/1CSaShMllF6SEZOGthTP7cSZ80RxAPtkx/view?usp=share_link

**Comment by Anais-bitmark** [comment]
@longbmk 
What do we need from me here?

**Comment by Anais-bitmark** [comment]
@hvthhien 
Same here, can we just load a static thumbnail of the artwork until we are able to load and auto-play the artwork (once resized by the server)?

**Comment by anhnguyenbitmark** [comment]
@Anais-bitmark actually, even we won't play the NFTs lively in the feed, it still crashes. That's because the artwork itself. Some requires a lot of rendering power, takes up from application's allocated resource. 
Can we only show the thumbnail in the feed and let the user tap into the detail to play the actual artwork? What I observed is, my phone got warmer when browsing the Discovery feed.

**Comment by Anais-bitmark** [comment]
@anhnguyenbitmark 
So let's apply what you are saying, better if we don't have to add in extra UI.

Maybe next cycle we could improve the discover feed. If we don't auto-play artwork within the feed we could have a small tag on the thumbnail to indicate which type of artwork it is. So user will more likely open it to play the video or software.
