### ISSUE TITLE
There are some artworks are missing Artist address in Artwork infor page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2084]
Please use these address to debug:
tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-657632
tez-KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW-31448
tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-28713
tez-KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW-31453
tez-KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW-30885
tez-KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW-23159

![image](https://user-images.githubusercontent.com/109057362/210701924-1d2e6b2c-2b44-401b-9ba4-2d0757d83f42.png)
![image](https://user-images.githubusercontent.com/109057362/210701935-ed280c81-067a-4f8c-9e71-20172b5ed82e.png)

**Comment by PhucDuongBitmark** [comment]
[0.5 units]
fix this bug bu replace artist name by artist address if not have name

**Comment by longbmk** [comment]
Indexer still not update to show artist name after indexing address/tokenID

![Image](https://user-images.githubusercontent.com/109057362/211261122-e0547ead-f3cf-4f41-ab09-43314dc63f78.png)

**Comment by longbmk** [comment]
@PhucDuongBitmark can you please help to check it? It still happens. Thank you

**Comment by longbmk** [comment]
@PhucDuongBitmark This issue still happens with this IndexID tez-KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW-30878. Please kindly help to check it. Thank you.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/109057362/218956998-1f740af1-6173-4924-8630-343f5fe0984b.png">

**Comment by PhucDuongBitmark** [comment]
@longbmk this is because we not call index api before check, please re-check and approve this ticket

**Comment by longbmk** [comment]
I have updated this bug to 1 point because @PhucDuongBitmark will do the migration for all existing token. I take time, so this ticket is re-estimated.

**Comment by longbmk** [comment]
Phuc Duong has support to update the address, we are still not doing the migration, so I change back the estimation to 0.5. 
This issue no longer happens.
