### ISSUE TITLE
There is a specific address has 7 tokens in indexer but it just displays 6 in AU app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2102]
Please see the log in this ticket
https://github.com/bitmark-inc/au-support-board/issues/1006

**Comment by hvthhien** [comment]
from indexer, it returns 6 tokens: 
https://indexer.autonomy.io/v1/nft?owner=b7q69aj96SMD8JiRawTD45BD3xr9LnC6fiGje3BSkKpKiJ9yVn&offset=0&size=50

**Comment by longbmk** [comment]
For now, the indexer returned 7 tokens after some fix. So I think we can close it. https://indexer.autonomy.io/v1/nft?owner=b7q69aj96SMD8JiRawTD45BD3xr9LnC6fiGje3BSkKpKiJ9yVn

<img width="954" alt="image" src="https://user-images.githubusercontent.com/109057362/212796656-3c443ee6-2629-430a-98b9-f24f9f97828f.png">

**Comment by minhkstn** [comment]
[0.5 units] find cause
