### ISSUE TITLE
Application crashes when loading Discover with a big collection or a very big video/artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2103]
Please use these address to reproduce:
Addresses:
0xef63682430CE126B0DB33Bb0F74161B4604580bA
tz1YzPosgwSCShxBJy6BVuR3QtRXyt5cP2WR
tz1YokFzMR1hX4m4aBqgutxLSUKFDdNoYGEN

bitmark archive:
tz1NaAvMy9WNnPynVXbn1sgMS2MkVNfBHo7Z
0xBEb9F810862c40A144925f568b1853d72Acc492F

Steps:
1. Import addresses.
2. Wait for the Collection/Discover load
3. Scroll down Collections/Discover to load artworks

Observed result:
Application is crashed out to OS screen

Expected result:
Application is not crashed. Or we should define more UX to handle this if we cannot handle the big video/artwork in technical.

https://user-images.githubusercontent.com/109057362/211272187-dd719dd0-b1b9-4267-a706-1666763a3882.MP4

https://github.com/bitmark-inc/autonomy-apps/issues/2071
https://github.com/bitmark-inc/autonomy-apps/issues/2076

Customer support ticket:
https://github.com/bitmark-inc/au-support-board/issues/980

**Comment by Anais-bitmark** [comment]
@longbmk 
How you need UI here?
I maybe don't understand completely, but can we not handle the app to not crash instead of adding a message?

**Comment by Anais-bitmark** [comment]
@hvthhien Can we just use a static thumbnail, until we are able to load the original thumbnail and auto-play it?

**Comment by hvthhien** [comment]
@Anais-bitmark We've already implemented your idea, even with the delay time is longer (1s).

**Comment by longbmk** [comment]
This issue no longer happens when using the big collection. I think we can close this ticket. The application loading still need to improve more, but we can do it in the future. If this bug happens again, I will reopen it. Thank you
