### ISSUE TITLE
There is specific case AU doesn't fetch Tez address of a Bitmark linked account from indexer, so user is missing some artworks in Collection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2112]
This is the support ticket. https://github.com/bitmark-inc/au-support-board/issues/1026
This is the QR code to check account:
https://drive.google.com/file/d/1o0qBnuVAemF_9tnZosj-UwWHgw6IzEFs/view?usp=share_link

Please use this debug log to check.
https://raw.githubusercontent.com/bitmark-inc/au-support-board/main/attachments/did%3Akey%3AzQ3shR82uVzFRUCV6GmwePTMbMGiqKN59dcym3sCxTvDJPDLk/ef7e4f84b134da587d675fed509a4c23f8ad5ec8d1751ca1f4ad80ed49d2fac8.text?token=GHSAT0AAAAAAB2PSS62AH2L3ZCCG7S2GG56Y56ICFQ

Sean's view in this account:
![image](https://user-images.githubusercontent.com/109057362/211716903-560d269b-eed2-49ae-8dc7-9b048811000f.png)
Red26 view in this account:
![image](https://user-images.githubusercontent.com/109057362/211717002-fff9651a-d889-4860-b792-0c663f1fb99f.png)

**Comment by hvthhien** [comment]
[0.5 units] Investigate + debug

**Comment by longbmk** [comment]
This issue just happens in the user's device. I think we need to wait for this user's feedback. The production indexer has been deployed.

**Comment by longbmk** [comment]
On behalf of Sean, he asked the user, this issue still happens. It is still missing this art https://feralfile.com/artworks/4ac90d22-2b94-4dad-8685-3df950746010

**Comment by anhnguyenbitmark** [comment]
Will check again after cycle 026.
