### ISSUE TITLE
Max amount does not update when user changes Fee priority to higher so that the transaction will be failed

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2119]
Steps:
1. Navigate to send ETH/Tezos screen
2. Enter the target address
3. Select max amount
4. Change Fee priority to a higher
5. Process the transaction

Observed result:
Transaction is failed.

Expected result:
- [ ] The amount should be recalculate when user change the Fee priority to higher to have transaction successful
- [ ] The amount should be recalculate when user change the Fee priority to lower to have transaction successful
https://user-images.githubusercontent.com/109057362/212021099-aea842fe-c87a-4010-a67c-a80b9672d812.MP4

**Comment by phuocbitmark** [comment]
[0.25 units] update state after changing fee option

**Comment by longbmk** [comment]
[Bug] @phuocbitmark this issue still happens. The amount still retain when changing the Fee priority. Please kindly follow the expected result of bug to fix it in root cause.

https://user-images.githubusercontent.com/109057362/212957525-b121dda1-f726-4637-a564-b0a6f895a329.MP4

**Comment by phuocbitmark** [comment]
@longbmk i don't we should change what users type in any case, user would not always notice that, so it will cause mistaken action. in this case, if we change the amount, users might sometime send the wrong amount compare to what they want to. we already have the feature to enter the max amount, so we shouldn't change the amount if it not enough, just notifying user is sufficient

**Comment by longbmk** [comment]
Ok. If we change amount, it will not be a good permission. Current is ok. Let me close this bug.
