### ISSUE TITLE
User is unable to scan QR code at second time if do not accept permission for Camera when using scanning QR code

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2121]
Steps:
1. Open AU app
2. Open QR code feature
3. Click on "Don't allow" button
4. Close Scan QR screen
5. Re-open QR code screen

Observed result:
The white blank QR screen displays

Expected result:
UX should have a message and button to notify the user open Settings app to set allowing Camera permission.

**Comment by Anais-bitmark** [comment]
@ppupha 
UI is ready
[0.25 unit] UI

[Figma](https://www.figma.com/file/tuqLQaKbK2QomaWEnH2jmD/Au-bug_2121%3A-User-is-unable-to-scan-QR-code-at-second-time-%5B...%5D-when-using-scanning-QR-code?node-id=0%3A1&t=jLGFtFCbK6QxHatk-1)

<img width="1042" alt="Capture d’écran 2023-01-17 à 22 00 21" src="https://user-images.githubusercontent.com/61187455/213021780-0054f579-2b50-4e60-839d-d1f6cb08095c.png">

**Comment by ppupha** [comment]
@Anais-bitmark please read comment in figma
![f7bbc7ee-495a-4d6f-bea1-7018d003d17f](https://user-images.githubusercontent.com/47568867/215432142-985f9d19-42b4-4665-99ce-a2084a1a51c6.jpeg)

**Comment by ppupha** [comment]
[0.5 units] apply UI

**Comment by Anais-bitmark** [comment]
@ppupha it works the way you applied it.

**Comment by ppupha** [comment]
Ready to test @longbmk

**Comment by longbmk** [comment]
This bug still happens in iOS. Please double check and fix it @ppupha 
![Image](https://user-images.githubusercontent.com/109057362/216363400-23dd9808-dabf-4659-a218-3197612da8de.jpeg)

**Comment by ppupha** [comment]
Issue on iOS was fixed @longbmk please test again.
