### ISSUE TITLE
Proceed button in "Conflict detect" screen displays too low. It should move to higher as design

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2122]
![IMG_0723](https://user-images.githubusercontent.com/109057362/212053831-df1db728-d266-4285-9862-7c10f825d82c.PNG)

**Comment by ppupha** [comment]
[0.1 units]
- [x] Fixed Proceed Button Position
![dfde2da6-a727-46a8-ae5b-7d9e18d88f0e](https://user-images.githubusercontent.com/47568867/212232941-03470663-598f-4e6e-9d89-5a12107c8301.jpeg)

- [x] Fixed Send Button Position
![524d5468-da00-43dd-aa69-341b44b7ab32](https://user-images.githubusercontent.com/47568867/212232916-83c0fdec-d0b0-462f-b781-ff941ed15a35.jpeg)

**Comment by ppupha** [comment]
@longbmk the bugs was fixed and ready to test

**Comment by longbmk** [comment]
This issue no longer happens
