### ISSUE TITLE
Missing notification to user when the supporter reply to support ticket of user

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2130]
Steps:
1. Report a bug
2. Navigate to Collection screen
3. Supporter reply a message to support ticket
4. Observe the application

Observed result:
There is no notification when supporter reply ticket

Expected result:
There should be a notification to user when supporter reply the support ticket

**Comment by ppupha** [comment]
This issue happened because app doesn't receive any notification from server. Please help to check @hvthhien.

**Comment by ppupha** [comment]
I think it happens because that user denied notification permission on his phone (the same as camera permission), @Anais-bitmark please design UI for this case.

**Comment by ppupha** [comment]
@Anais-bitmark remider

**Comment by anhnguyenbitmark** [comment]
Two cases after discussing with @longbmk and @ppupha 
1. If the notification got denied by OS, it would not get through to the app. We don't count that case.
2. If the notification came when the user is in the live support chat, we don't support live update to the current chat thread. So we don't count that case as well.
