### ISSUE TITLE
There are some FXhash artworks lost data from indexer

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2131]
Please kindly use Sean address to debug this issue: tz1f6UyafTfyoBHStmEqcpfjA855rf26g2Nn.

Please also use these Michael addresses to check: 0x96C3233AfaAAe1Fec3F56949Bc20eC5247C0963A
tz1YSrengCy1pexrCu6xVs8wxXnHv2Vu4sXA

Thank you.

![image](https://user-images.githubusercontent.com/109057362/212596564-8616b0ab-c263-4ab7-b3ed-0c6b572c011e.png)
![image](https://user-images.githubusercontent.com/109057362/212596567-48576c19-3fc5-4f29-acf2-f87dee4c10f3.png)
![image](https://user-images.githubusercontent.com/109057362/212596800-95ccf286-2b4f-477e-bdfb-f62bbc6759f2.png)

**Comment by minhkstn** [comment]
the reason maybe because of the return of fxhash from `func (api *FxHashAPI) GetObjectDetail(c context.Context, id big.Int) (FxHashObjectDetail, error)`

**Comment by minhkstn** [comment]
[1 unit] find root cause

**Comment by Anais-bitmark** [comment]
Yes!! this my bug 🥳🥳
@minhkstn did you find out what was happening?
The thumbnail on the collection is constantly "loading"

**Comment by lemonlatte** [comment]
We create a story : https://github.com/bitmark-inc/autonomy/issues/1886 in the backend.

**Comment by minhkstn** [comment]
@longbmk the corresponding story https://github.com/bitmark-inc/autonomy/issues/1886 is done. This can be done too.

**Comment by longbmk** [comment]
@minhkstn this issue still happens. Please check this address: tz1f6UyafTfyoBHStmEqcpfjA855rf26g2Nn.
TokenID: tez-KT1EfsNuqwLAWDd3o4pvfUx1CAh5GMdTrRvr-22172

https://user-images.githubusercontent.com/109057362/232426680-99b57a3f-7297-42a8-81ae-1eba3da40056.MP4

**Comment by minhkstn** [comment]
[1 unit] fix another case where the thumbnailURL is empty.

**Comment by minhkstn** [comment]
@longbmk The code is ready for testing.

**Comment by longbmk** [comment]
[0.1 unit] This issue is fixed
