### ISSUE TITLE
Disconnect & revoke rights: connection remain even after disconnect

### ISSUE THREAD

**Issue by phuocbitmark** [bitmark-inc/autonomy-apps#2133]
Au app connects multiple times to a site.
When delete connections, user has to disconnect multiple times to clear all connections

**Comment by phuocbitmark** [comment]
https://user-images.githubusercontent.com/110799144/212649723-b8bc014e-7f93-4a14-a72e-a34f17d96ce7.mp4

**Comment by phuocbitmark** [comment]
[0.5 units] clear all connections at once

**Comment by longbmk** [comment]
This issue no longer happens.
