### ISSUE TITLE
Gif artwork is autoplay in Discover mode but cannot play in Artwork infor page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2148]
Please use this address to check or this tokenID to check:
tz1VVUxg8UdcsuSRVQxZiHAP7GqQ5uckLto7
tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-807476
https://user-images.githubusercontent.com/109057362/213127686-19e8ed4e-2d23-4bac-ad5c-448438c10642.MP4

**Comment by ppupha** [comment]
@longbmk it work on my phone. Please check again if it still happens.

https://user-images.githubusercontent.com/47568867/213363574-762a4953-e505-4788-8d74-01be3c5f0f31.mp4

**Comment by ppupha** [comment]
[0.2 units] replace thumbnail by artwork

**Comment by longbmk** [comment]
This issue no longer happens.
