### ISSUE TITLE
X button of Artwork preview page is larger than X button of Artwork infor page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2149]
![image](https://user-images.githubusercontent.com/109057362/213128396-5b5e6f79-2c7a-4979-89eb-5db9fd4ffed2.png)
![image](https://user-images.githubusercontent.com/109057362/213128416-d0432508-1067-4992-8ba9-1d10cc620911.png)

**Comment by ppupha** [comment]
[0.1 units] fix close icon size and update title size to 14

**Comment by ppupha** [comment]
Ready to test @longbmk

**Comment by longbmk** [comment]
This issue no longer happens
