### ISSUE TITLE
Sometime, Autonomy cannot connect to Metamask if user wait some minutes to click to connect Metamask

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2150]
Please see this video for more details.
https://user-images.githubusercontent.com/109057362/213132141-bcc214e9-886b-47c2-a673-bb910f0521fb.MP4

**Comment by hvthhien** [comment]
The socket connection might drop from Metamask, For this case, we don't receive any events to handle.

**Comment by longbmk** [comment]
@hvthhien I click at the second times, it open Metamask and Autonomy immediately. I think the connection is not dropped because it is very short time. Use is taking many times click to connect from AU to Metamask. Please kindly help to check it.
Thanks

**Comment by hvthhien** [comment]
@longbmk since we moved to the new wallet connect bridger server, the issue has been resolved, please check the latest develop/main.
