### ISSUE TITLE
App should preview with correct type

### ISSUE THREAD

**Issue by hvthhien** [bitmark-inc/autonomy-apps#2155]
Behavior: For now app auto fallback to the webview when the MIME Type is missing.

Expected: We should detect the MIMEType from the previewURL it's missing to show the correct preview type.

**Comment by trunghq17520184** [comment]
[o.5 units] get mimetype when loading artwork detail

**Comment by longbmk** [comment]
https://github.com/bitmark-inc/autonomy-apps/issues/2067

This bug is fixed in this ticket.
