### ISSUE TITLE
"Ledger connect" stucks at the Connecting screen if the connection has problem. We need to have the timeout for the connection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2177]
Steps:
1. Open Tezos application in Ledger
2. Open AU app
3. Link to Ledger by Ethereum wallet

Observed result:
Application still able to scan Ledger and try to connect. The connection is not timeout, user stucked at this screen and has no any method to back to another screen.

Expected result:
We should have a message to show wrong application and have the timeout connection.
![IMG_0754](https://user-images.githubusercontent.com/109057362/215429539-0793694d-a3b0-4037-a745-9d0a3fa889b5.PNG)

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by hvthhien** [comment]
[0.25 units] fix android connecting issue.
