### ISSUE TITLE
Rights section displays without any content

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2182]
Please use your address to check it.
tz1ijwENjgh5q9qtMUToqWfUYGQPC5pTTsaq
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/109057362/216000844-6ee8e8b1-d3aa-48e7-87f8-6e3c54047c2f.png)

**Comment by ppupha** [comment]
@Anais-bitmark @longbmk I see the orders of sections in artwork detail and feed detail are different:
In artwork detail: Metadata -> Provenance -> Right
In feed detail: Right -> Metadata -> Provenance
Which order is the correct one?

**Comment by ppupha** [comment]
[0.5 units] hide Right Section if its empty, Reorder sections in feed detail

**Comment by ppupha** [comment]
@longbmk ready to test
