### ISSUE TITLE
Link account always show Backup message from FeralFile instead of the correct management

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2184]
1. Link Metamask to Autonomy
2. Navigate to account detail of the Metamask linked account.

Observed result:
The Link account from Metamask displays content with FeralFile.

Expected result:
The link account should show correct management.

![IMG_B4C5849E0329-1](https://user-images.githubusercontent.com/109057362/216215969-f5064e87-a28c-49e0-98b1-701de544ae9d.jpeg)

**Comment by Anais-bitmark** [comment]
@longbmk 
This is an implementation bug.
The correct Ui for Linked wallet details is [here](https://www.figma.com/file/JoRz7cKKYw185VC1z6mAgw/Au_1742%3A-Settings-(rebranding)?node-id=18%3A5311&t=i5dKveg0dnbFdtl0-4)

![image](https://user-images.githubusercontent.com/61187455/219824292-ed4d8d7e-7946-47b6-9347-45ba6179ed7c.png)

**Comment by Anais-bitmark** [comment]
@anhnguyenbitmark 
This is an implementation bug.
I provided again the correct UI above.

**Comment by longbmk** [comment]
Thank you @Anais-bitmark.

Please kindly help to apply it @ppupha.

**Comment by ppupha** [comment]
[0.25 units] bug fixing

**Comment by ppupha** [comment]
@longbmk ready to test

**Comment by longbmk** [comment]
This bug no longer happens.
