### ISSUE TITLE
There are so many of the same push notification messages send to user at the same time when having feed event

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2189]
There are too many of the same push notification messages sent to user simultaneously when having a feed event. We should group the notification to only 1 message or update the message.
![image](https://user-images.githubusercontent.com/109057362/216499300-b546e78e-1e65-4c0a-9b5a-db9c6fc572d8.png)

Please kindly follow this document to apply it. https://documentation.onesignal.com/docs/notification-grouping

The discussion thread is here. https://bitmark.slack.com/archives/C034EPS6CLS/p1675376827204089

**Comment by lemonlatte** [comment]
[0.5] add the key and deployment
