### ISSUE TITLE
Sometime, Autonomy application get the out of memory issue

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#219]
<img width="1342" alt="Screen Shot 2022-07-18 at 13 58 09" src="https://user-images.githubusercontent.com/109057362/179460572-5df0238c-7cfb-400e-a880-b0659abd731b.png">

https://github.com/bitmark-inc/au-support-board/issues/345

**Comment by hvthhien** [comment]
Closed as duplicated with [#232](https://github.com/bitmark-inc/autonomy-apps/issues/232)
