### ISSUE TITLE
Missing spinner to wait for subscribing to cast the Artwork to Chrome cast

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#221]
Steps:
1. Open an Artwork NFT
2. Tap on Cast icon on top of screen
3. Tap con Subscribe button
4. Observe the screen

Observe result:
The application wait for subscribe loading response without any spinner.

Expected result:
There should be a spinner displays when waiting for subscribing response.

**Comment by hvthhien** [comment]
this can be considered an improvement for implementation later.

**Comment by longbmk** [comment]
Hi @caseyalt @Anais-bitmark, can you help to design the spinner for this issue?
Thank you very much

**Comment by longbmk** [comment]
@hungqd We also need the spinner to wait for loading list of casting devices when clicking on Cast icon after subscribing.

**Comment by hungqd** [comment]
0.5 point: show spinner when searching for cast devices.

**Comment by Anais-bitmark** [comment]
@longbmk I missed this one.
It would be good if we could move it into UI improvement.
And if we don't have time to treat it in this cycle it's pushed to the next one.
@hungqd If you've already done, can you send a screenshot of how it looks?

**Comment by Anais-bitmark** [comment]
@hungqd Does it looks like that?

![image](https://user-images.githubusercontent.com/61187455/186675225-e7c462bf-528b-4b3d-906c-ae2035ba00a0.png)
