### ISSUE TITLE
[TV][testflight]The user is not able to connect the app to the TV app. The "Unexpected problem" error is shown on the screen after trying to connect to the TV app

### ISSUE THREAD

**Issue by NekhDRej** [bitmark-inc/autonomy-apps#222]
Steps to reproduce:
- Open the TV Autonomy app
- Open the Autonomy app on the iOS
- Tap on the QR scanner
- Scan the code from the TV Autonomy app
- Tap on the "Authorize" button
- Pay attention to the result

Actual result: The user is not able to connect the app to the TV app. The "Unexpected problem" error is shown on the screen after trying to connect to the TV app
Expected result: The iOS app should be connected to the TV app after authorizing the app via QR code

Note: The "Error! Please try again" error is shown in the TV Autonomy app after scanning the code via the Autonomy app

Environment:
iOS build (TestFlight): 0.28.3 (2)
iPhone 12\iOS 15.5
TV build: 1.1.5
Chromecast with Google TV
![tv_error_2](https://user-images.githubusercontent.com/101094775/179470849-bf8ddb0a-3eea-43ab-b825-2a8f193f1e5f.jpg)

**Comment by hvthhien** [comment]
@NekhDRej Do you have a video, I'm still able to connect to Autonomy app. Or if the error happens, please send us a report, thank you.

**Comment by NekhDRej** [comment]
@hvthhien Here is the video. Also, I sent the log to you, check it from your side

https://user-images.githubusercontent.com/101094775/179479256-9c2ad486-c550-414a-8fb6-58d95f7caf65.mp4

**Comment by NekhDRej** [comment]
The issue is fixed

Environment:
iOS build (TestFlight): 0.30.0 (2)
iPhone 12\iOS 15.5
TV build: 1.1.5
Chromecast with Google TV
