### ISSUE TITLE
Restore/Link account in Onboarding makes the default account is not the first index account

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2227]
Steps:
1. Forget I exist to move to Onboarding screen
2. Link a Metamask account
3. Navigate to Account screen

Observed result:
Default account does not display in the first line.

Expected result:
Default account should be displayed in the first line after:
- [x] Restore an account
- [x] Link an account at onboarding

![1675829912449](https://user-images.githubusercontent.com/109057362/217451977-12380321-c11a-4bfa-9dba-04dbdda82786.JPEG)

**Comment by phuocbitmark** [comment]
[0.5 units] move default wallet into the first place, improve wallet loading time

**Comment by longbmk** [comment]
This issue no longer happens.
