### ISSUE TITLE
The videos still display when tapping on ">" btn while playing the videos

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#23]
**Steps to reproduce:**
1. Launch Autonomy
2. Play videos artwork
3. Tap on ">" btn
4. Check if the videos sound still play or not?

**Observed result:**
The videos still display when tapping on ">" btn while playing the videos

**Information:**
Build: 0.27.4(44) (App Center) Device:
- Ip13 pro max OS (15.3)
- Redmi Note 11S (Android 11)

https://user-images.githubusercontent.com/42630760/165420879-684dd2e6-03e6-41fd-adb5-2ded15c5049d.MP4

**Comment by hienphan1472** [comment]
This bug is fixed!
