### ISSUE TITLE
Indexer just returns 2 tokens although this specific address has 5 tokens

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2300]
Please check this user. https://opensea.io/0xbaa3B1cc281ccfe0AabA8c369d88FB3f11a9eaa9
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/109057362/218966319-0012b16f-6e42-4453-a833-a149e0b41572.png">

The indexer returns 2 tokens. This is the link.
https://indexer.staging.autonomy.io/nft?owner=0xbaa3B1cc281ccfe0AabA8c369d88FB3f11a9eaa9
<img width="957" alt="image" src="https://user-images.githubusercontent.com/109057362/218966660-266418e7-caaa-4e16-ace7-84ebf504ac1d.png">

**Comment by minhkstn** [comment]
This [token](https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/58354131420321349020814864904404910047759552326900780167473137817194233343765) has the contract address which is in the blacklist of our nfs-indexer server.

**Comment by minhkstn** [comment]
```
unexpected error while getting token owner address of the contract","contract":"0xc826833508d2DA724fD9105dE65ccA50aBFa2436","tokenId":"3","error":"opensea api error: {\"success\":false}"
```

**Comment by minhkstn** [comment]
```
unexpected error while getting token owner address of the contract","contract":"0x3B2aDD395a2cd156a75159028E913b397309e7EF","tokenId":"3","error":"opensea api error: {\"success\":false}"}
```

**Comment by minhkstn** [comment]
The above tokens are in Optimism network. Opensea API can't get metadata of these tokens.

To get metadata, use this https://docs.alchemy.com/reference/getownersfortoken

Read more: https://www.alchemy.com/overviews/optimism-nft-api

@lemonlatte I propose to have a story to support indexing tokens in this network

**Comment by minhkstn** [comment]
@longbmk Since the reason is from third-party API, we can't index Optimism tokens in our server. There's a contract that is in our blacklist (ie `0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85`), so we don't index it.

**Comment by minhkstn** [comment]
[1 unit] find bugs and propose a solution.

**Comment by longbmk** [comment]
@minhkstn Ok Minh. Let me close it because we don't support Optimism and dont show ENS artwork in our Collection
