### ISSUE TITLE
Artwork preview cannot load in Collection page after upgrading to Flutter 3.7.1

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2301]
Please use Autonomy Appcenter to import any address with artwork to check the artwork thumbnail in Autonomy.

![IMG_834DFED13FBB-1](https://user-images.githubusercontent.com/109057362/218990069-22ad44dc-9154-4931-a8b9-d6762fab668a.jpeg)

**Comment by hvthhien** [comment]
@hvthhien The issue was fixed, please help me to verify on the latest appcenter build

**Comment by longbmk** [comment]
This issue no longer happens.

**Comment by hvthhien** [comment]
[0.5 units] fix isolate issue after upgrading into
