### ISSUE TITLE
Artworks of old account still display then disappearing after user does the "Forget I exist"

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2318]
Steps:
1. Import an account that has at least 1 artwork
2. Navigate to Collections page
3. Fotget I exist
4. Create a new account
5. Observe the collection after creating a wallet

Observed result:
Previous collection displays then disappear.

Expected result:
Collections should be cleared cache first then loading new after creating a new wallet

https://user-images.githubusercontent.com/109057362/219317929-f0c8c366-b388-4208-945d-46cccb253830.MP4

**Comment by ppupha** [comment]
@longbmk ready to test.

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by ppupha** [comment]
[0.5 units] check and fix bug
