### ISSUE TITLE
Autonomy app is out of memory when open a IPFS NFT detail view and wait many time to load

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#232]
This issue happens in Sean's iPhone, Hien's iPhone 7.

Steps:
1. Launch Autonomy app
2. Open a NFT detail view
3. Wait for 5 minutes.

Observed result:
There is a message out of memory displays

Expected result:
Nothing error displays when app is loading/waiting

**Comment by anhnguyenbitmark** [comment]
Waiting for https://github.com/bitmark-inc/autonomy/issues/1418
