### ISSUE TITLE
Artwork owner display 0 although user is owning the token

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2322]
Please kindly contact me to get the seed to debug. Please see the video for more detail.
https://github.com/bitmark-inc/au-support-board-test/issues/1653
https://user-images.githubusercontent.com/109057362/219342938-0806de86-7b8d-4e1d-86c8-03df0534465a.MP4

https://indexer.autonomy.io/nft?owner=tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM
https://indexer.staging.autonomy.io/nft?owner=tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM

Please query with Balance = 0 for "Gogeta" artwork

**Comment by minhkstn** [comment]
The API should be `v1/nft`. It returns tokens with balance > 0 on both staging and production.

**Comment by minhkstn** [comment]
```
"id": "53282417003504234343034903226908894718267038890916105456212014626752617807589",
    "blockchain": "tezos",
    "fungible": true,
    "contractType": "fa2",
    "contractAddress": "KT1QWATcHYpBVDxvNoxw5CbkaMGpjm4SxXa2",
    "edition": 0,
    "editionName": "",
    "mintedAt": "0001-01-01T00:00:00Z",
    "balance": 1,
    "owner": "tz1dBwDL1Ze9zKtfBdiS1WcLZrqDjfgqBUuR",
    "owners": {
      "tz1cHjB7VgfnzfMjy9SW8XUKBDd39fArLcFs": 1
    },
```

**Comment by minhkstn** [comment]
@longbmk @lemonlatte Please check the above problem I describe. The `owners` of some fungible  Tezos `tokens` are not updated like `account_tokens`. I think we need to fix it to make consistent

**Comment by longbmk** [comment]
This issue is ok in /v1. Let me close it. Thank you Minh.

**Comment by minhkstn** [comment]
[0.5 units] investigate the bug
