### ISSUE TITLE
Discovery stucks and spinner spins never end at the first time, when importing an address that has too many artworks

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2341]
Steps:
1. Import the addresses has many artworks
2. Load the Discovery tab

Observed result:
The Discovery stuck. The spinner spins never end. When user kill the app and reopen, the Discovery loads success.

Expected result:
Discovery should be call to prepare when user imports or link any address that has feeds event

https://github.com/bitmark-inc/au-support-board-test/issues/1663

**Comment by ppupha** [comment]
Address to debud:
0x91B4015A7482e3185EEaEE3c9d7FC6f113e7FD69
tz1d8uUEijk6BYb31a79k2UtJtv4xzK1puxY
0x670236E395b27f095E184f2067D4d25EEf1aC73f
tz1Uh2RpzF72AH4WmpysFGNThHn5apP6YFcx
tz1gEVqnejRkwfpfqoxhTfi9tDm1xT2mqiGV
0xa29Ad67470bcA02Bb73285ca2637C167Bbe32A3D

**Comment by ppupha** [comment]
@longbmk it takes to long to load discovery because there are many artwork in this wallet. Please wait for about 1 min.

**Comment by ppupha** [comment]
[0.25 units] check bug

**Comment by ppupha** [comment]
@longbmk  this story was fixed by [Discover feed fail to load #1982](https://github.com/bitmark-inc/autonomy/issues/1982). Please check if this issue is still happen.

**Comment by longbmk** [comment]
This issue no longer happens
