### ISSUE TITLE
Au staging mainnet app is using /nft API in v0 instead of v1

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2343]
Au staging mainnet app is using /nft API in v0 instead of v1 because I call the API v1 because I called the V1 and it returns no token but the app still show 3 token Gogeta like v0 API
This is the address to debug: tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/109057362/219572517-21e80034-4e22-4370-9f08-2783535837b8.png">
https://indexer.staging.autonomy.io/nft?owner=tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM

<img width="951" alt="image" src="https://user-images.githubusercontent.com/109057362/219572680-43a4ae4c-a878-40a0-9859-077f6550d64e.png">

**Comment by phuocbitmark** [comment]
i have checked the log and the APIs. app only call v1, and data from indexer matched with ui. So, if it's a bug, it's probably from backend

**Comment by longbmk** [comment]
Ok Phước. Thank you, the API V1 also returned data. So I will close this ticket.

**Comment by longbmk** [comment]
@phuocbitmark Please log work if it takes your time @phuocbitmark. If not, please change it to 0 Unit. Thank you

**Comment by phuocbitmark** [comment]
[0.25 units] investigate
