### ISSUE TITLE
Artwork owner display 0 when user has 2 addresses that holding the same token from OpenSea/Objkt

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2369]
Artwork owner display 0 when user has 2 addresses that holding the same token from OpenSea. IndexID from 2 accounts has the same indexID. Please use my addresses to debug this case.
0x49891bFFfe8c573dc969adA7A9E8645A35ceaC92
0x029B6d25EcF32543F1beC3323325F4dc46fE1c54

Steps:
1. Import an account has a 1155 token
2. Import an another account has a 1155 token in account in step 1
3. Move to Send artwork screen of this 1155 token

Observed result:
Owner token display 0

Expected result:
Owner token should display correct amount.

https://user-images.githubusercontent.com/109057362/220048453-7cb8414e-7fdd-4846-9da4-82bcf306d4d5.MP4

**Comment by anhnguyenbitmark** [comment]
@Anais-bitmark : To me we should display one artwork in the collection page even there are multiple addresses have this token. And in the artwork detail, we list out the addresses and their balance for that token.
For sending out the NFTs, we allow user to choose the source address (which has the token), and display the available amount that the user can input.

**Comment by longbmk** [comment]
@Anais-bitmark Can you take a look in this issue? We need to finalize the case 2 addresses holding the same token 1155 and these 2 addresses are imported to our Autonomy. We need your help for this design. 
cc @anhnguyenbitmark

**Comment by trunghq17520184** [comment]
[0.25 units] Check and fix the balance of token

**Comment by longbmk** [comment]
This bug is fixed. Thank you Trung

**Comment by Anais-bitmark** [comment]
@longbmk 
Is this solved or you still need my help on it?
