### ISSUE TITLE
Missing Pending thumbnail displays to wait for token after purchasing Tez/Ethereum artwork 

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2370]
Steps:
1. Purchase a Tezos/Ethereum artwork
2. Load the Collection and wait for blockchain confirm
3. Observe the collection to wait for Pending thumbnail

Observed result:
Missing the Pending thumbnail displays when waiting for the token deliver

Expected result:
- [ ] Pending token should display when waiting for token is delivered for Tezos network
- [ ] Pending token should display when waiting for token is delivered for Ethereum network
- [ ] Pending token disappears after token delivered for Tezos
- [ ] Pending token disappears after token delivered for Ethereum

**Comment by hvthhien** [comment]
[0.5 units] update pending token for tezos.

**Comment by longbmk** [comment]
[0.1 unit] This issue no longer happens.
