### ISSUE TITLE
There are inconsistency between owner and owners data of a token after user transfer the token

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2372]
Please check with this indexID. Owner has update in account_tokens collection but the owners does not update.
https://github.com/bitmark-inc/autonomy-apps/issues/2322.

# "id": "53282417003504234343034903226908894718267038890916105456212014626752617807590",
    "blockchain": "tezos",
    "fungible": true,
    "contractType": "fa2",
    "contractAddress": "KT1QWATcHYpBVDxvNoxw5CbkaMGpjm4SxXa2",
    "edition": 0,
    "editionName": "",
    "mintedAt": "0001-01-01T00:00:00Z",
    "balance": 1,
    "owner": "tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM", // in account_tokens collection (correct)
    "owners": {
      "tz1cHjB7VgfnzfMjy9SW8XUKBDd39fArLcFs": 1 // in tokens collection (wrong)
    },
    "originTokenInfo": null,
    "indexID": "tez-KT1QWATcHYpBVDxvNoxw5CbkaMGpjm4SxXa2-53282417003504234343034903226908894718267038890916105456212014626752617807590",

**Comment by minhkstn** [comment]
Currently, Production env returns wrong owners but Staging env returns correct owners

- Production
```
"owner": "tz1cHjB7VgfnzfMjy9SW8XUKBDd39fArLcFs",
        "owners": {
            "tz1cHjB7VgfnzfMjy9SW8XUKBDd39fArLcFs": 1
        },
```

- Staging
```
"owner": "tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM",
        "owners": {
            "tz1R58U5ovKoo3pUwFMdSEWEcftYGvkfoUHM": 1
        },
```

**Comment by hvthhien** [comment]
@longbmk @minhkstn  The owners filed is deprecated, we shouldn't use it anymore.

**Comment by longbmk** [comment]
Ok. Let me close it. Thank you
