### ISSUE TITLE
Missing opensource link under changelog and privacy policy link under settings after doing the Rebranding

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2394]
Apple blocks our Autonomy app. Please update the design and Autonomy app to have these points unlocked.

- [ ] add an opensource link under changelog
- [ ] add privacy policy link under settings

**Comment by Anais-bitmark** [comment]
@hvthhien 
Ui is ready
[Figma](https://www.figma.com/file/axRaqQxsfBfxY7zFWtRj1O/Bug_2394%3A-Missing-opensource-link-under-changelog-and-privacy-policy-link-under-settings...?node-id=0%3A1&t=lnAokmZAt2RQXC4Q-1)

<img width="1226" alt="Capture d’écran 2023-02-23 à 10 18 18" src="https://user-images.githubusercontent.com/61187455/220879531-d6d541b9-188d-4cc1-ae92-80a727c49bea.png">

**Comment by hvthhien** [comment]
[0.5 units] add opensource privacy links.
