### ISSUE TITLE
[FF + Au][iOS] Cannot Disconnect / Revoke Autonomy from FF on Autonomy app 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#24]
**Steps to reproduces:**
1. Create FF account
2. Launch Au app
3. Scan QR code to link to FF account (W3)
4. Sign
5. On Autonomy App
6. navigate to Connections
7.  Revoke Autonomy from FF
8. Check the Connections on App
9. Check the Connections on FF

**Observed result:**
- App displays no connection with FF on App. But Users still being connected to FF
- However on FF, Web3 wallet still is the option to connect with FF

**Information:**
Build: 0.27.4 (44) (App Center) 
Device:
- Ip13 pro max OS (15.3)
Attachment: 
https://user-images.githubusercontent.com/42630760/165883455-17967ed7-a818-4f2a-a0c8-f1d6263359b5.MP4

**Comment by anhnguyenbitmark** [comment]
Closed. We will revisit the Feral File <> Autonomy linking on Q3.
