### ISSUE TITLE
Owned field in Artwork infor does not update to new amount after sending the artwork to another address

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2400]
Steps:
1. Import a wallet that has at least 1 a 1155 token with owned greater than 1
2. Transfer the token to another address
3. Close the Confirm transfer popup after doing transfer
4. Observe the Owned field of the artwork.

Observed result:
Owned field still retains in old data.

Expected result:
- [ ] Owned field should be updated to new value after sending. 
- [ ] We need to check the local DB to store and update after blockchain confirmed.

https://user-images.githubusercontent.com/109057362/220823111-c93439de-74a0-4f77-9eac-e2995497930a.MP4

**Comment by ppupha** [comment]
@longbmk this bug happened because that it is need about ~20mins to confirm sending.

**Comment by ppupha** [comment]
https://user-images.githubusercontent.com/47568867/226265311-1b7d5574-09c3-4bbd-bfb8-c1b7412bff23.mp4

**Comment by ppupha** [comment]
[0.5 units] bugs fixing

**Comment by ppupha** [comment]
@longbmk ready to test
we force decrease the owned field after sent. It will be reverted after 2 min.

**Comment by Toromambo** [comment]
need to confirm to blockchain

**Comment by Bullet1010** [comment]
please follow guidelines

**Comment by moskovich** [comment]
@Bullet1010 what guidelines are you referring to? Can you share a link?

**Comment by longbmk** [comment]
This bug no longer happens
