### ISSUE TITLE
Feed event still fetch although all wallets are removed

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2448]
Steps:
1. Add some wallets that have artworks
2. Wait for Discovery load full feed event
3. Delete all wallets to make the Collection has no any artworks.
4. Load the Discovery tab.

Observed result:
Discovery still loads artwork
https://user-images.githubusercontent.com/109057362/222048730-91af8134-51f1-4d8a-a053-3d77fdbc15b2.MP4

Expected result:
Feed event should be updated and backup when remove wallets

**Comment by phuocbitmark** [comment]
@longbmk  probably same problem of [#2893](https://github.com/bitmark-inc/autonomy-apps/issues/2893)

**Comment by longbmk** [comment]
Currently, Discovery is no longer in our app. Let me close and reopen when it backed
