### ISSUE TITLE
Provenance time does not base on the timezone of client time when opening the artwork info

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2467]
My timezone is GMT+7 but the time loading seems GMT+5. It should base on client time.
Please use this tokenID to debug:
eth-0xb43c51447405008AEBf7a35B4D15e1f29b7Ce823-25799626422107336106799441989037798636229641625220763022744216897291922308939

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/109057362/222641155-9ec531a1-9cdf-44cc-8ea9-a9efb267323f.png">

![IMG_0822](https://user-images.githubusercontent.com/109057362/222641219-0a249540-82aa-4d86-b40f-e559cd37f408.PNG)

**Comment by ppupha** [comment]
@longbmk i check and this is not an issue.
