### ISSUE TITLE
Camera app does not show Connect to Autonomy when scan QR to Autonomy connect/Migrage web3 in Feralfile

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2486]
We need to change URI from wc: to autonomy: in the supported deeplink. After open AU app, the deeplink should be support to do the connection. Currently, when replace the wc: to autonomy:, the connection cannot establish.

1. We need to change to support both current schema to connect and new schema to just show "Connect to Autonomy". 
2. After we finish in AU, FF will update and we do the test for integration.
3. After integration, we remove the old schema in AU.

Note: Please notice this just support for Autonomy connect, not affect to WalletConnect.

![IMG_7E4B97B9B4A7-1](https://user-images.githubusercontent.com/109057362/223020353-a0beaf48-a99a-4377-9d9e-d8b05c10ab8d.jpeg)

**Comment by hvthhien** [comment]
[0.25 units] Investigate issue, add some more deeplink schemes supported in app.

**Comment by longbmk** [comment]
[0.1 unit] Check for the camera app shows and open in Autonomy app
