### ISSUE TITLE
Tezos transaction: amount display incorrectly

### ISSUE THREAD

**Issue by phuocbitmark** [bitmark-inc/autonomy-apps#2494]
For claim and mint transaction on objkt, amount display incorrectly
checkout tx: https://tzkt.io/ooia4VJK35JbtBZGFsyKhpv4nJb1aWKXrQtT9WHrKgwahLNonZY/73298377

**Comment by phuocbitmark** [comment]
[0.75 unit] for claim transaction -> show "Bought NFT"; fix scrolling

**Comment by phuocbitmark** [comment]
![Image](https://user-images.githubusercontent.com/110799144/223603042-2915ee1e-2579-4324-8eda-7764719c6dfc.png)

**Comment by longbmk** [comment]
This issue no longer happens
