### ISSUE TITLE
There are some artworks have thumbnailURL are stranger format, so that the artwork thumbails display black cover

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2495]
Please use these addresses to debug. Thanks
tz1YokFzMR1hX4m4aBqgutxLSUKFDdNoYGEN
tz1YzPosgwSCShxBJy6BVuR3QtRXyt5cP2WR
tz1SneH7oDuU2T1JDPSvJ4haKnqVqNNctMhW

https://user-images.githubusercontent.com/109057362/223352247-a4440a2e-0552-4135-b74e-bd439fc13f1d.mp4

**Comment by lemonlatte** [comment]
@longbmk I think this is also solved. Do we encounter this recently?

**Comment by moskovich** [comment]
@longbmk can you retest this?

**Comment by longbmk** [comment]
The thumbnail displayed correct. I think we can close this ticket
