### ISSUE TITLE
Missing rebranding for the Web3 Glossary full screen

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2511]
[figma](https://www.figma.com/file/LZqJp7JstDzclSyycZViks/Au-bug_2511%3AMissing-rebranding-for-the-Web3-Glossary-full-screen?node-id=0%3A1&t=5bwkpkZ7PqM44zWo-1)

![image](https://user-images.githubusercontent.com/109057362/224674026-fcb48bfa-e539-4864-ba1b-39e2bcacd870.png)

**Comment by Anais-bitmark** [comment]
@ppupha 

[Figma](https://www.figma.com/file/LZqJp7JstDzclSyycZViks/Au-bug_2511%3AMissing-rebranding-for-the-Web3-Glossary-full-screen?node-id=0%3A1&t=5bwkpkZ7PqM44zWo-1)
UI is ready.
It should be the same Ui warning as for other artworks played fullscreen.
Displayed for 4s and then disappears.

<img width="1105" alt="Capture d’écran 2023-03-13 à 11 52 24" src="https://user-images.githubusercontent.com/61187455/224694265-af1d2892-b286-4a9e-8b3d-255609d506ec.png">

**Comment by ppupha** [comment]
@Anais-bitmark 

https://user-images.githubusercontent.com/47568867/224878368-25d82b22-de5d-4490-8d25-7a33db5cabda.mp4

**Comment by ppupha** [comment]
[0.5 unit] bugs fixing
