### ISSUE TITLE
Indexer does not update lastActivityTime correct although user purchases a new token and it delivered to user

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2513]
Solution:
So this is the things we should update (https://bitmark.slack.com/team/U03NZ7JU8KC):
- [x] Find and update the missing tokens lastActivityTime during indexAsset.
- [x] Update v2/nft to use lastActivityTime of the account_tokens
- [x] Update pending to use lastActivityTime
Not sure this will affect on anything: GetTokenBalanceAndLastTimeForOwner always return zero last time due to the change in PR#99 --> Please take a look on it @minhkstn.

Not sure do you have anything else to add? --> Please take a look on it @lemonlatte 

Issue detail:
When I purchase the new token from Objkt, the lastActivityTime update incorrect. So that it make the Pending token in UI does not disappear and show the real token. It also make the token sort is not the 1st in the Collection page after purchasing.
Please check on my address here. https://indexer.staging.autonomy.io/v2/nft?owner=tz1dBwDL1Ze9zKtfBdiS1WcLZrqDjfgqBUuR

![image](https://user-images.githubusercontent.com/109057362/224680930-5b515670-7da6-47e5-90a4-e9fe9ad82f4a.png)

**Comment by minhkstn** [comment]
[0.5 units] update code.

**Comment by minhkstn** [comment]
[1 unit] update code.

**Comment by longbmk** [comment]
This issue is fixed. Thank you Minh
