### ISSUE TITLE
AU app still listen pending event for transfer burning token in MoMA burn

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2516]
1. Import address has Moma burn
2. Autonomy connect to Feralfile
3. Burn token
4. Observe Autonomy collections screen

Observed result:
There are 4 pending tokens display in Collection

Expected result:
- [ ] 3 Burning transaction should not be listion in AU
- [ ] 1 pending for new token keep listening
https://user-images.githubusercontent.com/109057362/224896883-bd60ecef-8dba-431a-8e5c-e7432a285d06.MP4

**Comment by longbmk** [comment]
This bug no longer happens.

**Comment by trunghq17520184** [comment]
[0.5 units] Filter transaction form eth
