### ISSUE TITLE
There are some MoMA burn artworks and new minted artworks do not contain provenance in indexer

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2518]
Please kindly use my address to debug for this. I am not sure this issue happens in production but in testnet, it happens. To make sure it not happens, we need to have a good process to apply the fix for it.

https://indexer.test.autonomy.io/v2/nft?owner=0x49891bFFfe8c573dc969adA7A9E8645A35ceaC92 
eth-0xDb06644CC66BF122CD5A140f5DEb373F9CaBa46E-65590127784515406696723934469870875483509898408649268851331845618087849791227

**Comment by minhkstn** [comment]
@longbmk  I can't find that token in your address. Could you please check it again?

**Comment by minhkstn** [comment]
@longbmk I believe this is not a bug. When the token is fixed indexed in our DB, the provenance is null on purpose. The job of refreshing provenance is a heavy task to we don't do it in indexing. When the token is transferred to a new account by the Au user, the provenance will be updated.

**Comment by minhkstn** [comment]
[0.5 units] check the issue.

**Comment by longbmk** [comment]
@lemonlatte can you please help to take a look to have better solution in here? Thank you

**Comment by minhkstn** [comment]
Currently, we call `indexWorkflow` for all new tokens that are not index in DB. This results in null provenance but it is expected for general tokens.

We need to re-design `event-processor` to get provenance/ownership or minted tokens.

**Comment by longbmk** [comment]
This issue no longer happens.
![IMG_9877](https://user-images.githubusercontent.com/109057362/232431045-4cfdf078-bac2-4a36-9a60-ad051b63ca24.png)
![IMG_9876](https://user-images.githubusercontent.com/109057362/232431050-e27f8d9b-8e32-494c-9bf9-eeb782cc035d.png)
![IMG_9875](https://user-images.githubusercontent.com/109057362/232431052-1cc57c06-79e0-4d7d-bea6-ce56da14dd35.png)
