### ISSUE TITLE
Missing rebranding for User identity popup when clicking on user's address in provenance data in Artwork info page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2520]
![image](https://user-images.githubusercontent.com/109057362/225187236-7b9d43fc-5e8b-4008-8c7a-5eb281f9e42e.png)

**Comment by ppupha** [comment]
@Anais-bitmark please provide UI for this bug story

**Comment by Anais-bitmark** [comment]
@ppupha 
UI is ready
[0.25 unit] UI

[Figma](https://www.figma.com/file/ktcFyk4JCwOkGkd2ZEPlG9/Au-bug_2520%3A-Missing-rebranding-for-User-identity-popup?node-id=0%3A1&t=04h5Wp8k4QkDrnRK-1)

<img width="793" alt="Capture d’écran 2023-03-24 à 02 43 51" src="https://user-images.githubusercontent.com/61187455/227403140-4ff70b46-4e6f-4248-9ad2-0b6b1d2f1079.png">

**Comment by ppupha** [comment]
[0.25 units] fix bugs

**Comment by longbmk** [comment]
This issue no longer happens
