### ISSUE TITLE
Collection displays blank space although it has much tokens when having some wallets are hidden

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2526]
Steps:
1. Import some wallets have many artwork
2. Hide 1-2 wallets that have artwork at the 1 page of the collection
3. Kill AU app
4. Reopen AU app

Observed result:
There are some blank space display and scroll down will show artworks

Expected result:
The Collection should optimize for both all wallets show and some of them are hidden.
https://user-images.githubusercontent.com/109057362/225848639-45cde189-b336-4466-8a0a-baaa440b1b99.MP4

**Comment by ppupha** [comment]
[0.5 unit] investigate, fix bug

**Comment by longbmk** [comment]
This issue no longer happens
