### ISSUE TITLE
Missing NFT from Bitmark blockchain after linking the account to Autonomy

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2529]
Please use this QR code to link and debug
https://drive.google.com/file/d/14NnD0oyjlv-CsR_qhcF3LdRCkt_4-4ZE/view?usp=share_link

**Comment by minhkstn** [comment]
[0.5 units] fix bug.

**Comment by longbmk** [comment]
This bug is fixed.
