### ISSUE TITLE
Aggregated collectors that we list in the discover feed should also be applied when opening the artwork details in discover.

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2530]
![image](https://user-images.githubusercontent.com/109057362/226547177-61daff34-1946-4a4b-935a-4951d2bdb3d6.png)
![image](https://user-images.githubusercontent.com/109057362/226547204-d928371f-6828-47bb-b292-7b1bf0c5d9cf.png)

**Comment by ppupha** [comment]
@longbmk ready to test
