### ISSUE TITLE
The new collection and indexer missed sync up after some using time

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2536]
1. Install the new app with new collection
2. Import some wallet has artworks
3. Wait some days
4. Open the collection

Observed result:
Missing some artworks in the collection. Do the rebuild metadata will resolved it

Expected result:
Collection should update to reflect new update from Indexer

**Comment by trunghq17520184** [comment]
[0.5 units] Investigate and fix the type of `isFeralFileFrame`

**Comment by longbmk** [comment]
This issue no longer happens.
