### ISSUE TITLE
Estimate fee does not calculate when user lost focus the address/amount field in transfer/Validate Transaction page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2537]
1. Navigate to Send artwork/Sent crypto page
2. Enter address
3. Enter amount
4. Lost focus amount field

Observed result:
Fee is not calculated when losting focus Amount field. It just calculate when press done in vitual keyboard

Expected result:
- [x] Fee should be calculated when user lost focus amount field in Transfer crypto page
- [x] Fee should be calculated when user lost focus address field in Transfer NFT page

**Comment by ppupha** [comment]
@longbmk ready to test

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by ppupha** [comment]
[0.5 unit] fix bugs
