### ISSUE TITLE
Spinner still displays when artwork is loading a part

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2550]
We can try to have the webview transparent, and put the spinner behind (in z-order). Then when the webview begain having some content, it would cover the spinner.
The discussion is here.
https://bitmark.slack.com/archives/C034EPS6CLS/p1679929346415099

![image](https://user-images.githubusercontent.com/109057362/228117400-45ec0a4f-51fa-495b-b4c3-4351a9ba67ad.png)

![image](https://user-images.githubusercontent.com/109057362/228117426-1585f554-10cd-4ee5-9409-8e66b61035e3.png)

**Comment by ppupha** [comment]
[0.5 unit] update Gif view and nft_rendering

**Comment by ppupha** [comment]
@longbmk this story is ready to test.

**Comment by longbmk** [comment]
[0.1 unit] Check the bug with token tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-773426.
