### ISSUE TITLE
Collection order wrong - The new purchasing token does not update at the first of collection, it is mixing to the middle of collection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2551]
Steps:
1. Collection has many tokens
2. Puschase a new token
3. Wait for indexer confirm

Observed result:
The new purchasing token does not show at the first token in collection.

 Expected result:
The new purchasing token should display at the first token in collection

Note: The example for this issue. https://bitmark.slack.com/archives/C034EPS6CLS/p1680234144212629

**Comment by minhkstn** [comment]
because we have many events queued in `event-processor`, the new purchased token might not be processed by `event-processor`. It is processed by `/index`

**Comment by lemonlatte** [comment]
We create a story: https://github.com/bitmark-inc/autonomy/issues/1894 on the backend.
