### ISSUE TITLE
MoMA postcard does not display the Confirm screen after scanning the QR code by Camera app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2556]
1. Install the Production app
2. Scan the MoMA QR code by Camera app
3. Open the AU app

Observed result:
Missing the Confirm MoMA postcard screen.

Expected result:
There should be the Confirm MoMA postcard screen when scan QR code by Camera app

**Comment by trunghq17520184** [comment]
[0.5 units] Update confirm screen
