### ISSUE TITLE
User is still able to back to previous screen by swiping left to right in Onboarding/Add new wallet page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2558]
1. Go to Onboarding->Create new wallet
2. Swipe left to right to back

Observed result:
The previous screen displays

Expected result:
The swipe back event should be disable when creating a new wallet
https://github.com/bitmark-inc/autonomy/issues/1858

**Comment by ppupha** [comment]
[0.5 unit] prevent back from name account.

**Comment by ppupha** [comment]
@longbmk this story is ready to test

**Comment by longbmk** [comment]
This issue no longer happens.
