### ISSUE TITLE
The owned token display 0 when transfering a 1155 token to a new address in the Autonomy app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2572]
https://github.com/bitmark-inc/autonomy-apps/issues/2400

https://user-images.githubusercontent.com/109057362/230878536-35712d4c-90c6-4dc6-b824-d61a6875e224.MP4

**Comment by ppupha** [comment]
@longbmk this story is ready to test

**Comment by ppupha** [comment]
[0.5 unit] fix bug

**Comment by longbmk** [comment]
[0.1 unit] This issue no longer happens
