### ISSUE TITLE
Sometime, black screen displays when linking Metamask to Autonomy

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2575]
This issue rarely happen. Just connect to Metamask from AU app and black screen displays
https://github.com/bitmark-inc/au-support-board/issues/1301

**Comment by ppupha** [comment]
We have removed linked wallet, so this bug will not happen.
@longbmk please close this bug.

**Comment by longbmk** [comment]
Yes, let me close it. Thank you Sang
