### ISSUE TITLE
Autonomy does not show error message when having issue to contact RPC node

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2586]
Please kindly share us the design to update @Anais-bitmark.
We need to handle the case connection to RPC failed to prove the issue is from the node and we need the user to retry manually.
Thank you

**Comment by Anais-bitmark** [comment]
@trunghq17520184 
[Figma](https://www.figma.com/file/yc7j1IsnPuUF34F0POqwqH/Au-bug_2586%3A-Autonomy-does-not-show-error-message-when-having-issue-to-contact-RPC-node?node-id=0%3A1&t=xMDrkkNorI3NXhJC-1)

<img width="1510" alt="Capture d’écran 2023-04-13 à 10 09 03" src="https://user-images.githubusercontent.com/61187455/231727272-57c3a262-c6d3-4b02-b296-f148a7ede886.png">

**Comment by trunghq17520184** [comment]
[0.5 units] Update message and retry estimate

**Comment by longbmk** [comment]
[0.1 unit] Check for case timeout, not enough money to pay fee. Work collaborate to check case node fail with Trung.
