### ISSUE TITLE
Missing TNS/ENS for provenance of the artwork if the address has TNS/ENS

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2591]
Please use this address to debug. tz1YhWtCRd9LKr1rtd3wdCCz2ceNWAsS2Lnd

![image](https://user-images.githubusercontent.com/109057362/232376869-d7f453d4-d507-4b54-b397-da64044a4891.png)

**Comment by ppupha** [comment]
[0.5 unit] fix bug

**Comment by longbmk** [comment]
[0.1 unit] This issue no longer happens
