### ISSUE TITLE
User is not able to hide an address in the account that linked from Bitmark collection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2593]
Please use this QR to link addresses and reproduce by my video.
https://drive.google.com/file/d/14NnD0oyjlv-CsR_qhcF3LdRCkt_4-4ZE/view?usp=share_link

https://user-images.githubusercontent.com/109057362/232422278-0cad5c13-c279-485b-a635-2c88acfd9fbf.MP4

**Comment by longbmk** [comment]
[0.1 unit] This issue no longer happens

**Comment by phuocbitmark** [comment]
[0.5 unit] fix hide link account
