### ISSUE TITLE
There are some displayed issues need to update

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2598]
- [ ] There is also too much space at the top if you look at non-base wallet
![image](https://user-images.githubusercontent.com/109057362/232953122-56427cba-7001-4334-aabc-583a8abc01d4.png)

- [ ] There is still an old font used for the link on recovery phrase screen.
![image](https://user-images.githubusercontent.com/109057362/232953158-f67c1f45-cfc2-4f04-93e3-29e3ab0e34dd.png)

- [ ] Can we fix the spacing above the first article in Editorial? It should « breath » a bit mores see Figma design.
![image](https://user-images.githubusercontent.com/109057362/232954749-ccc4eb24-8ea6-4e0f-846b-847544e20e96.png)
![image](https://user-images.githubusercontent.com/109057362/232954761-c67442dd-b7a7-402f-ad1e-305ab3b506a5.png)

- [ ] Keep header font-size fixed even if change font-size for the content of the article. Also I need to fix how we display long title in header.
![image](https://user-images.githubusercontent.com/109057362/232955464-749a5cf0-158f-45f9-b240-86402543c252.png)

- [ ] On linked wallet screen:
Helper phrase under recovery should be 14px.
- [x] We shouldn’t see the brackets <…> around « Temple - Tezos Wallet ».
<. >. was just to show that we need to adapt the name depending on the wallet.
![image](https://user-images.githubusercontent.com/109057362/232954800-8e586eb5-5b7f-4975-9e49-3f60f6210944.png)

- [ ] Please add "s" for artwork
![image](https://user-images.githubusercontent.com/109057362/232957610-efef65cb-125e-4843-9178-f1bd2e132294.png)

**Comment by ppupha** [comment]
@longbmk this story is ready to test.
