### ISSUE TITLE
[FF][Sign in]Can not Sign to FF using scan QR in Autonomy app (using browser on same device)

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#26]
https://bitmark.slack.com/archives/C034EPS6CLS/p1648567372956089

**Steps to reproduce:**
1. Navigate to FF on browser
2. Click on Sign in btn
3. Choose Autonomy
4. On Autonomy: Tap Connect btn

Observed result:
Nothing happens. 

**Information**:
Build: 0.27.4(44) (App Center) Device:
- Ip13 pro max OS (15.3)
- Attachment: 
https://user-images.githubusercontent.com/42630760/161910386-bbb22187-2b3a-49ac-a25f-7aa84a0652fe.MP4

**Comment by hvthhien** [comment]
@NekhDRej n
Be aware that once the session is rejected, you cannot connect again. So if you open the app via the link and then reject it, you need to go back, exit the page containing the QR then try tapping to link again to reset your connection.

**Comment by NekhDRej** [comment]
The bug is fixed

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10

https://user-images.githubusercontent.com/101094775/175950908-b30fdf47-5548-49cc-87ea-2faf625f9b53.mp4
