### ISSUE TITLE
Please update to use thumbnailURL instead of previewURL because of FF updated to it

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2614]
https://bitmark.slack.com/files/U02CDSQSG/F050KMZ2HFA/image_from_ios.jpg

https://bitmark.slack.com/archives/C034EPS6CLS/p1679547360528179

**Comment by ppupha** [comment]
FF will fix this bugs.

**Comment by moskovich** [comment]
@ppupha what's the status here?

**Comment by ppupha** [comment]
This issue was fixed by FF. 
@longbmk please help to test again.

**Comment by longbmk** [comment]
Yes, it fixed. Let me close it
