### ISSUE TITLE
Postcard from 1st user dissappears after backend confirmed 2nd user stamps success

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2615]
It makes the FT token to NFT and balance change to 0. It should retain the token balance for user 1
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/109057362/234827726-71c8a378-dce5-477e-b787-3e869295b263.png">

**Comment by minhkstn** [comment]
`fungible=false` ==> indexer treats those postcard as non-fungible because of missing the assign for `Fungible` in `indexTezosToken()` in Dev env.

**Comment by lemonlatte** [comment]
@longbmk please follow on this

**Comment by longbmk** [comment]
This issue no longer happens.
