### ISSUE TITLE
QR code in website does not update to refresh in Brave browser

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2624]
Please fix it in 
- [ ] Mobile Brave browser
- [ ] Desktop Brave browser
![Screenshot_20230428-113010_20230428_113022099](https://user-images.githubusercontent.com/109057362/235054726-0211bab3-287c-4267-9e5b-b04e3cf98ac1.jpg)

**Comment by phuocbitmark** [comment]
@longbmk i checked with my mac, at first it only loaded text, but when i turns down Shield, i was be able to load qr code and video
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/110799144/235296707-7511304a-d862-4a14-ad9d-03d91a337479.png">

**Comment by phuocbitmark** [comment]
same thing happened to my phone (android)

**Comment by longbmk** [comment]
Ok. This issue can be closed.

**Comment by phuocbitmark** [comment]
[0.25 unit] checking issue
