### ISSUE TITLE
Postcard - Missing push notification after the postcard is accepting/stamping

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2629]
- [x] When a user accepts the postcard, we need to have a push notification to notify to all users holding the postcard.

**Comment by longbmk** [comment]
Please fix this option @PhucDuongBitmark. The remaining will need @anhnguyenbitmark to confirm for the new function to implement with @Anais-bitmark and @moskovich. 

- [ ] When a user accepts the postcard, we need to have a push notification to notify to all users holding the postcard.

**Comment by PhucDuongBitmark** [comment]
@longbmk please check this bug, seem like that's fixed

**Comment by lemonlatte** [comment]
I think this is also solved. cc @longbmk

**Comment by longbmk** [comment]
Thank you Jim,

This bug is fixed.

**Comment by longbmk** [comment]
@lemonlatte please log work for this. :)

**Comment by lemonlatte** [comment]
no work for this in this cycle. it probably solved by features in previous cycles.
