### ISSUE TITLE
Postcard - Sometime, the Au app always ask user to paste the copy text when opening the postcard

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2630]
Steps:
1. Copy any text from Mac machine
2. Open the Postcard in the iPhone that have the same icloud with Mac
3. Observe the copy message

Observed result:
There is a popup to ask user paste the copy text although we don't have any textbox to paste

Expected result:
The AU app should not ask to paste the copy text when opening postcard 
![image](https://user-images.githubusercontent.com/109057362/235877708-f59c8864-493d-4ae7-9d9c-1f459cc02477.png)

**Comment by longbmk** [comment]
It seems the function handle deeplink has problem. I open the WC from Opensea by manually link "autonomy://wc?uri=..." also show this message in Postcard build. The production does not happen it.

**Comment by hvthhien** [comment]
It happens in AppCenter only since missing the branch key configs.

**Comment by longbmk** [comment]
Basing on the comment from Hien, I will close this ticket
