### ISSUE TITLE
Postcard - Location text displays over the border when the location is too long in stamp screen

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2631]
The location should only show "City, Country" and we should ignore all remaining data.
![image](https://user-images.githubusercontent.com/109057362/235879094-332126d6-37e1-4784-9469-38bcf840a44f.png)

**Comment by phuocbitmark** [comment]
@Anais-bitmark 
![image](https://user-images.githubusercontent.com/110799144/236429238-d3d80d2f-4c3f-46d3-bf15-d36575e8ef1b.png)

**Comment by phuocbitmark** [comment]
@Anais-bitmark could this work? (only in design stamp page, it doesn't affect later images)

**Comment by phuocbitmark** [comment]
[0.25 unit] truncate location text
