### ISSUE TITLE
Indexer does not update the balance when user sends/transfers a NFT to another address

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2633]
This issue happens in both case transfer token and accept the offer in Opensea.

Steps:
1. Make sure user has at least 1 NFT in the collection
2. Send the NFT to another address
3. Check the indexer from source address and destination address

Observed result:
Balance of the source address still show 1 although user sent the NFT to another address.
Balance of the destination address still not contain the new NFT

Expected result:
The NFT should update for both source address and destination address

https://etherscan.io/tx/0xb96fdd78252de3e145e18c704864bbe5a219101a009e1956ea53b185d3969f6f

https://indexer.test.autonomy.io/v2/nft?owner=0x49891bFFfe8c573dc969adA7A9E8645A35ceaC92&size=1009&offset=0

![image](https://user-images.githubusercontent.com/109057362/237048011-e73601cc-5105-4849-9092-44b21f16d880.png)

**Comment by lemonlatte** [comment]
I think this should be solved.
Can we validate it again? @longbmk

**Comment by longbmk** [comment]
This bug is fixed. Thank you Jim

**Comment by longbmk** [comment]
@lemonlatte please log work for this.

**Comment by lemonlatte** [comment]
no work for this in this cycle. it probably solved by features in previous cycles.

**Comment by longbmk** [comment]
Hi @lemonlatte This bug back to happens when transfer a NFT to another address. Can you please help to fix it? Thank you
