### ISSUE TITLE
Postcard - The background of Postcard still display although user clicked on the stamp to view stamp detail

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2635]
Please see the video for more detail.
https://user-images.githubusercontent.com/109057362/235891813-7902a01a-0d1e-45ff-8133-711a1d574d8a.MP4

**Comment by anhthuqs99** [comment]
[0.25 units] - update the artwork background & fix the broken metadata when viewing stamp

**Comment by longbmk** [comment]
This bug no longer happens
