### ISSUE TITLE
Postcard - Header of Postcard is truncated when it is too long

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2640]
1. Accept a postcard
2. Open the Postcard detail
3. Observe the postcard header

Observed result:
The postcard header is truncated.

Expected result:
The full name of the postcard should load in postcard header
![image](https://user-images.githubusercontent.com/109057362/236096656-604cbd89-801a-4f15-9a7e-683025147fcc.png)

**Comment by ppupha** [comment]
[0.25 unit] fix bug: make title display in 2 lines
