### ISSUE TITLE
Sometime, the Stamp cannot display in preview screen after user sign the signature

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2641]
Steps:
1. Stamp a postcard
2. Sign a signature
3. Observe the Preview screen

Observed result:
Sometimes, the stamp cannot display in preview screen

**Comment by ppupha** [comment]
[0.5 unit] check software artwork and fix bug

**Comment by longbmk** [comment]
[0.25 unit] This issue no longer happens
