### ISSUE TITLE
Sometimes, the "Already delivered" message still displays although user has not accept the postcard

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2642]
1. Stamp a postcard
2. Share the postcard to another user
3. Accept the postcard.

Observed result:
Sometimes, the "Already delivered" message still displays although user has not accept the postcard

Expected result:
The postcard should be accept success.
![image](https://user-images.githubusercontent.com/109057362/236147740-05a9c9e6-104e-4146-b0a4-4635ef0a2485.png)

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by ppupha** [comment]
[0.5 unit] investigate and fix bug
