### ISSUE TITLE
Postcard - Sometime, AU app show "Weak GPS..." message instead of load correct GPS signal

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2645]
Sometime, AU app show "Weak GPS..." message instead of load correct GPS signal. It make user very confuse on it. 

Please double check with Backend to make sure the API not timeout when calling @ppupha

**Comment by longbmk** [comment]
This issue no longer happens when change timeout to 5s

**Comment by ppupha** [comment]
[0.25 unit] check and fix bug
