### ISSUE TITLE
Postcard - Traveling data cannot load success when opening a postcard has full 15 stamps

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2646]
Please see the video for more detail.
https://user-images.githubusercontent.com/109057362/236149978-21dd2298-edef-4d0c-beaa-54c10c4a0da3.MP4

**Comment by phuocbitmark** [comment]
[0.5 unit] fix load location

**Comment by longbmk** [comment]
This issue no longer happens
