### ISSUE TITLE
There are some addresses in provenance do not load the TNS/ENS

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2648]
There are some addresses in provenance do not load the TNS/ENS. We need to review code to handle load TNS/ENS for all location we have address (artist, provenance, collector)

**Comment by ppupha** [comment]
Checked:
- Artwork detail:
    - [x] Artist Name
    - [x] Provenance
- Discovery Preview + Detail
    - [x] Artist Name
    - [x] Recipient 
- Postcard detail
    - [x] Artist Name
    - [x] Creators  
- Receive Postcard
    - [x] Artist Name 
- Send Artwork
    - [x] Artist Name 
-
