### ISSUE TITLE
Postcard - Sometimes, Postcard need more than 5 minutes to update data

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2651]
Sometimes, Postcard need more than 5 minutes to update data. It is too slow. We need to fix it @ppupha. I discussed with Jim and 
he said it is from FE.
![image](https://user-images.githubusercontent.com/109057362/236167884-2b9000fe-9e06-4e40-8e50-6e305bee9ca5.png)

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by ppupha** [comment]
[0.5 unit] fix bugs
