### ISSUE TITLE
All sections Metadata, Token Ownership, Rights should be collapsed by default when opening the artwork detail screen

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2654]
Currently, the artwork expands all section. It make the view is not good. We should make it collapse by default. Basing on the comment in here.
https://bitmark.slack.com/archives/C034EPS6CLS/p1683254274685869
![image](https://user-images.githubusercontent.com/109057362/236367644-5ba4f3d5-12ae-4fac-87cf-f144a77e9db0.png)

**Comment by phuocbitmark** [comment]
@longbmk this has been fixed on main, and it will be applied for develop and interactive postcard later (when we merge them)
