### ISSUE TITLE
Restored account does not show the addresses although the artwork still show correctly collection after user restore wallet successful

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2656]
1. Restore Autonomy with the 2nd wallet has artworks.
2. Observe the collection
3. Observe the address of 1st wallet and 2nd wallet

Observed result:
The primary wallet shows the correct addresses but the 2nd wallet is missing addresses although its artworks show correct

Expected result:
All wallets should show correct addresses after restoring.

 Note: This case can happen when the app has very old data before we apply the correct migration.
https://user-images.githubusercontent.com/109057362/236728899-35bd4b4f-140b-44c0-8615-c57d91161975.mp4

**Comment by phuocbitmark** [comment]
@longbmk please recheck this
