### ISSUE TITLE
Postcard - Accept screen does not filter out all linked accounts. It should show only full accounts

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2658]
![IMG_1C9293A19AFB-1](https://user-images.githubusercontent.com/109057362/236754001-f28b4ea7-ede4-4895-a31b-e6c51055a5d4.jpeg)

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by ppupha** [comment]
[0.25 unit] fix bug
