### ISSUE TITLE
Postcard - TNS/ENS does not apply for Artists data after accept the postcard

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2664]
![IMG_1D838D91DA33-1](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/339ffec9-d560-456c-a8d8-8a6c9f3fa42e)

**Comment by longbmk** [comment]
This issue still happens. Please help to double check it @ppupha.

![Image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/79208137-41ce-456f-b3c5-bd2d886b0b8e)

**Comment by longbmk** [comment]
TNS applied to Artist

![Image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/2f97ace9-4ab1-4ed4-9743-bf9c692976df)

**Comment by ppupha** [comment]
[0.25 unit] check bugs
