### ISSUE TITLE
Postcard - Android only - User is able to fake GPS to travel the postcard although just be in 1 location

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2674]
1. Use android phone to fake GPS
2. Open Autonomy and accept 1 postcard
3. Observe the location traveling

Observed result:
Traveling is normal like user travel and accept in another place

Expected result:
The fake GPS should be dectect

**Comment by ppupha** [comment]
[0.25 unit] check and simple UI for fake GPS case

**Comment by Anais-bitmark** [comment]
@longbmk @ppupha 
Is this message enough?
Basically it would pop-up when user tries to accept a postcard or tries to stamp the postcard while faking GPS location.
These are the two steps where we are recording the location, right?

[Figma](https://www.figma.com/file/2BKMMOodYKYD4jnml84Uab/Au-bug_2674%3A-Postcard---Android---User-is-able-to-fake-GPS-to-travel-the-postcard?type=design&node-id=0%3A1&t=4p3INg8x8FLnMadl-1)

<img width="455" alt="Capture d’écran 2023-05-15 à 15 22 31" src="https://github.com/bitmark-inc/autonomy-apps/assets/61187455/0dee6eca-a062-49b7-a2f1-689d947fa7a0">

**Comment by longbmk** [comment]
[0.1 unit] This bug is fixed

![Image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/218eacbf-cf50-44a0-8b3d-cc88fffef119)
