### ISSUE TITLE
Missing the warning screen for backing up cloud when user by pass onboarding by scan QR code airdrop/irl by Camera app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2675]
This is dangerous IMO, we are shortening the onboarding for a better user experience starting their journey with Web3 and Autonomy. But we can compromise the security.
When bypassing the backup screen:
- [ ] if cloud is enable we auto backup and that’s fine.
- [ ] if cloud is OFF we should show a warning message once onboard. Could be a tip card? But user can’t guess what he supposes to do to guarantee the recovery of his wallet.
We have an improvement for that that we had to postpone, but maybe we should at least show a tip card on collection if we have bypassed the backup screen and cloud is turn OFF. I would consider this a bug.

**Comment by Anais-bitmark** [comment]
@phuocbitmark 
[Figma](https://www.figma.com/file/iRxeEZGZLTMRph4nSHSiLj/Au-bug_2675%3A-Missing-the-warning-screen-for-backing-up-cloud-when-user-by-pass-onboarding-by(...)?type=design&node-id=0%3A1&t=Ctlg6rmLA9uqECEU-1)
[0.25 unit] UI

<img width="919" alt="Capture d’écran 2023-05-15 à 15 59 18" src="https://github.com/bitmark-inc/autonomy-apps/assets/61187455/7f6a42f0-d03d-4778-9930-e4762315d41c">

**Comment by phuocbitmark** [comment]
Currently, i repeat this message each 7 days if user turn it off but doesn't enable back up. will that interval time works?

**Comment by phuocbitmark** [comment]
@Anais-bitmark it's on

**Comment by longbmk** [comment]
The Tipcard showed in AU when update is disabled in 7 days
