### ISSUE TITLE
Playlist does not affect to hide its artwork when user hide the artwork in collection

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2676]
Steps:
1. Add some artwork to a playlist
2. Hide 1st artwork of the playlist in Collection
3. Observe the thumbnail and the 1st artwork in the playlist.

Observed result:
Playlist has not updated the thumbnail and the hidden artwork.

Expected result:
- [ ] But if I hide my address and NFTs it would be good to be able to update playlists too.
- [ ] Either switching the thumbnail for one that is not hidden or if all NFTs in the playlist are hidden,I shouldn’t see the playlist

**Comment by phuocbitmark** [comment]
@longbmk do we hide the playlist if all of its artworks are hidden

**Comment by phuocbitmark** [comment]
update thumbnail fail is an already known bug and will be fix in another story.

**Comment by phuocbitmark** [comment]
[1 unit] create service, update dao, refactor code, update tokens in playlist

**Comment by longbmk** [comment]
This issue no longer happens
