### ISSUE TITLE
User still need to enter amount to transfer although owned just 1 edition for 1155 token

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2677]
1. User has own 1 edition of 1155 token
2. Navigate to transfer artwork page
3. Observe the amount of send artwork

Observed result:
The amount field still needs to enter amount although it is 1

Expected result:
- [ ] If user has 1 edition of 1155 token. It should auto fill 1
- [ ] If user has many edition of 1155 token. I should not fill the amount like current design

**Comment by longbmk** [comment]
This issue no longer happens

**Comment by phuocbitmark** [comment]
[0.25 unit] fix this and [#2689](https://github.com/bitmark-inc/autonomy-apps/issues/2689)
