### ISSUE TITLE
User is still able to restore an account that has already existed in Autonomy app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#268]
User is still able to restore an account that has already existed in Autonomy app. It should show "Your account has already existed and link to account xxx".

Steps:
1. Open the default account in Autonomy
2. Copy the Backup seeds
3. import the seeds to restore data
4. Back to Settings page
5. Observe the Account list

Observed result:
There is a new restored from seeds account displays in Accounts List. This is duplicated with default account.

Expected result:
The message "Your account has already existed and link to account xxx" displays

https://user-images.githubusercontent.com/109057362/180939740-47821614-7129-4b6a-b9b3-71a050b7426c.MOV

**Comment by hungqd** [comment]
Hi a @longbmk, since user import the full account (not linked account), so I suggest that the message title should be "Already Imported" and message content is "You’ve already imported this account to Autonomy.". Is it ok?

**Comment by caseyalt** [comment]
@hungqd — this sounds good to me.
