### ISSUE TITLE
Missing address of a wallet when switching from testnet app to mainnet app and vice versa

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2680]
1. Create some wallet in testnet app.
2. Remove app and install mainnet app (appcenter mainnet)
3. Open the wallet and observe the address

Observed result:
There are some wallet is missing address

Expected result:
We should generate address when scanning wallets and see it missing address.

**Comment by phuocbitmark** [comment]
[0.25 unit] add address if default wallet has none during GetCategorizedAccountsEvent

**Comment by longbmk** [comment]
This bug still need to fix to all addresses instead of default addresses of the wallet
