### ISSUE TITLE
Postcard - There are some displayed issue for Postcard preview in Postcard detail page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2681]
- [x] There is a redundant white vertical line on the left of artwork preview 
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/b5929322-51c8-4aea-a056-b7e70555f276

- [x] There are 2 black lines on top and bottom of a blank artwork preview
![IMG_0938](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/d4802dfe-e293-4701-aa38-548c0683f679)

**Comment by ppupha** [comment]
[0.25 unit] fix bugs

**Comment by longbmk** [comment]
[0.25 unit] This issue no longer happens
