### ISSUE TITLE
[iOS][Keychain]The backup keys on iCloud cannot be restored when signing in with Apple account on another device 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#27]
**Step to reproduce:**
The 1st iphone:
1. Install Autonomy app
2. Create /import full account
3. Back up data with Apple account ID A

**The 2nd device:**
1. Install Autonomy app
2. Create /import full account
3. Login with the same Apple account ID A (device 1st)
4. Check if the Keys will be sync across devices or not?
5. Uninstall App
6. Reinstall App - Restore 
7. Check if the Keys will sync across devices or not?

===> The Keys have been creates in the 1st device can not sync across the 2nd device

**Information:**
Build: 0.26.7 (34) (App Center) Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)

**Comment by NekhDRej** [comment]
The issue is fixed

Environment:
iOS build (App center): 0.30.0 (67)
iPhone 12\iOS 15.5
