### ISSUE TITLE
Postcard doesn’t follow the location settings of the user. People in the US see distance in KM instead of Miles

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2711]
1. Claim and stamp a postcard
2. Share the postcard to US user
3. Observe the postcard in US

Observed result:
The Postcard traveling displays in KM instead of Miles

Expected result:
The Postcard traveling should apply the setting in device to show KM/Miles in AU app for Postcard traveling

**Comment by longbmk** [comment]
This bug still happens. I am in Vietnam but I see the distance is miles instead of KM

![Image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/deb77c37-624b-436e-a2e5-7bb498e0c41a)

**Comment by phuocbitmark** [comment]
@longbmk i think @ppupha fixed it
