### ISSUE TITLE
Postcard - Chat form of the appropriate Postcard does not open when user opening the Push notification from a postcard message

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2718]
Steps:
1. User accept 1 postcard into 2 devices
2. Enable Push notification for these 2 devices
3. Send a message from device A to device B
4. Open the push notification from device B
5. Observe the return page

Observed result:
The Autonomy app opens

Expected result:
The Chat form of the appropriate Postcard display

**Comment by longbmk** [comment]
This issue is fixed

**Comment by ppupha** [comment]
[0.5 unit] bug fixing
