### ISSUE TITLE
Postcard - There are some UI issue about postcard feedback from Anais

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2731]
Please see the figma file for more details.
https://www.figma.com/file/9RMgYpFzyl2kRczzLMfPq5/Au_XXXX%3A-MoMA-Postcard-UI-updates?type=design&node-id=312-13133&t=nhSeAxz8EBsBY5bo-0

**Comment by ppupha** [comment]
[0.5 unit] fix UI and pop-up postcard updates
