### ISSUE TITLE
Au Client app follows invalid address, so it make the server returns wrong feed event

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2737]
These are logs from server.
 time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow="Autonomy Dev" user="did:key:zQ3shN4wPPztbf6wJG1okf2Xqu9K1HAL4Xbnx6F │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow="Autonomy Dev" user="did:key:zQ3shN4wPPztbf6wJG1okf2Xqu9K1HAL4Xbnx6F │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow=KT1GtbuswcNMGhHF2TSuH1Yfaqn16do8Qtva user="did:key:zQ3shN4wPPztbf6wJ │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow=KT1GtbuswcNMGhHF2TSuH1Yfaqn16do8Qtva user="did:key:zQ3shN4wPPztbf6wJ │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow="Autonomy Dev" user="did:key:zQ3shN4wPPztbf6wJG1okf2Xqu9K1HAL4Xbnx6F │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow=b4Te8dMMNsRyv1utUAyqkeuywiE8FMuR4AmGCh8vuMMK9mg71B user="did:key:zQ3 │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow="Autonomy Dev" user="did:key:zQ3shN4wPPztbf6wJG1okf2Xqu9K1HAL4Xbnx6F │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow="Autonomy Dev" user="did:key:zQ3shN4wPPztbf6wJG1okf2Xqu9K1HAL4Xbnx6F │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow="Autonomy Dev" user="did:key:zQ3shN4wPPztbf6wJG1okf2Xqu9K1HAL4Xbnx6F │
│ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow=bMwqc3H7QH3FwxHonKFzaWGAgUrNtN2Af2FDUuzRFD2H8yHQJ6 user="did:key:zQ3

**Comment by phuocbitmark** [comment]
@longbmk  │ time="2023-06-12T06:39:22Z" level=error msg="attempt to follow invalid address" follow=bMwqc3H7QH3FwxHonKFzaWGAgUrNtN2Af2FDUuzRFD2H8yHQJ6 user="did🔑zQ3 : this is a artist bitmark id for feral file token. this is a legacy of FF email-based account and will be fixed when FF upgrades to FF 2.0

**Comment by phuocbitmark** [comment]
this was fixed in Manually follow story. Please check again

**Comment by longbmk** [comment]
Feed no longer displays in our app. let me close this
