### ISSUE TITLE
number of Feed is not consitent with the number of Discover loaded art (e.g. Feed show 16 but the real loads 7 art)

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2741]
1. Please forget I exist then load the Feed tab\
2. Compare the number of feed and number of loaded artworks

Observed result:
The feed shows 16-18 but the real artworks load 7

Expected result:
We are facing a rate limit in OpenSea and the artwork in Discover. So the artwork really load 7 arts. We need to update the number notification on top to the really loading artwork.

https://github.com/bitmark-inc/autonomy-apps/assets/109057362/ffa1fc5e-836c-48ef-9f08-745134591e2d

**Comment by longbmk** [comment]
This bug no longer happens

**Comment by ppupha** [comment]
[0.5 unit] fix duplicated feeds
