### ISSUE TITLE
Scanning screen freezes in white background after scanning a QR to connect to a canvas app at the 1st time after installing AU app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2753]
Steps:
1. Install the AU app
2. Scan the QR code to connect to Canvas app
3. Observe the Camera screen

Observed result:
Scan screen display in white background and user cannot connect to Canvas app. When closing and reopen camera again, the connection is ok. This issue just happens at the 1st time after installing the app

Expected result:
The Camera should work and make the connection successful at the 1st time after installing the app
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/1962965a-2a9b-47a4-b807-3b24798918ff

**Comment by ppupha** [comment]
[0.5 unit] fix and check bug
