### ISSUE TITLE
Postcard - Sometimes, the software artwork does not update stamp when user keep the postcard detail screen and waiting for blockchain confirm

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2768]
Steps:
1. Claim and stamp a postcard
2. Open and keep the postcard to have "Confirming in Blockchain" screen
3. Wait for the postcard loaded.

Observer result:
Sometime, the software artwork does not reload to fill the stamp

Expected result:
We should to fill local first before all loading success
![image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/ddf56485-4493-4215-b2e4-619d0d4ee2c8)

**Comment by ppupha** [comment]
We discussed here: https://bitmark.slack.com/archives/C034EPS6CLS/p1691985990371929
