### ISSUE TITLE
WC2.0 - Nothing happens when connect by WC2.0 in the mobile browser to the Autonomy app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2776]
Steps:
1. Open the Autonomy app
2. Open Safari and navigate to Opensea
3. Connect Opensea by WC2.0
4. Open the Autonomy app

Observed result:
Nothing happens after opening the Autonomy app

Expected result:
AU app should establish a connection to WC2.0 to OS.
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/5307bf93-04c2-48e4-aa16-b1fb111a3bd1

**Comment by phuocbitmark** [comment]
[0.5 unit] debug

**Comment by longbmk** [comment]
This bug is fixed. Thank you Phuoc
