### ISSUE TITLE
WC2.0 - There are some specific user cannot list/edit listing an artwork in OpenSea

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2779]
There are some specific user cannot list/edit listing an artwork in OpenSea. Please use my address to debug this, Hien.

https://github.com/bitmark-inc/autonomy-apps/assets/109057362/3d807948-aa57-4554-927d-b894fcd674b4

**Comment by hvthhien** [comment]
[0.25 units] debugs + fix eip55 issue.

**Comment by longbmk** [comment]
This bug is fixed.
