### ISSUE TITLE
Playlist does not remove after removing/sending the last artwork to another address out of the Autonomy app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2782]
Steps:
1. Add an artwork to playlist
2. Keep 1 artwork in playlist and remove all artworks
3. Transfer the remaining artwork to another address outside of the Autonomy app
4. Observe the Playlist

Observed result:
The playlist is shown with no artwork in this

Expected result:
The playlist should be remove if having no any artwork after removing/Sending the last artwork
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/a0a06da1-013f-4e74-a772-82cd6019b57c

**Comment by phuocbitmark** [comment]
[0.75 unit] refresh playlist, handle recently sent token
