### ISSUE TITLE
Selected address is not deselected after clicking on it in Connection page

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2798]
1. Make sure user has many Ethereum addresses in AU app
2. Do the WalletConnect
3. Select an address
4. Click on the selected address

Observed result:
The selected address still be selected

Expected result:
- [ ] The selected address is deselected after clicking on it
- [ ] The Confirm button should be disabled after deselecting the address

**Comment by phuocbitmark** [comment]
@bencebitmark this is easy to implement. However, i don't see any value to implement this, user either exits or selects the right address to continue. And we needs to add a bunch of codes in a lot of places in our app (everywhere that need to select addresses), which make our app worse cause as Sean said less code is better.

**Comment by bencebitmark** [comment]
@phuocbitmark let's add this to backlog.

**Comment by bencebitmark** [comment]
the value is that it's not obvious you can select the correct address to deselect, especially that we have two things to select sometimes, both ETH and TEZ.

**Comment by phuocbitmark** [comment]
so we should make it's obvious that they can switch address by select another. the point of not allow them to deselect is to remind that in each category (tez, or eth), you should select one and only one address, you can't select none, neither multiple.
we could separate list of ETH and TEZ when it has both

**Comment by bencebitmark** [comment]
> we could separate list of ETH and TEZ when it has both

i like this. i think this story would need more thought / value assessment in coming preps. perhaps a UI improvement. let's do it at a later cycle.
