### ISSUE TITLE
Hidden address still show in Select Address screen for AU connect/WC/Beacon/Airdrop

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2809]
1. Add more than 1 address to AU app
2. Hide 1 address
3. Do the airdrop
4. Obsere the Addresses in Select Address screen

Observed result:
The hidden address still shows in Select Address screen

Expected result:
The hidden address should not show in Select Address screen

[Figma](https://www.figma.com/file/5jT9uK4chsQogxvc7S3FWd/Au_2809-%E2%80%93-Select-hidden-addresses?type=design&node-id=0%3A1&mode=design&t=0l1jUB8LVXS8yiGe-1)

**Comment by longbmk** [comment]
Let's finish the confirmation in feedback channel then we will apply the fix. Thank you Phuoc

**Comment by phuocbitmark** [comment]
[0.75 unit] separate showed addresses and hidden addresses
