### ISSUE TITLE
USD amount auto change from 1 to 10 $USD when changing currency and type 1 into amount textbox

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2813]
Steps:
1. Navigate to Send ETH/XTZ screen
2. Click on amount textbox
3. Tap on ETH/TEZ icon
4. Tap on USD icon
5. Enter value 1 for Amount
6. Observe the amount after entering

Observed result:
Amount auto change to 10 $USD

Expected result:
Amount should keep 1 when enter 1.
If the value is empty, we shouldn't convert (just update the placeholder).
https://github.com/bitmark-inc/autonomy/issues/2072#issuecomment-1643142773

**Comment by phuocbitmark** [comment]
[0.25 unit] not convert if amount = 0; USD place holder; textfield cursor
