### ISSUE TITLE
The new added address does not show in Addreses page if user restore the AU app without any address.

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2816]
Steps:
1. Install AU app
2. remove all addresses
3. Backup AU app
4. Delete AU app
5. Reinstall app
6. Add a new address to AU
7. Observe the new address in Addresses page

Observed result:
There is no any address in Addresses page. Kill app and open again will show the added address.

Expected result:
The new added address displays in Addresses page.

Note:
This issue also happens after remove all address and then adding just 1 Ethereum address or 1 Tezos address

**Comment by phuocbitmark** [comment]
[0.25 unit] investigate, fix

**Comment by longbmk** [comment]
This bug is fixed
