### ISSUE TITLE
Auto onboarding cannot make the connection to AU connect/WC in case "Create a new address"

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2817]
1. Make sure user is on a "Create a new address" screen
2. Scan AU connect/WC 2.0 by Camera app
3. Open the AU app

Observed result:
Cannot make the connection to FF by AU connect/WC

Expected result:
Connection is established. We should fix for 2 below cases:
- [x] Auto onboarding for case "Create new address" in AU Connect --> failed. This is not from this ticket. Production also happens. I think it happens when Addresses are not load so it make we does not have address to do the connection
- [x] Auto onboarding for case "Create new address" in WC

**Comment by longbmk** [comment]
This bug no longer happens

**Comment by ppupha** [comment]
[0.5 unit] bug fixing
