### ISSUE TITLE
Tizen canvas app cannot play software artwork and SVG artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2822]
- [ ] Please use this token to debug casting in the Canvas app for Software artwork. tez-KT1Lak6VLc3k33EqvpTBfpXspoRAKUa4ycVJ-1690428138387.

- [ ] This is for SVG artwork: 
tez-KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi-1213128

**Comment by ppupha** [comment]
Note: tez-KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi-1213128 is a software artwork.

**Comment by ppupha** [comment]
Fixed: Tizen can play light software artwork.

Support webview https://github.com/bitmark-inc/autonomy-canvas-tizen/pull/4#event-10126498139

**Comment by ppupha** [comment]
[1 unit] support webview
