### ISSUE TITLE
AU connect/WC2.0 does not make the connect after auto onboarding in case "Create a new address"

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2832]
Steps:
1. User is in "Create a new address" screen
2. Scan a QR code for AU Connect/WC2.0 by Camera app of the phone
3. Observe the AU app

Observed result:
Missing the connection screen for AU connect/WC2.0 after AU app does auto onboarding

Expected result:
Connection screen should show after AU app does auto onboarding by scanning AU connect/WC2.0
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/bfa7d363-f46e-4949-86d6-79e48d392ce3

**Comment by phuocbitmark** [comment]
@longbmk couldn't recreate bug, could you recheck
