### ISSUE TITLE
Editorial tab does not load when clicking on it at the first time loading AU app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2836]
1. Open AU app
2. Click on Editorial tab

Observed result:
Nothing happens when clicking on Editorial tab

Expected result:
Editorial tab loads when clicking on at the first time.
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/d1a38b27-93a4-4267-8cc4-bfba11bb14f8

**Comment by ppupha** [comment]
We will remove editorial, so, we can close this ticket.
