### ISSUE TITLE
Postcard artwork still displays in Discovery

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2850]
For now, when artist mint a Postcard, it displays in Discovery of the follower. We should temporary hide it in Discovery. Please kindly help us to fix it Mr HXW. Thank you

**Comment by hxw** [comment]
This involves a new database table `eventfeed.ignores` and used as follows:

Block examples:
```
INSERT INTO  eventfeed.ignores(chain,contract) VALUES ('ethereum', '0x1278936....');
INSERT INTO  eventfeed.ignores(chain,contract) VALUES ('tezos', 'KT1ioerjbd7i....');
```

To remove a block, just delete:
```
DELETE FROM eventfeed.ignores WHERE chain='ethereum' AND contract='0x1335....';
```

The block/unblock will occur immediately and will also apply to any events already on the server's internal queue.

**Comment by hxw** [comment]
This code is deployed to production
