### ISSUE TITLE
[Change request] There is a redundant step to show "Connected" when scanning to connect the Canvas app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2857]
After scanning the QR code to connect the Canvas app, the Connected popup displays. We need to remove it and keep showing the popup list of devices.
![image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/09e11166-f515-40bf-af0a-67aff64aa4df)

**Comment by phuocbitmark** [comment]
@longbmk in list device pop up, there's buttons for casting. Do we hide or disable it.
Or show we need a new UI for it
cc @bencebitmark

**Comment by bencebitmark** [comment]
@phuocbitmark no need to show this popup. no new ui, just hide.

**Comment by phuocbitmark** [comment]
@bencebitmark it's just added recently because someone complained that after scan canvas qr code, it just pops out and nothing happen. If we don't show any thing, should we allow to scan there?

**Comment by bencebitmark** [comment]
`If we don't show any thing, should we allow to scan there?`

Sorry, not sure I understand. What do you mean here @phuocbitmark?

**Comment by phuocbitmark** [comment]
@phuocbitmark i mean that we can show error if user scan canvas qr code using global scanner (the one above help, settings)

**Comment by bencebitmark** [comment]
@phuocbitmark i'd keep the current flow, just hiding the popup Long posted above. no other change.

**Comment by longbmk** [comment]
@bencebitmark @phuocbitmark I think we hide the Connected popup but w neeed to handle other cases:
- [ ] When user scans by "Settings->scan", it still need to show Connected popup
- [ ] When user scan in "Add new canvas" popup, it does not show Connected popup but we still need to show "Canvas popup to cast. If we hide, user still need to click on "Cast" icon again. It's worse than show "Connected" popup.

**Comment by phuocbitmark** [comment]
@longbmk i don't understand why does user still need to click on "Cast" icon again. after scan qr, it pop to Connect to canvas dialog.
and  When user scans by "Settings->scan", it still need to show Connected popup -> do you want to revert what we did?

**Comment by bencebitmark** [comment]
@longbmk i think both cases above we can hide the popup in the app, since the display you're connecting to already gives you feedback that you connected.

<img width="785" alt="Screenshot 2023-09-11 at 09 14 42" src="https://github.com/bitmark-inc/autonomy-apps/assets/128143921/c86b2f32-f3de-4794-89e4-1e1dc0633408">

**Comment by longbmk** [comment]
Ok. Let me mark this ticket to be Done
