### ISSUE TITLE
Done button at the bottom of playlist display overlap the artworks at the bottom

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2858]
Please update base on the design.
https://www.figma.com/file/NsMDYhSmBZe5TO9VPoJ1tB/Autonomy-%2F-Bug-%2F-Larger-padding-below-last-artwork-row?type=design&node-id=0%3A1&mode=design&t=tIVDobAhDV60U7SH-1

![image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/0f156bb6-98c0-4f2e-b585-102d6ff67191)

**Comment by phuocbitmark** [comment]
@bencebitmark do we add that blank space when creating new playlist or add new token to playlist (same screen)

**Comment by phuocbitmark** [comment]
[0.25 unit] added 3 cells to the grid in create new/edit playlist page

**Comment by bencebitmark** [comment]
@phuocbitmark yes, please add to all instances with the same / similar UI. i'm also addressing it this cycle with the design.
