### ISSUE TITLE
Sometimes, Indexer cannot sync data stamp from blockchain although stamp location stored into blockchain

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2862]
Steps:
1. Claim a postcard
2. Share a postcard to another user
3. Another user accepts the postcard
4. Open the postcard detail and wait for the stamp confirmed

Observed result:
Sometimes, the stamp cannot show in software artwork. 
Another issue is that client is basing on 2 APIs, 1 from TZKT and 1 in indexer. It can make confuse in client waiting time.

Expected result:
- [ ] Server needs to update Stamp by delay some seconds to watch event
- [ ] Client app should follow just indexer instead of both indexer and tzkt
https://raw.githubusercontent.com/bitmark-inc/au-support-board/main/attachments/did%3Akey%3AzQ3shiPEMX2GejD3nUBLmKN4KJ56VQqdknPYDfj16eFTW2LS6/7f6810490c471919659fa5f7747b667eab0fe6348b225f01553fa6c813516f64.png?token=GHSAT0AAAAAAB2PSS634OX6ZRMIDI7QJ6BOZG4STTQ

https://raw.githubusercontent.com/bitmark-inc/au-support-board/main/attachments/did%3Akey%3AzQ3shiPEMX2GejD3nUBLmKN4KJ56VQqdknPYDfj16eFTW2LS6/c21b8f71fc6654c6da4bb83dc9b70d8332db5d0bb2051fd6ad7e0d0f37e68a2c.png?token=GHSAT0AAAAAAB2PSS625MR4QCK4UH54RAOEZG4STUA

https://raw.githubusercontent.com/bitmark-inc/au-support-board/main/attachments/did%3Akey%3AzQ3shiPEMX2GejD3nUBLmKN4KJ56VQqdknPYDfj16eFTW2LS6/d7eabef1774e43a7203db2f8871fea57b34ea6af64d174a796631d3b5ca8745e.png?token=GHSAT0AAAAAAB2PSS62QU77TBFCI42X6SQMZG4STVA

**Comment by lemonlatte** [comment]
Add the defer processing for event processor : https://github.com/bitmark-inc/nft-indexer/pull/213
