### ISSUE TITLE
Postcard - Postcard detail does not open when opening the Postcard traveling push notification

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2874]
1. Claim a postcard
2. Share the postcard to another device
3. Accept the postcard
4. Wait for the push notification to notify postcard traveling in device 1
5. Click on the notification

Observed result:
Postcard detail open but does not refresh

Expected result:
Postcard detail refresh after opening by clicking on the push notification

**Comment by ppupha** [comment]
This issue was fixed iin https://github.com/bitmark-inc/autonomy-client/pull/1212

**Comment by longbmk** [comment]
This still need Backend to check. Please help to apply it @lemonlatte @hvthhien. Thank you
