### ISSUE TITLE
Sometimes, the Discover tab header disappears when navigating to Discover tab

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2875]
This is really hard to reproduce. Sometimes, it happens. Please help to review the code. Thank you
![image](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/2f8a4d18-5b3d-42e7-b1b7-45a1fd11d5d7)

**Comment by phuocbitmark** [comment]
we no longer have tab bar after remove editorial

**Comment by ppupha** [comment]
It might be problem while getting feed. It can make the discover screen empty after remove editorial.
