### ISSUE TITLE
Software artwork wait for loading all stamps instead of async to load stamps that available to load

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2876]
1. Share and stamp the postcard many times
2. Load the postcard detail

Observed result:
Postcard load is too long.

Expected result:
It should be async to load stamps in a postcard.

**Comment by anhthuqs99** [comment]
[0.25 units] - asynchronous load artwork stamps

**Comment by longbmk** [comment]
This issue no longer happens, but we still need to fix the footer of each stamp. It is another issue.

**Comment by anhthuqs99** [comment]
[1 unit] - fixing side effects after the change to async load artwork
  - Change to load stamp by stamp
  - get query params to synchronously load artwork & turn on flag `fullLoaded` support to take screenshots.
