### ISSUE TITLE
Missing feed event tokenID in debug logs although tokens still display in app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2877]
1. Import some addresses that have many feed event
2. View Discovery function
3. Report a debug log

Observed result:
Debug logs is missing TokenID in Feed event response

Expected result:
All tokenIDs display in debug logs to easier to trace the issue

**Comment by ppupha** [comment]
This issue was fixed in https://github.com/bitmark-inc/autonomy-client/pull/1188
