### ISSUE TITLE
Discovery is very lag when loading default feed

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2886]
Discovery is very lag when loading default feed. I think we need to debug and improve it.
https://photos.app.goo.gl/Ydv5TVkzAAnoHW5f9

**Comment by ppupha** [comment]
Discovery is lag because of this token `tez-KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE-427156`. This is a heavy software artwork. 
@hxw can you please help to replace it.
cc @bencebitmark please help to choose another artwork to replace.

**Comment by bencebitmark** [comment]
@ppupha what's the artwork title and artist?

**Comment by ppupha** [comment]
@bencebitmark it's default artwork. We choose 7 artworks and  show them if there are not any events in discover.

**Comment by bencebitmark** [comment]
> because of this token tez-KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE-427156

i meant what's the specific artwork this token is associated with?

**Comment by ppupha** [comment]
@bencebitmark This token https://www.fxhash.xyz/gentk/427156

**Comment by bencebitmark** [comment]
@ppupha @longbmk let's just remove that one artwork for now. no replacement needed, as it looks like the Discover function itself will be removed.

**Comment by ppupha** [comment]
@hxw please remove `tez-KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE-427156` from discovery.

**Comment by anhnguyenbitmark** [comment]
Closed. It's not valid any more, according the new direction here: https://github.com/bitmark-inc/autonomy/issues/2165
