### ISSUE TITLE
Follow address is not unfollowed when user remove the suggested address in Feed event

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2893]
Steps:
1. Add a custom address to follow list (e.g. vitalik.eth)
2. Wait for event sync
3. Remove the address to update unfollow event
4. Check the feed event

Observed result:
Feed event still show the artwork from removed address

Expected result:
Feed event should be update to reflect the new unfollow event
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/53529a92-d216-4d12-8961-73cbda030231

**Comment by hxw** [comment]
The original spec of the feed server was not to remove any events from unfollow requests and not to add old events when follow new address is received.
The way the app was implementing follows, on selecting the collection:
- get a list of all currently followed addresses
- unfollow all addresses in this list
- follow all addresses from current collection
As far as I can tell the app is still doing this, and still is sending invalid addresses (this very old bug is still not fixed)

If I make this change then this will cause all feeds for all users will be cleared the moment they open their collection tab.

**Comment by hxw** [comment]
Perhaps this should be a new API  and the old `DELETE /follows` just left as-is so that users who open old app version prior to updating to the fixed app do not erase their whole feed.

**Comment by phuocbitmark** [comment]
@hxw about invalid addresses, it will be fixed soon. if a invalid address found in local (len < 36, != 0x00000...) then it will query delete /follows

**Comment by hvthhien** [comment]
> The original spec of the feed server was not to remove any events from unfollow requests and not to add old events when follow new address is received. The way the app was implementing follows, on selecting the collection:
> 
> * get a list of all currently followed addresses
> * unfollow all addresses in this list
> * follow all addresses from current collection
>   As far as I can tell the app is still doing this, and still is sending invalid addresses (this very old bug is still not fixed)
> 
> If I make this change then this will cause all feeds for all users will be cleared the moment they open their collection tab.

The app flow will be changed to this:
- Follow new artists when new tokens are added to the collection.
- Unfollow an artist when the user selects to unfollow (via UI)

@hxw does it affect anything on the current implementation?

**Comment by phuocbitmark** [comment]
@hxw just start to read autonomy-event-feed, trying to learn from it, i have a question, when user unfollows an address why can't just remove events where recipient = address.

**Comment by hxw** [comment]
After looking through the code I think making v2 API is the proper solution, since v1 API is implementing the follow system as originally specified.

@longbmk Since this is essentially a new feature should the v2 follow function add back some of the currently recorded events for the address? 

However must be careful with any add, because if the APP is rapidly doing its delete and re-add of all follows then this will cause very high database load and could cause the database to run out of capacity and disconnect.

**Comment by hxw** [comment]
> @hxw just start to read autonomy-event-feed, trying to learn from it, i have a question, when user unfollows an address why can't just remove events where recipient = address.

@phuocbitmark Just to answer your question, events are shared by all users, so remove by address would remove that event for others still following that address and leave their feed corrupt (i.e., pointing at a no longer existing event).. The feed is essentially the classic database M:M intersection of users and events so has no actual data.

**Comment by longbmk** [comment]
Currently, Discovery is no longer in our app. Let me close and reopen when it backed
