### ISSUE TITLE
There are 2 onboarding postcard screens display when scanning a Postcard QR code in the slow Internet network

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2905]
Pre-condition:
1. Make sure internet network slow
2. Scan to claim a postcard

Observed result:
There are 2 onboarding postcard screens display

Expected result:
Just only 1 onboarding screen displays when claiming a postcard in slow network.

**Comment by ppupha** [comment]
this issue was fixed in https://github.com/bitmark-inc/autonomy-client/pull/1211#pullrequestreview-1612320310
