### ISSUE TITLE
AU app crashes when Signing to connect OpenSea in Safari mobile to AU in only 1 device

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2908]
Please see the video for more detail
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/be454a6a-e480-4d1a-aa2b-7498e8c4b4e4

**Comment by phuocbitmark** [comment]
[0.25 units] add ignore prefix

**Comment by longbmk** [comment]
The application still crashes when connectting in Mobile browser to AU app in the same device
