### ISSUE TITLE
MoMA Postcard improvements / Round 1

### ISSUE THREAD

**Issue by moskovich** [bitmark-inc/autonomy-apps#2909]
We need to fix:
- Address selection styling if user has multiple Tezos addresses.
- Update ‘Confirm your design’ button to ‘Finalise your stamp’
- Update 'Confirming on blockchain...' and 'Updating token...' progress indicator texts to 'Recording stamp to blockchain...'
- Add postcard title to postcard artwork page.
- Fix postcard alignment on postcard artwork page.
- For the 'Total Distance Traveled' progress indicator, only turn a progress bar block purple if a stamp has been created. For example 5 stamps = 5 progress bar blocks. (Currently # of stamps ≠ # of progress bar blocks.)

[Design](https://www.figma.com/file/e6cU7pYvmQ4H1hlFqlvqNQ/MoMA-%2F-Postcard-improvements?type=design&node-id=0%3A1&mode=design&t=itTg6kqQ20bEPYaC-1).

**Comment by longbmk** [comment]
@bencebitmark Please help to work on this for the design Bence!. Thank you
