### ISSUE TITLE
Canvas app only - There is a specific artwork displays with white background instead of black by default of artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2920]
1. This is the artwork in AU app:
![IMG_864C3287029B-1](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/1d444aa8-318e-4cc8-a3bb-5a1ac1318eee)

2. This is the artwork displayed in Canvas app
![IMG_1106](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/52f860bf-9f74-49e5-bd70-836bea1c5eae)

**Comment by phuocbitmark** [comment]
[0.5 unit] fix for model viewer in android tv, set background for tizen app
