### ISSUE TITLE
MoMA Postcard / Cancel invitation modal language and styling

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#2928]
Update language to clarify cancelling action. Update modal styling to MoMA brand.

[Design](https://www.figma.com/file/mFpe5b3LZdemMNFwQL1uDz/Autonomy-%232928-%2F-MoMA-%2F-Cancel-invitation-modal?type=design&node-id=0%3A1&mode=design&t=OmRPjYgqTT5eqPj4-1).

**Comment by ppupha** [comment]
@bencebitmark is the design final?

**Comment by bencebitmark** [comment]
@ppupha yes, the design is final.

**Comment by longbmk** [comment]
The design is applied.
