### ISSUE TITLE
New minted token image broken on the discovery feed

### ISSUE THREAD

**Issue by lemonlatte** [bitmark-inc/autonomy-apps#2947]
For some tokens, for example from fxhash, that needs to be revealed, we would not be able to get the image for displaying immediately right after the token is minted. In this case, users will possibly see the following screen.

![Screenshot_20230919-093414](https://github.com/bitmark-inc/autonomy-apps/assets/1197028/11e50ddf-9e70-48bf-9d2b-2b09d9ac53d8)

To mitigate this case, we can try to add a delay for indexing tokens in feeds, for example, 5 mins. In the most of the cases, the tokens should already be revealed or updated from the blockchain.

**Comment by lemonlatte** [comment]
@moskovich could you help to review this if you have time?

**Comment by moskovich** [comment]
Yes — great idea. I love that. Please add this as debt — ok to be critical.

**Comment by longbmk** [comment]
Discovery is no longer in our app. let me close and reopen when it backed
