### ISSUE TITLE
Enable continuity when viewing the artwork from the detail page to the preview page

### ISSUE THREAD

**Issue by anhnguyenbitmark** [bitmark-inc/autonomy-apps#2955]
### Problem
Artworks are restarted when users tap to view them from the artwork detail page.

### Goal
- Use the same controllers (or even UI views) to continue playing the artwork in the preview mode.
- Support animation if needed.

**Comment by Anais-bitmark** [comment]
@anhnguyenbitmark is this one solved?

**Comment by anhnguyenbitmark** [comment]
Not yet.

**Comment by ppupha** [comment]
Because artwork preview has been removed, we can close this issue.

**Comment by longbmk** [comment]
This fix is applied.
