### ISSUE TITLE
Postcard - Software artwork - Postcard stamp detail can scroll to 15 stamps although user just stamp some stamps (e.g. 5 stamps)

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2963]
1. Stamp 5 stamps
2. Open Software artwork
3. Scroll to the next

Observed result:
User is able to scroll to the 15th stamp although has 5 stamps.

Expected result:
User is not able to scroll to blank stamp
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/c7af9fdc-ccec-4bbf-bbb3-59212f69ee39

**Comment by longbmk** [comment]
This ticket is Done. Let's deploy to production @anhthuqs99 @lemonlatte

**Comment by anhthuqs99** [comment]
> @anhthuqs99 which commit is for this change?

This one: https://github.com/bitmark-inc/autonomy-postcard/pull/139/commits/c5ab4d1c6fb00988fe4c75656c1b0634b02deb73

**Comment by lemonlatte** [comment]
the last commit is not tested. should we include it?

**Comment by anhthuqs99** [comment]
> the last [commit](https://github.com/bitmark-inc/autonomy-postcard/commit/a824a622992006c4142fc4c7681c406ff4419e19) is not tested. should we include it?

This one I've updated when implement the [MoMA Postcard / First 15 cards webpage#2162](https://github.com/bitmark-inc/autonomy/issues/2162) for consistency showing date time. If you afraid there can be side effect I'll remove it.
I've used same function and it's work well in [this website](https://moma-first-15-dev.pages.dev/postcards)
