### ISSUE TITLE
increase speed of web postcard viewer

### ISSUE THREAD

**Issue by moskovich** [bitmark-inc/autonomy-apps#2969]
It’s taking more than a minute to load on a fast connection from California.

**Comment by ppupha** [comment]
@moskovich do you mean `web postcard viewer` is postcard software or webviewer https://viewer.autonomy.io/token/tez-KT1Rg1hhAPD8HSKaNKV6zuu7y8Zuk4QXaq2V-1692032250445?

**Comment by moskovich** [comment]
It's the entire page. Before the postcard is viewable.

**Comment by ppupha** [comment]
@moskovich can you give me the link? my postcard link is now taking about 3-4 seconds to load the token and 4-5 seconds to load the software.

**Comment by moskovich** [comment]
The link is in my first post.

**Comment by ppupha** [comment]
We use thumbnail instead of software postcard, so the speed could be faster.
[MoMA Postcard / View postcard on Autonomy web viewer](https://github.com/bitmark-inc/autonomy/issues/2168)
