### ISSUE TITLE
Artwork infor back to previous artwork instead of keep the current viewing artwork if user move artwork detail then clickon Infor icon on top left

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#297]
Steps:
1. Open the Artwork infor page
2. Click on the Artwork to view detail.
3. Swipe to move to next Artwork
4. Click on the Infor icon on top left of the Artwork
5. Observe the returned Artwork info page

Observed result:
The previous Artwork Info page displays

Expected result:
The Artwork Infor of current viewing Artwork displays.
https://user-images.githubusercontent.com/109057362/182285193-367ca521-f57d-496b-b593-9b8df8ba9567.MOV

**Comment by hungqd** [comment]
@caseyalt @Anais-bitmark , could you take a look at this bug.
We have 2 options:
1. Disable swipe function in the artwork preview page. (only when Immediate info view enabled).
2. Update artwork info view according to the current artwork (after user has swiped). 
For me, I think option 1 would be better.
How do you think? or any other ideas?
