### ISSUE TITLE
Increase speed of downloading postcard and stamp as image

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#2998]
• Downloading stamp and postcard should be near instant.

**Comment by ppupha** [comment]
Download stamp is now improved by using catch (it will be fast from the second download). For the fist time, we need to call API and wait for response.

@lemonlatte do you have any solution to improve this?

**Comment by lemonlatte** [comment]
we need to build something to make chrome as a service first. there are a lot of screenshot need to generate from the server. it almost can not instant unless the image is taking from the client. 

i think the download can be instant but the preparation can not. 

@bencebitmark what a about to design a button fade out and unlock when the stamp is ready from server.

**Comment by bencebitmark** [comment]
> download the stamp without the bottom bar
how about the entire postcard download speed? (given it includes the bottom bars.)

i wouldn't disable the download button, that could be interpreted as the function not being available currently.

idea: show 'Stamp / postcard saved.' popup instantly after pressed 'Download', even if it's not saved. by the time user switches to their photos app (1-2 seconds minimum), it will be saved by then.

**Comment by lemonlatte** [comment]
According to discussion over here: https://bitmark.slack.com/archives/C04J8DTNEM6/p1697098402474309?thread_ts=1697042628.474769&cid=C04J8DTNEM6

- We will pre-generate the stamp for downloading right after the transaction is confirmed.
- For stamps which does not have a pre-generate image, we fall back to take screenshot like before.
   - In the mean time, we will save the result of the screenshot we just take back to the db for later using.

cc @bencebitmark 

---

Just deployed this feature on dev. @longbmk  Please help to test. The post process of the stamp image is not at the same time the mobile receive a notification to stamp updated. It would take 1-2 min to process.

**Comment by lemonlatte** [comment]
Update:
- only apply to download stamp now.
- the download postcard is not using an dedicate api now. we need to create another api to support this.

**Comment by longbmk** [comment]
Development is ok. Please help us to deploy to production after we submit the application to have new API URI request, Jim.
Thank you
