### ISSUE TITLE
Display full postcard image (without the postcard being cropped) when shared on Twitter

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#3011]
**Acceptance criteria:**
• When a postcard is shared on Twitter using the Autonomy Viewer, ensure the postcard itself isn't cropped.
• Use 2:1 aspect ratio for thumbnails.
• The available black background can be cropped to a certain extent. Though a margin around the postcard should still exist.

[Design](https://www.figma.com/file/KZ76h946ZMkmZyVuFTAelB/Autonomy-%233011-%2F-MoMA-%2F-Postcard-thumbnail-for-Twitter?type=design&node-id=1%3A2&mode=design&t=dlHj3ZQT6UMo78iV-1).

**Comment by lemonlatte** [comment]
@anhthuqs99 could you have to make a new style for this?
