### ISSUE TITLE
Show postcard Artists (in Metadata) and Token Ownership section accurately.

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#3033]
**Acceptance criteria:**
• Metadata: make artist section an expandable list.
• Token ownership: turn this into an expandable list too, with the number of shares owned displayed.
• UI language changes.

[Design](https://www.figma.com/file/w9UOrE1wegauOFwzFlCz6d/Autonomy-%233033-%2F-MoMA-Postcard-%2F-Show-Token-Ownership-and-Metadata-accurately?type=design&node-id=0%3A1&mode=design&t=1NCKkk3HeVtl9sj4-1).

**Comment by longbmk** [comment]
UI still needs to update to match the design. Please update it @ppupha. Thank you
