### ISSUE TITLE
MoMA Postcard / Improvements

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#3061]
Acceptance criteria:
• Ability to send postcard right after designing.
• Various other improvements to onboarding.
• Various other improvements to postcard artwork details page.
• Announcement of postcard completion in postcard chat.

[Design](https://www.figma.com/file/MwjXZ2no4s4lALVhaNOt1I/Autonomy-%233061-%2F-MoMA-Postcard-%2F-Improvements?type=design&node-id=0%3A1&mode=design&t=S2ekuTNeFaUsb26t-1).

**Comment by longbmk** [comment]
[Bug] Postcard is hung at "Minting stamp" step if losting Internet connection in Stamping time. When user resumes, the Postcard is hung at "Minting stamp"
