### ISSUE TITLE
MoMA Postcard / Share link opens app store instead of postcard flow

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#3062]
I sent a postcard invite to Sean, and it didn't open to him in-app. 

The invite link opened the App Store page for Autonomy.

**Comment by bencebitmark** [comment]
https://github.com/bitmark-inc/autonomy-apps/assets/128143921/12f12dc0-d5ee-4d0b-9765-d25c8a7e4781

**Comment by ppupha** [comment]
It works when use camera to scan.

**Comment by ppupha** [comment]
@lemonlatte please help to check the config from branch link.

**Comment by lemonlatte** [comment]
@anhnguyenbitmark @hvthhien can you check?

**Comment by longbmk** [comment]
For this issue, it happens from BranchIO. Let's contact them for it. It seems @anhnguyenbitmark contacted @moskovich to do it.

**Comment by anhnguyenbitmark** [comment]
I submitted a question to them via their support console.

**Comment by longbmk** [comment]
Hi all,

It seems the deeplink does not work in Twitter. Maybe some social network app, OTT app wrapped our deeplink in their links, so it will not open our AU app. This is the list.
Not worked: Twitter, iMessage, Facebook.
Worked: Skype, Slack, SMS message app, Gmail.

Let's discuss for this issue and should we try a solution to prevent/fix this? @moskovich @anhnguyenbitmark @lemonlatte @hvthhien @phuocbitmark @ppupha 

Thank you

**Comment by phuocbitmark** [comment]
twitter works for me (samsung note 9), although it automatically opened production app, usually it would ask to choose among chrome, Au app prod and Au app dev

**Comment by anhnguyenbitmark** [comment]
Twitter and Facebook might have a wrapper link to the original one, which will redirect.
On iOS, Branch.io uses Universal link to open the app. And universal links don't support redirection. Reference: https://developer.apple.com/forums/thread/28391

**Comment by longbmk** [comment]
Update for iMessage issue: At the 1st time sent to stranger user, Apple will block the link. User need to copy and open in browser then open the app, it will work. If iMessage allow to show the link, just need to click on the link and it can work properly for now. Please notice for it to support user @ritawu91 @JasonLiuBitmark @phuocbitmark @ppupha, cc @moskovich

**Comment by anhnguyenbitmark** [comment]
I updated the FAQ doc for customer support.

**Comment by longbmk** [comment]
Maybe the issue from Social Network app cannot fix. Let me close this ticket.
