### ISSUE TITLE
Postcard - "Postcard sent" button does not update back to "Send postcard" if user tap out to dismiss the share popup without sharing the link

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#3063]
1. Postcard stamped
2. Click on Share Postcard button
3. Tap out to dismiss the share popup without share the link
4. Observe the "Postcard sent" button

Observed result:
It shows "Postcard sent" instead of "Send postcard".

Expected result:
It should back to yellow button to show "Send postcard"

**Comment by anhnguyenbitmark** [comment]
Check the share result `ShareResultStatus.dismissed` and enable the button again.
