### ISSUE TITLE
[Kukai] Already linked popup should be showed when linking account many time

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#31]
Currently, when linking account with Kukai wallet, from the 2nd time, the alias name will be updated instead of showing Already linked popup 

**Steps to reproduce**
1. Launch Autonomy app
2. link Kukai wallet
3. Try to link Kukai wallet again

**Observed result:** 
Already linked popup doesn't display

**Information:**
Build: 0.27.1 (38) (App Center) 
Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)
- Nexus 5X (8.1.0)
- Redmi Note 11S (Android 11)
https://user-images.githubusercontent.com/42630760/163914063-9a7c0f85-3f57-4472-9961-27ca92c13d81.MP4

**Comment by NekhDRej** [comment]
The bug is fixed

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5 
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10
