### ISSUE TITLE
Change request - 1st Claim of user should be changed to real location of user

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#3124]
- [ ] Currently, we are hard-coding to the MoMA location when a user claims for the 1st time. We need to update it to the real location of user. 
- [ ] The formula distance should be updated for the 1st location in AU app
- [ ] The formula distance should be updated for the 1st location in 
website
- [ ] The formula distance should be updated for the backend.
- [ ] Old users still show old data from MoMA because data is recorded to blockchain
- [ ] New users will show the real location.

**Comment by longbmk** [comment]
@moskovich @bencebitmark @anhnguyenbitmark, @lemonlatte should we update for this issue and also update real location for users claimed in MoMA lobby, free QR code, sale QR code? CC: @hvthhien @phuocbitmark @ppupha 

I also have some cases need to figure out and discuss:
- Technical: For the user claim in MoMA lobby, we should round the GPS to show the location from MoMA.
- Does free QR/sale QR claim in the nearly location with MoMA will show from MoMA or real location of user? And do we need to separate the QR from MoMA lobby with QR from free code/sale code?

Thanks,

**Comment by moskovich** [comment]
@longbmk we decided to keep the first claim MoMA. 

In the lobby we should use our TOTP codes, as with the mementos. For online, I believe we are doing this as a single-use QR code. That's my expectation.

**Comment by phuocbitmark** [comment]
@moskovich so for the pay to mint postcard first claim, do we use user's location or keep hard code MoMA?

**Comment by moskovich** [comment]
We always use MoMA's location as the first in the postcard. It doesn't matter if it's paid for or free.

**Comment by phuocbitmark** [comment]
got it, thanks

**Comment by moskovich** [comment]
👍🏻👍🏻
