### ISSUE TITLE
Nothing happens after scaning QR to load all user's Artworks to Autonomy Viewer 

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#313]
1. Open Autonomy app in Chromecast
2. Open Autonomy app in iOS TestFlight
3. Scan QR code of Autonomy Viewer in Chromecast

Observed result:
Nothing happens after scanning

Expected result:
All artworks of Autonomy display in Autonomy Viewer of Chromecast

**Comment by longbmk** [comment]
This bug still happens in build 0.31.0(3) in production

**Comment by hungqd** [comment]
1 point: investigate issue.
