### ISSUE TITLE
[iOS] [Audio Artwork] Audio Artwork detailed view disappears when playing it then minimizing, relaunching it 3 times

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#317]
1. Open an Audio artwork in iOS
2. Minimize and relaunch app 3 times
3. Observe the Audio artwork detailed view

Observed result:
The Detail view switches to white screen.

Expected result:
The Audio artwork relaunch with correct detailed view
https://user-images.githubusercontent.com/109057362/182558223-f91ab41b-7a0e-4024-837e-3cb3b72f628a.mp4

**Comment by hungqd** [comment]
Can't reproduce on iPhone 8 (iOS 15.6)

**Comment by longbmk** [comment]
It seems this issue no longer happens after some fixed bugs. I also cannot reproduce it in iPhone XS max
