### ISSUE TITLE
Postcard - Missing a warning message when user close GPS location and submit the Stamp

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#3175]
@caseyalt We need your help to design a message to warn the user that distance will not be calculated if user is Web (Not share location).
We have 4 cases in here:
- [ ]  GPS and share location --> Submit Location
- [ ] Not open GPS --> Web user
- [ ] Open GPS but not share location --> Web user
- [ ] User got Weak GPS and then stop GPS --> Web user.
The popup should show the warning and have 2 button Ok and Cancel/Update GPS. When user click Ok, we submit user as Web user. If user click Cancel, we not submit and let user update the GPS.

CC @moskovich @anhnguyenbitmark 

This is the video for this issue
https://github.com/bitmark-inc/autonomy-apps/assets/109057362/844bf399-4196-46d5-98f8-ebec9c4e67d5

**Comment by caseyalt** [comment]
@longbmk — are we getting support requests from users about this? Honestly, they don't feel that important to me. Is this only happening on Android?

**Comment by longbmk** [comment]
> @longbmk — are we getting support requests from users about this? Honestly, they don't feel that important to me. Is this only happening on Android?

Hi @caseyalt,
This maybe can happen in iOS. I got it in the past. There is no user asking for support about this but it can make in the future.

**Comment by moskovich** [comment]
Let's just make sure it's clear that the city location is unknown. We are reworking the language here today.

**Comment by longbmk** [comment]
This is a low priority and maybe obsolete. Let me close it and reopen later if it still need to improve.
