### ISSUE TITLE
Cannot scan Postcard QR code within app

### ISSUE THREAD

**Issue by moskovich** [bitmark-inc/autonomy-apps#3181]
It will say "Invalid QR code"

**Comment by ppupha** [comment]
@moskovich could you please share the QRCode? I tried scanning some of Qr code and all of them work.

**Comment by ppupha** [comment]
@moskovich can you give more details about this issue?
The message `Invalid QR Code` is shown only if you scan a qr code does not contain postcard deeplink, which should start with `https://autonomy-app.app.link`

**Comment by moskovich** [comment]
This must have been fixed. It's working now.
