### ISSUE TITLE
[Android][Artwork Detail] The artwork source should be showed in webview instead of open the web browser on device

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#33]
- on iOS, The artwork source is showed in webview
- on Android, The artwork source is showed in the browser

**Steps to reproduce:**
1. Launch Autonomy app
2. Navigate to gallery 
3. Tap to view any artwork on Detail screen
4. Tap on Source 

**Observed result:**
- on Android, The artwork source is showed in the browser

**Information:**
Build: 0.26.8 (35) (App Center) 
Device:
- Nexus 5X (8.1.0)
- Redmi Note 11S (Android 11)

https://user-images.githubusercontent.com/42630760/162772394-05999b8d-f873-4d41-a5a4-af1b7bdcdd54.mp4

**Comment by anhnguyenbitmark** [comment]
@caseyalt I'm not sure if the Android OS supports a built-in Webview like iOS. If that's not the case, should we build our own Webview?

**Comment by caseyalt** [comment]
@anhnguyenbitmark — I guess this is now called "Contract", right? Is there an easy way to see if Android supports anything like a webview? If it's hard, I personally think it's fine to just open it in the browser. There's no security issue with doing that, right?

**Comment by anhnguyenbitmark** [comment]
> There's no security issue with doing that, right?
We just open the artwork pages and some documents. No security issues here.
