### ISSUE TITLE
[Metadata] Medium should be [Video] instead of [Other]

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#36]
Metadata: https://ipfs.io/ipfs/QmcChFEaVKuE8p2X23LHa1z6s6NxtTp5ejkWkmREwvFfrw
--> "mimeType":"video/mp4"

**Steps to reproduce:**
1. Add address: [tz1fTVs1tWbTWHmvJvvu67gHtn9ChWBjoZ7i]
2. Check token detail - metadata 
    Token:  tez-KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton-512632
3. Check metadata: https://ipfs.io/ipfs/QmSxvToBZUZrVNrjmNNp6rnqrRsZNJVgZwfKedkZgnPV5c

**Observed result:**
- Token details: Medium is Other
- Metadata: https://ipfs.io/ipfs/QmcChFEaVKuE8p2X23LHa1z6s6NxtTp5ejkWkmREwvFfrw
--> "mimeType":"video/mp4"

**Information:**
Information:
Build: 0.27.2 (40) (App Center) Device:
- Ip13 pro max OS (15.3)

![Image from iOS (8)](https://user-images.githubusercontent.com/42630760/164283834-977bc0c0-df25-4be1-a262-755ac492d1f6.jpg)

**Comment by NekhDRej** [comment]
The bug is fixed.

iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - fixed
Android build (App center): 0.29.9 (61)
Redmi 8A\Android 10 - fixed

https://user-images.githubusercontent.com/101094775/174783985-9d219669-4078-45f1-9ba8-f8d81cc5d42d.mp4
