### ISSUE TITLE
[iOS][Keychain]The error displays when changing status iCloud Keychain ON <> OFF then deleting Autonomy acc 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#37]
**Steps to reproduce:**
1. Launch Autonomy App
2. Check the setting  iCloud Keychain on device
3. Switch to change  iCloud Keychain status
4. Navigate to Autonomy app 
5. Try to delete account

**Information**:
Build: 0.26.7 (34) (App Center) Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)

https://user-images.githubusercontent.com/42630760/162176482-72677216-69d8-4c43-b463-621b98461d16.MP4

**Comment by NekhDRej** [comment]
The bug is fixed

iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - fixed

https://user-images.githubusercontent.com/101094775/175342654-d1acf625-904d-4723-9e7d-9e16a71eaf38.mp4
