### ISSUE TITLE
[Android] Users are unable to open Release Note after tapping on [Back] btn on Android Navigation bar

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#38]
**Steps to reproduce:**
1. Launch app
2. Open Release Note
3. Tap on Back btn on Android Navigation bar
4. Open Release Note again

**Observed result:**
Nothing happens 

**Information:**
Build: 0.26.8 (35) (App Center) Device:
- Nexus 5X (8.1.0)
- Redmi Note 11S (Android 11)
https://user-images.githubusercontent.com/42630760/162755301-6fed1340-b5c7-47bb-b3ef-dc15bbe3db9e.mp4

**Comment by NekhDRej** [comment]
The bug is fixed

Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10 - fixed
