### ISSUE TITLE
[Android][UI] Some popup/button are displays with incorrect UI after viewing artwork

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#39]
Steps to reproduce:
1. Launch Autonomy app
2. Play some artwork
3. Try to trigger some popup and check the UI (delete account, Turn on Passcode and reopen app)

**Information**:
Build: 0.26.8 (35) (App Center)
 Device:
- Redmi Note 11S (Android 11)
![Screenshot_2022-04-11-21-47-07-892_com bitmark autonomy_client inhouse](https://user-images.githubusercontent.com/42630760/162770793-e161bf36-469e-42aa-a31f-71ae90df35d8.jpg)
![Screenshot_2022-04-11-21-47-27-942_com bitmark autonomy_client inhouse](https://user-images.githubusercontent.com/42630760/162770814-501be3e4-d1ea-4713-a962-21b1f09e5575.jpg)

**Comment by NekhDRej** [comment]
The bug is fixed

Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10 - fixed
