### ISSUE TITLE
[Artwork Detail] Missing Artist information 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#41]
On Artwork detail screen, Artist information does not displayed. However I can see the artist info on Open Sea
https://opensea.io/assets/0x7d8d74b44b433ca6f134e43eec1e63b0c43eeafa/1

Information:
Build: 0.26.8 (35) (App Center) 
Device:
- Ip13 pro max OS (15.3)
- Ip8 (15.2)
- Nexus 5X (8.1.0)
- Redmi Note 11S (Android 11)

https://user-images.githubusercontent.com/42630760/163353783-313e0967-f4ed-45fd-b218-febed6f69791.MP4

**Comment by JasonLiuBitmark** [comment]
@anhnguyenbitmark , reminder to move this to another board.

**Comment by lemonlatte** [comment]
When I check it, it is updated. The information is relies on the upstream api. Opensea sometimes returns data which is mismatched with what it displayed on their site. We currently can not solve this issue.
