### ISSUE TITLE
[Play artwork] The music still plays at Artwork detail screen when tapping on the title of the artwork

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#42]
**Steps to reproduce:**
1. Play any music artwork
2. Tap on the title of the token
3. Check if music still plays or not

**Observed result:**
[Play artwork] The music still plays at Artwork detail screen 

**Information:**
Build: 0.26.8 (35) (App Center)
  Device:
* Ip13 pro max OS (15.3)

https://user-images.githubusercontent.com/42630760/162984809-fc37387b-2091-4574-a652-636ecdf3e6c6.MP4

**Comment by hienphan1472** [comment]
This bug is fixed
