### ISSUE TITLE
[Playback] The error displays when playing pdf artwork at the first time 

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#43]
Steps to reproduce:
1. Launch Autonomy App
2. Link account has pdf tokens
3. Play pdf 

Observed result:
The error displays, however users can view pdf after closing the error popup

**Information:** 
Build: 0.26.8 (35) (App Center)  
Device:
* Ip13 pro max OS (15.3)

https://user-images.githubusercontent.com/42630760/162983571-d25b08ed-182b-46cf-adc3-f830831d7d31.MP4

**Comment by NekhDRej** [comment]
The bug is fixed.

iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - fixed
Android build (App center): 0.29.8 (61)
Redmi 8A\Android 10 - fixed

https://user-images.githubusercontent.com/101094775/174775810-8ad73527-9cab-4864-8321-58130b5d5d64.mp4
