### ISSUE TITLE
Tezos beacon transaction was signed with incorrect information

### ISSUE THREAD

**Issue by anhnguyenbitmark** [bitmark-inc/autonomy-apps#44]
A user was trying to sign a Tezos transaction (send an NFT to a new owner) using Tezos beacon from objkt website.
The transaction was confirmed as successful, but the token isn't transferred to the new owner.
- The user lost the gas fee.
- Even if the transaction is signed with correct data, the Autonomy app doesn't refresh with the new owner.

Build information:
- Platform: iOS
- App version: 0.27.1

**Comment by NekhDRej** [comment]
The bug is fixed.
iOS build (App center): 0.29.8 (64)
iPhone 12\iOS 15.5

https://user-images.githubusercontent.com/101094775/174269172-c67b2987-1990-4d09-9fc9-bf8ffaeccf11.mp4
https://user-images.githubusercontent.com/101094775/174269215-82216a39-997c-40d0-b7f4-f4d92aebd9d4.mp4
