### ISSUE TITLE
Black screen displays in Au when Discovery return an artwork that is deleted/burned in Blockchain

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#447]
1. Open Au app
2. Click on Discovery icon
3. Swift to next to see the blank screen in Discovery.

Expected result:
Caching server should sync/delete the burned token do not cache it. Data returns will contain only available artwork, not contain deleted/burned artwork

https://user-images.githubusercontent.com/109057362/183595845-a21df119-8bee-4f72-9b8a-d0208db3a08c.MP4

**Comment by hxw** [comment]
[2022-08-16..17] 1 unit start of a burn NFT event to remove feed items that have be "deleted"

**Comment by hxw** [comment]
Related PRs:
https://github.com/bitmark-inc/autonomy-event-feed/pull/3
https://github.com/bitmark-inc/nft-indexer/pull/1

**Comment by hxw** [comment]
@lemonlatte  would you look at the above PRs.
Especially the indexer one - If OK, would you merge it and deploy indexer to dev.
After I can deploy the event feed to dev for further testing

**Comment by longbmk** [comment]
This issue no longer happens.
Thank you very much @hxw @lemonlatte
