### ISSUE TITLE
Loading animation displays forever if there is not enough crypto to buy the token on objkt.com

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#47]
**Information:**
Build: 0.26.8 (35) (App Center)
Device:
* Ip13 pro max OS (15.3)

https://user-images.githubusercontent.com/42630760/162988676-761f33b3-78d0-4b45-8a32-cefb8da1bf4b.MP4

**Comment by hienphan1472** [comment]
This bug is fixed. Send button is disabled
![IMG_3708](https://user-images.githubusercontent.com/33851123/170942647-6100d5e3-84f3-4f9e-ad4d-51c40775bd76.PNG)
d
