### ISSUE TITLE
Tezos NFTs won't stay hidden.

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#48]
IndexerID: tez-KT1KrTm6Aei9zp6UH7zYi5EUx23PAvcoK5B5-2
TokenURL: https://objkt.com/asset/KT1KrTm6Aei9zp6UH7zYi5EUx23PAvcoK5B5/2

- Open tezos artwork deatil
- Tap option to hide artwork
- Use the app normally after 1-2 hours
- The artwork became unhide.

**Comment by moskovich** [comment]
I think this should be medium because the user's actions are lost.

**Comment by NekhDRej** [comment]
The bug is fixed.
iOS build (App center): 0.29.8 (64)
iPhone 12\iOS 15.5
Android build (App center): 0.29.8 (60)
Redmi 8A\Android 10 - fixed

https://user-images.githubusercontent.com/101094775/174295865-1f0361c9-bd15-461b-b19a-bc3c79cc3081.mp4
