### ISSUE TITLE
[TV] Videos with Incorrect Aspect Ratios

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#52]
Asset URL: http://www.morehshin.com/moonfaced/

**Observed result:**

https://user-images.githubusercontent.com/50816149/169930197-b4b93327-41b8-4838-a540-b48abf7c862a.mp4

**Expected result:**
https://user-images.githubusercontent.com/42630760/164285370-abb6ac2c-094b-40f6-9e54-4f2ecacbf1d3.MP4

**Comment by thuyenBitmark** [comment]
@moskovich updated (covert .mov to .mp4). how about it now?

**Comment by moskovich** [comment]
yes, that works. But this is a problem with the artwork itself. Can you add this into our FF list to fix? We should not treat it as an autonomy bug.

**Comment by NekhDRej** [comment]
The issue is fixed. The aspect ratio works as expected, the image\video is not stretched

Environment:
iOS build (TestFlight): 0.30.0 (2)
iPhone 12\iOS 15.5
TV build: 1.1.5
Chromecast with Google TV
