### ISSUE TITLE
"Link requested" message still displays although user authorized FF account in Web

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#534]
Pre-condition:
1. FF web has not login
Steps:
1. Open Au app
2. Click on "+ Account->Add-> Feral File"
3. Login to Feral File web
4. Authorize the web to back to Au app

Observed result:
The account does not link and the "Link requested" message still displays

Expected result:
The FF account is linked and "Link requested" message disappears
https://user-images.githubusercontent.com/109057362/183881259-885e9947-a0c9-4964-b438-9e36ed89ef42.MP4

**Comment by anhnguyenbitmark** [comment]
We will remove the web3 login soon (after Feral File cycle 19). This issue won't be valid anymore. We can keep the behavior as is.

**Comment by longbmk** [comment]
This function will be no longer valid in some next cycle, so that this issue will not fix and we need to close it.

**Comment by longbmk** [comment]
We need to get back and fix this issue with high priority because some users need to link FF account and they reported the issue
