### ISSUE TITLE
[Enhancement] [TV] [Gallery] The thumbnail of the artworks should be in the same frame size

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#56]
Information: 
Device: TV
Attachment: 
![framesize](https://user-images.githubusercontent.com/42630760/163772014-bf6d459a-07f4-4af0-b632-4400226e25a4.jpg)

**Comment by NekhDRej** [comment]
The issue is fixed

Environment:
iOS build (TestFlight): 0.30.0 (2)
iPhone 12\iOS 15.5
TV build: 1.1.5
Chromecast with Google TV
![size_thumbnail](https://user-images.githubusercontent.com/101094775/179504109-6b67c5bd-8ea3-49da-a9d6-ebabcfc75321.jpg)
