### ISSUE TITLE
All setting should be restored after reinstalling or update app

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#57]
Steps to reproduce:
1. Launch Autonomy app
2. Change some setting eg: Hide artwork, Hide from Category, Turn on Face ID...
3. Uninstall app
4. ReInstall app

Observed result:
All setting are default setting

Setting:
- Sort gallery by
- Immediate Playback
- Face ID
- Notification
- analytic 
- Hide from Gallery

Information:
Build: 0.27.2 (40) (App Center) 
Device:
- Ip13 pro max OS (15.3)
https://user-images.githubusercontent.com/42630760/164595491-88ba71fd-4d8a-4b1b-8437-b89e8edbd4c7.MP4

**Comment by thuyenBitmark** [comment]
There are backup data:
```
- immediatePlaybacks
- isAnalyticsEnabled
- guideViewed
- finishedSurvey
- hidden tokens
- hidden accounts
```

More information in: https://bitmark.slack.com/archives/C01EPPD07HU/p1653874211206729

**Comment by NekhDRej** [comment]
The bug is fixed

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5 
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10
