### ISSUE TITLE
Rounding (for USD) needs to be to two decimal places

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#58]
https://bitmark.slack.com/archives/C034EPS6CLS/p1646782093025639

Steps:
1. Link a Feral File account (which has tokens in their collection) into Autonomy
2. Click to navigate to Feral File token Details Screen.
3. Scroll to Value Section and check the result

Expected result:
- Rounding (for USD) needs to be to two decimal places (Example: 77.00 USD)

**Comment by hienphan1472** [comment]
This bug still happens on build 0.29.1 (57)
Tested on iphone 12
![IMG_3709](https://user-images.githubusercontent.com/33851123/170943826-1bde29c2-bb19-484a-af51-294cf488884b.PNG)

**Comment by NekhDRej** [comment]
The issue is fixed. 

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10
