### ISSUE TITLE
Sometime, black screen displays and user cannot interact anything in Au app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#581]
We have not found the specific steps yet. We just know there is this bug in system. This is the trace log when I got this issue. Please kindly take a look at this. This bug happens several times but really hard to reproduce.
[c470fb71e54f1eca0e72203c6dc50fe76f92aaa03f9c039859ce1d8062ae2184.txt](https://github.com/bitmark-inc/autonomy-apps/files/9306766/c470fb71e54f1eca0e72203c6dc50fe76f92aaa03f9c039859ce1d8062ae2184.txt)

https://github.com/bitmark-inc/au-support-board/issues/451

**Comment by hvthhien** [comment]
I don't see this happen anymore for a long time. During refactor to apply to lints, I optimized something maybe resolve this issue. Please help to test if this is still occur or not.
