### ISSUE TITLE
I’m trying to register my profile on Tezos profiles and also verify my Twitter handle but in both scenarios I get an Invalid Bse58 error message

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#61]
https://github.com/bitmark-inc/au-support-board/issues/101

**Comment by NekhDRej** [comment]
The bug is fixed.
iOS build (App center): 0.29.8 (64)
iPhone 12\iOS 15.5 - fixed
Android build (App center): 0.29.8 (60)
Redmi 8A\Android 10 - fixed

https://user-images.githubusercontent.com/101094775/174627293-a38d00d8-c541-4272-8345-5dc479a2c1f7.mp4
