### ISSUE TITLE
The unexpected notification "All files have been  downloaded" are sent to the user

### ISSUE THREAD

**Issue by hienphan1472** [bitmark-inc/autonomy-apps#67]
When all the images are downloaded, this unexpected notification are sent to the user. We should prevent that from happening.

**Comment by hienphan1472** [comment]
![1828](https://user-images.githubusercontent.com/33851123/170917131-1d987d8d-2196-4d0c-af69-01dd9dfd5b0e.jpeg)

**Comment by NekhDRej** [comment]
@hienphan1472 This notification is shown to me only after buying the new NFT or re-install app. Is it expected behavior?

**Comment by hienphan1472** [comment]
Yes, it's as expected

**Comment by NekhDRej** [comment]
The bug is fixed

iOS build (App center): 0.29.9 (65)
iPhone 12\iOS 15.5 - fixed
Android build (App center): 0.29.9 (61)
Redmi 8A\Android 10 - fixed

**Comment by longbmk** [comment]
This bug re-happens in build: 0.31.0(3)
