### ISSUE TITLE
Not all video NFTs show the option to fast forward / rewind or view video length

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#7]
https://discord.com/channels/768706944097058828/883766547888357386/963512740851363930

Not all video NFTs show the option to fast forward / rewind or view video length. "Environment" by Jared Tarbell (Field Guide) is one of the videos that does not show a time-scrubber or any of the other options (like airplay). None of the videos from the Field Guide collection have this option, so I would guess it applies to all FeralFile NFTs. NFTs coming from ETH, such as A Cube by Pak show a time-scrubber on the "View Artwork" page

Steps to reproduce: 
- Open the app
- click on the thumbnail of a video NFT from FeralFile
- notice no options are available, click on the screen, no options show up. 
- Close that piece, click on the thumbnail of a video NFT from the ETH network, notice the video scrubber is available, tap to hide / show the scrubber

Information:
Build: 0.26.8 (35) (App Center
)Device:
- Ip13 pro max OS (15.3)
- Redmi Note 11S (Android 11)

https://user-images.githubusercontent.com/42630760/163130154-9f29994e-8c7d-4106-af89-8114d5a13bbf.MP4

**Comment by NekhDRej** [comment]
The bug is not fixed

iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5 - not fixed
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10 - not fixed

https://user-images.githubusercontent.com/101094775/176382995-471051f1-edab-4f3f-bf2f-c353e7c14f51.mp4

**Comment by anhnguyenbitmark** [comment]
This bug is not up-to-date.
We fixed the issue with the scrubber. Now it doesn't show the scrubber anymore.
For the options for fast forward / rewind or view video length, we don't support that intentionally.
The expected behaviors are:
- The player doesn't show the scrubber.
- The player plays the video in a loop.
- The player doesn't provide the option to fast forward / rewind or view video length.

**Comment by NekhDRej** [comment]
The bug is fixed

iOS build (App center): 0.30.0 (67)
iPhone 12\iOS 15.5 
Android build (App center): 0.30.0 (63)
Redmi 8A\Android 10

**Comment by NekhDRej** [comment]
ads

**Comment by anhnguyenbitmark** [comment]
Hi @NekhDRej for the other medium type, since we cannot detect the video, the current solution is to treat it as a webpage.
