### ISSUE TITLE
Fxhash show incorrect information after purchase/transfer nft

### ISSUE THREAD

**Issue by hvthhien** [bitmark-inc/autonomy-apps#71]
- Purchase an item in Fxhash via Autonomy App.
- After purchasing successfully, the page still shows the error injecting into the blockchain

Expected: There should be a success message after purchasing.

**Comment by NekhDRej** [comment]
Blocked by https://github.com/bitmark-inc/autonomy-apps/issues/70

**Comment by NekhDRej** [comment]
The bug is fixed

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10
