### ISSUE TITLE
App should show alert notify when sending/estimating failed with xtz operation request

### ISSUE THREAD

**Issue by hvthhien** [bitmark-inc/autonomy-apps#73]
Try to buy an NFT via any Tezos Dapp that has a price larger than your balance.

Expected: The app should show the warning about estimation failed - don't have enough Tezos balance.

**Comment by NekhDRej** [comment]
The task is done

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10
