### ISSUE TITLE
Freeze app when attaching debug file

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#75]
https://user-images.githubusercontent.com/50816149/171774842-4d7bda0c-8ef0-4bc6-a37d-1de9353f852c.MP4

**Comment by NekhDRej** [comment]
The issue is partly fixed. Still, The app starts freezing on the Android

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5 - fixed
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10 - not fixed

**Comment by NekhDRej** [comment]
The bug is fixed

Environment:
iOS build (App center): 0.31.1 (74)
iPhone 12\iOS 15.5
Android build (App center): 0.31.1 (70)
Redmi 8A\Android 10
