### ISSUE TITLE
Error when trying to subscribe

### ISSUE THREAD

**Issue by anhnguyenbitmark** [bitmark-inc/autonomy-apps#77]
It shows an error message that prevents users from purchasing.

OS: iOS
Device: iPhone

**Comment by NekhDRej** [comment]
The bug is fixed.
iOS build (Testflight): 0.29.3 (2)
iPhone 12\iOS 15.5 - fixed

https://user-images.githubusercontent.com/101094775/174323675-02a9773d-bb9b-4ee0-a747-2405d4aa9e3c.mp4
