### ISSUE TITLE
Cant connect to objk.com

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#78]
Failed to addPeer, The operation couldn’t be completed. (BeaconCore.Beacon.Error error 7.)

**Comment by NekhDRej** [comment]
The issue is not reproduced

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5 
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10
