### ISSUE TITLE
[Android] Send XTZ transaction failed with kalamint

### ISSUE THREAD

**Issue by hvthhien** [bitmark-inc/autonomy-apps#79]
https://github.com/bitmark-inc/au-support-board/issues/146
- The operation request on Android was failed to sent

**Comment by NekhDRej** [comment]
The bug is fixed.
Android build (App center): 0.29.8 (60)
Redmi 8A\Android 10 - fixed

https://user-images.githubusercontent.com/101094775/174072278-7a849602-e295-4003-abac-381d04c7760b.mp4
