### ISSUE TITLE
Origination operation request failed via Tezos Beacon

### ISSUE THREAD

**Issue by hvthhien** [bitmark-inc/autonomy-apps#86]
Steps:
- Login to https://tzprofiles.com/ by connecting with Autonomy App.
- Setup a tezos profile.
- Deloy the profile.
- There will be a missing origination request to create a contract.

**Comment by JasonLiuBitmark** [comment]
From customer support request:
https://github.com/bitmark-inc/au-support-board/issues/162

**Comment by hvthhien** [comment]
The whole process is the contract is successfully deployed and will show the status `Deployed` on the main page after the transaction is confirmed.

**Comment by NekhDRej** [comment]
The bug is fixed.
iOS build (App center): 0.29.8 (64)
iPhone 12\iOS 15.5 - fixed

https://user-images.githubusercontent.com/101094775/174549247-63873508-cda2-48c3-83d1-cfc8b2d40f8c.mp4
