### ISSUE TITLE
Slow to open the app

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#88]
"My app is taking FOREVER to open up now. I counted 22 seconds on the last open and that was after closing everything and rebooting. It could be an internet issue on my end- not so great"

https://github.com/bitmark-inc/au-support-board/issues/192

**Comment by NekhDRej** [comment]
The issue is not reproduced

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5 
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10
