### ISSUE TITLE
There is nothing to prevent the screen from turning off while watching a video NFT

### ISSUE THREAD

**Issue by lynguyen278** [bitmark-inc/autonomy-apps#9]
This bug only happens on some videos. I can reproduce it with FF video 
Acc

https://discord.com/channels/768706944097058828/883766547888357386/963512740851363930

There is nothing to prevent the screen from turning off while watching a video NFT. If you watch something longer than your screen timeout, your phone will lock. This means you have to tap the screen a few times while watching long videos to keep it playing. Other apps like YouTube with video-based content are able to prevent this from happening while a video is playing

**Steps to reproduce:** 
- Set your auto-lock setting to a low value to make testing easier
- open the app
- navigate to the "View Artwork" page of a long video NFT (like Entity by Jared Tarbell)
- do not touch the phone, your phone will lock before the video finishes playing

**Information:**
Build: 0.26.8 (35) (App Center)
Device:
* Ip13 pro max OS (15.3)
* Redmi Note 11S (Android 11)

https://user-images.githubusercontent.com/42630760/163132278-8f6a8dc1-62e2-4dee-b81f-971f24030c92.MOV

**Comment by hienphan1472** [comment]
Fixed on ver 0.29.1 (57).
