### ISSUE TITLE
iOS chrome (time, signal strength, battery) is showing over the artwork during playback

### ISSUE THREAD

**Issue by caseyalt** [bitmark-inc/autonomy-apps#95]
https://github.com/bitmark-inc/au-support-board/issues/219

![b2c8892f731fab4d08768cbb0d70723c5aca051df4ec2557ef6f3a1c2fdfe54c](https://user-images.githubusercontent.com/1546286/174510092-d9248005-6efe-4bb1-b528-332d7b921f0d.jpeg)

**Comment by NekhDRej** [comment]
The bug is fixed.

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5 
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10
